### ISSUE TITLE
sfp_accounts.py User accounts

### ISSUE THREAD

**Issue by WebBreacher** [smicallef/spiderfoot#101]
Wanted to let you know that I've moved the recon-ng JSON user account enumeration file from the profiler module to its own project to ensure that it is updated and expanded more easily. The new project is at [(https://github.com/WebBreacher/WhatsMyName)]. 

I've modified the profiler recon-ng module to pull the raw JSON file from github at run-time (instead of embedding it in recon-ng). The new recon-ng code is in the staging branch right now if you'd like to see it.

The JSON file in the **WhatsMyName** project is easy to understand (I've made a readme.md file in the project to also explain its usage) without looking at the [https://bitbucket.org/LaNMaSteR53/recon-ng/branch/staging] code.

**Comment by smicallef** [comment]
Updated and now on master. Thanks a lot, this is a really valuable resource!
