### ISSUE TITLE
Bitcoin data input

### ISSUE THREAD

**Issue by leotrubach** [smicallef/spiderfoot#1017]
I wrote bitcoin who's who and bitcoin abuse modules.
It is always nice to have possibility to test it using web interface (to see how it works). How do i do that? Is that supported?

**Comment by smicallef** [comment]
Not supported yet but something intended for 3.3, since we now have additional modules for processing bitcoin addresses.

**Comment by smicallef** [comment]
Done in https://github.com/smicallef/spiderfoot/pull/1025
