### ISSUE TITLE
another error which has me asked to get reported.

### ISSUE THREAD

**Issue by Whichcraft** [smicallef/spiderfoot#104]
ERROR	

Unhandled exception (UnboundLocalError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/opt/spiderfoot-2.7.0/sfscan.py", line 255, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/opt/spiderfoot-2.7.0/sflib.py", line 1436, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot-2.7.0/modules/sfp_bingsearch.py", line 82, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot-2.7.0/sflib.py", line 1436, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot-2.7.0/modules/sfp_dns.py", line 164, in handleEvent\n    self.processHost(match[1], parentEvent, affiliate=False)\n', '  File "/opt/spiderfoot-2.7.0/modules/sfp_dns.py", line 388, in processHost\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot-2.7.0/sflib.py", line 1436, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot-2.7.0/modules/sfp_dns.py", line 220, in handleEvent\n    self.processHost(addr, parentEvent, False)\n', '  File "/opt/spiderfoot-2.7.0/modules/sfp_dns.py", line 388, in processHost\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot-2.7.0/sflib.py", line 1436, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot-2.7.0/modules/sfp_ir.py", line 337, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot-2.7.0/sflib.py", line 1436, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot-2.7.0/modules/sfp_xforce.py", line 192, in handleEvent\n    e = SpiderFootEvent(evtType, entry, self.__name__, event)\n', "UnboundLocalError: local variable 'evtType' referenced before assignment\n"]

**Comment by smicallef** [comment]
This is now fixed on github and will be in the upcoming 2.7.1 release in a few days.
