### ISSUE TITLE
DNS / Shared IP

### ISSUE THREAD

**Issue by adon90** [smicallef/spiderfoot#105]
It seems it doens't obtain all the domain names for a given IP, apparenty it gathers the first entry nslookup gives, so each time, I get one subdomain. 
I have tried calling dig -x <ip> +short for getting all the subdomains/virtual hosts but haven't been able to implement it successfuly.
dig -x would be great to include and necessary, because as I said, each time it shows a different subdomain in the "Internet Name" section.

**Comment by smicallef** [comment]
Could you e-mail me the target you are seeing this behaviour with?

**Comment by bcoles** [comment]
SpiderFoot should now return all IP addresses for each `INTERNET_NAME` object.
