### ISSUE TITLE
Response strings seem truncated.

### ISSUE THREAD

**Issue by cyberlive-debug** [smicallef/spiderfoot#1078]
As I mentioned before, we are calling various APIs and getting their responses in custom modules within SpiderFoot.  Some of these being PIPL, PeopleData and SocialSearcher.  The response strings (JSON) from these can be very lengthy.  As I go through our results it appears the responses are being truncated.  If I grab the response and throw it into something like Notepad++, it tells me that the response is cut off at 1024 characters.  These are returning the RAW_RIR_DATA.  

There are no errors and everything appears to be fine until I noticed it appears cut.  Is there a limit to the response string in SpiderFoot?  We are using the fetchURL() function to do so.  

Python 3.8

SpiderFoot 3.2

Thanks.

**Comment by bcoles** [comment]
> 
> 
> As I mentioned before, we are calling various APIs and getting their responses in custom modules within SpiderFoot. Some of these being PIPL, PeopleData and SocialSearcher. The response strings (JSON) from these can be very lengthy. As I go through our results it appears the responses are being truncated. If I grab the response and throw it into something like Notepad++, it tells me that the response is cut off at 1024 characters. These are returning the RAW_RIR_DATA.
> 
> There are no errors and everything appears to be fine until I noticed it appears cut. Is there a limit to the response string in SpiderFoot? We are using the fetchURL() function to do so.
> 
> Python 3.8
> 
> SpiderFoot 3.2
> 
> Thanks.

Yes, the limit is set in the `modules/sfp__stor_db.py` module. It is configurable via the Settings page.

![sfp__stor_db settings](https://user-images.githubusercontent.com/434827/94260913-51b00200-ff74-11ea-8e52-44e500e2c0f2.png)

**Comment by cyberlive-debug** [comment]
That worked great, thanks for the quick response.
