### ISSUE TITLE
Uninitialized evtType in sfp_xforce.py

### ISSUE THREAD

**Issue by bardicknowledge** [smicallef/spiderfoot#108]
I ran into a fatal exception in sfp_xforce.py around line 201:
e = SpiderFootEvent(evtType...

The message indicated that evtType was uninitialized.  I'm guessing the error occurs because an eventName shows up that is not recognized (around line 133).  I'm testing a fix to add a catch-all and log the eventName to self.sf.info.  Of course, this means that I'm changing most of the ifs to elifs.

**Comment by smicallef** [comment]
Hi, a fix for this should already exist in Github. Did you pull the latest version? A bug fix release will happen in the next few days.

**Comment by smicallef** [comment]
Fix deployed.
