### ISSUE TITLE
Add "request.show_tracebacks" to disable tracebacks log when failing authentication

### ISSUE THREAD

**Issue by mathiznogoud** [smicallef/spiderfoot#1083]
I'm using the lastest version of spiderfoot v3.2.1
According to my setups, when I'm unauthenticated I got redirected to a 401 page with a full tracebacks log.
I think this should be disable by adding request.show_tracebacks : false to the conf['/'] when enabling HTTP Auth.

**Comment by bcoles** [comment]
Tracebacks are useful. They are raised only when there is a bug.

I've created a PR #1084 to resolve the handling of 401 errors cleanly.
