### ISSUE TITLE
sfwebui: settings boolean options rendered as text boxes rather than combo boxes

### ISSUE THREAD

**Issue by bcoles** [smicallef/spiderfoot#1093]
Boolean options are rendered in the Settings view as a text box rather than a combo box. For example, the setting to enable debugging:

![settings text box](https://user-images.githubusercontent.com/434827/94990322-83514a80-05be-11eb-86bb-0ae07797cc08.png)

**Comment by smicallef** [comment]
Fixed in fa0ac543782a5823d01609df67d1ca9a26043876
