### ISSUE TITLE
No option to specify TOR control port authentication method

### ISSUE THREAD

**Issue by ecapuano** [smicallef/spiderfoot#110]
Use Case: I want to use a nearby (same LAN) TOR relay as the proxy for Spiderfoot.

My scans are failing after sometime because when Spiderfoot attempts TOR circuit regeneration, it fails to authenticate to the control port of the proxy running on the relay. 

Spiderfoot proxy config asks for TOR control port, but not a control password or cookie setting... How would Spiderfoot authenticate to the TOR control port to send commands? Is it only designed to use a local TOR client running on the same host?

**Comment by nopara73** [comment]
From the [Tor manual](https://www.torproject.org/docs/tor-manual.html.en).  

> Note: unless you also specify one or more of HashedControlPassword or CookieAuthentication, setting this option will cause Tor to allow any process on the local host to control it.

I did not look into the source code, so I don't know for sure if this is the case. I hope it helped.

**Comment by smicallef** [comment]
Yes, SpiderFoot is only intended to talk to a local TOR server.
