### ISSUE TITLE
Spiderfoot issue

### ISSUE THREAD

**Issue by Unknow13** [smicallef/spiderfoot#1107]
[!] Failed communicating with server: HTTPConnectionPool(host='127.0.0.1', port=5001): Max retries exceeded with url: /ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c82dad310>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by bcoles** [comment]
You must start the SpiderFoot web server first.

```
python3 ./sf.py -l 127.0.0.1:5001
```

**Comment by daityac0r0k0** [comment]
small correction.
gedit sf.py - change port to 5005 or any other equivalent
run - python3 ./sf.py -l 127.0.0.1:5005
