### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by omarkurt** [smicallef/spiderfoot#111]
I got an error while running python sf.py

Can you please write the module names with version numbers to the requirements.txt?

```
python sf.py

Critical Start-up Failure: No module named M2Crypto
=================================
It appears you are missing a module required for SpiderFoot
to function. Please refer to the documentation for the list
of dependencies and install them.

Python modules required are:
 - M2Crypto
 - netaddr
 - dns
 - cherrypy
 - mako
 - socks
 - pyPdf
 - metapdf
 - openxmllib
 - stem
 - bs4
 - gexf
 - phonenumbers

If you are running on Windows and getting this error, please report this as a bug to support@spiderfoot.net. 
```

**Comment by vroomgalaxy** [comment]
This is path error `export PYTHONPATH=/usr/local/lib/python2.7/dist-packages/:$PYTHONPATH`

However after this lxml is giving a etree error
`Critical Start-up Failure: /usr/local/lib/python2.7/dist-packages/lxml/etree.so: undefined symbol: PyFPE_jbuf`

Python environment is set to UCS-2. Tried to convert sf.py to dos2unix, but still getting same error.

**Comment by smicallef** [comment]
requirements.txt file has been added - please let me know if you still have problems. It would be helpful to know the Linux distro and version you are using.

**Comment by cwdsystems** [comment]
pip install future

**Comment by bcoles** [comment]
https://github.com/smicallef/spiderfoot/issues/242#issuecomment-471227576

**Comment by bcoles** [comment]
`future` is now included in `requirements.txt` as of 41677bcaae9495dcb70c9ac06d05c0b1de6cdcb0.
