### ISSUE TITLE
Can we run this as a batch?

### ISSUE THREAD

**Issue by cyberlive-debug** [smicallef/spiderfoot#1110]
We love the SpiderFoot tool, have incorporated a lot of modules to get where we need to be.  If we had a list of names/email/usernames to run.  For example, 5 or 10, is there a way to run this as a batch?  Loop through the input data in a CSV or some other kind of file?  Is there a limit if it can be batched?

Python 3.8

SpiderFoot 3.2

Thanks for your time.

**Comment by cyberlive-debug** [comment]
Is there a way to run this as a batch?  Can you please provide a follow up for this?

Thanks.

**Comment by bcoles** [comment]
> 
> 
> Is there a way to run this as a batch? Can you please provide a follow up for this?
> 
> Thanks.

SpiderFoot does not support creating multiple scans from an input file of targets.

However, you could use `sf.py` command line. Alternatively, you could create scans by using HTTP POST requests to the web server, although I wouldn't recommend this approach as the web server and routes are likely to change in the future.

Both approaches require writing the CSV parsing yourself to extract the target for the scan from the input file.

For example, to identify subdomains for `example.com` using the `sfp_crt` module and perform DNS resolution:

```
./sf.py -s 'example.com' -m sfp_crt,sfp_dnsresolve
```

The command line does not support "use cases" as offered by the web interface (`Passive`, `Investigate`, etc). You will need to provide a list of all modules you want to run (comma delimited).
