### ISSUE TITLE
Python3.9 -> fraction library deprecated and replaced by math

### ISSUE THREAD

**Issue by trizzosk** [smicallef/spiderfoot#1111]
Please provide a description of the issue and any relevant error messages.
Because of the error, spiderfoot is not starting at all. Error message on shell: cannot import gcd from fractions.

What version of Python are you using?
Python 3.9.0 (default, Oct  6 2020, 00:00:00) 

What version of SpiderFoot are you using (stable release or Git `master` branch)?
stable release

**Solution:**
Recently I upgraded distro to Fedora 33 release which brought python3.9. One of requirements - networkx - uses old module fractions and methods defined. File /usr/local/lib/python3.9/site-packages/networkx/algorithms/dag.py needs to be adjusted:
Line 23: from fractions import gcd
Replace with: from math import gcd

**Comment by bcoles** [comment]
Thanks for the heads up.

The `networkx` requirement is locked at version 2.3. I'm not sure why. It looks like networx version 2.5 fixes this issue.

I've created PR #1112 to bump the minimum required version of networkx to 2.5.

I've tested SpiderFoot starts correctly with these changes with Python 3.8.6. I haven't tested with Python 3.9.

**Comment by trizzosk** [comment]
Thank you. I will change requirements.txt to version you mention and reinstall to see if this helps (I changed the import manually so I assume it will work).

**Comment by trizzosk** [comment]
confirmed as functioning with Python3.9 on Fedora33. I put networkx==2.5 in requirements.

**Comment by bcoles** [comment]
> 
> 
> confirmed as functioning with Python3.9 on Fedora33. I put networkx==2.5 in requirements.

Thanks. I'm more concerned that it might break something for Python 3.6 / 3.7.

I'm not sure why it was pegged to 2.3. None the less, [Python 3.6 end of support is only a year away](https://endoflife.date/python) and we need to move forward.
