### ISSUE TITLE
Feature: Add support to cors

### ISSUE THREAD

**Issue by BillRizer** [smicallef/spiderfoot#1116]
I would like to be able to communicate with the spiderfoot API through another host without receiving the CORS error

**Comment by bcoles** [comment]
You can communicate with the REST API from another host.

CORS only affects clients which enforce the same-origin policy (such as web browsers). Do you require cross-origin access from a web browser? Why? If the user's web browser can interact with SpiderFoot then they could use the SpiderFoot web UI...

As an aside, I don't recommend opening up the SpiderFoot UI for anyone to access, especially without  a password.

None the less, I agree that it would be nice to support CORS. Unfortunately, this isn't as simple as I would like.

We've been talking about replacing CherryPy for a while. And also rewriting the REST API. And separating the web UI from the REST API. But it is a large piece of work.

Part of the reason for this change is the lack of plugins and documentation in the CherryPy ecosystem. It is far less popular than alternatives such as Flask.

I had a look at implementing CORS support to see if there was an easy way to fulfill your requirements.

There is a plugin for Cherrypy called `cherrypy_cors`. However, it only has 6 stars on GitHub, and is rarely updated. That's disconcerting.

The author added origin whitelisting only after someone asked for it as if it was an after thought... That's disconcerting. The whole point of CORS is to allow whitelist access. It seems the plugin was originally created to allow wildcard access. That's disconcerting.

Nonetheless, it now supports whitelisting domains, so I had a go at implementing it.

PR is up, pending merge: #1119

Note that this does not support using CORS with credentials. Again, **I strongly discourage exposing SpiderFoot UI without requiring authentication.**

**Comment by BillRizer** [comment]
Hello, thank you very much for the answer,

I am currently creating another page and would like to make requests to know the status of the scans,
a panel with several other things.
 I understand the dangers of cors.

`PR is up, pending merge: #1119`
thanks again :100:
