### ISSUE TITLE
Scans presisting docker container restarts

### ISSUE THREAD

**Issue by whoismikem** [smicallef/spiderfoot#1122]
When running docker container, database appears to be saved into ~/spiderfoo.db. Ability to redirect the db location would be beneficial when using volumes and persisting scans. What's the current way of doing this?

Something like (file: sf.py)
```
data_path = os.environ.get('SPIDERFOOT_DATA')
if data_path:
    sfConfig['__database'] = f'{data_path}/spiderfoot.db'
```

Thanks

**Comment by smicallef** [comment]
Take a look at the latest `Dockerfile` - you can use a volume to store the database outside of the container.
