### ISSUE TITLE
Critical Start-up Failure: No module named six

### ISSUE THREAD

**Issue by vroomgalaxy** [smicallef/spiderfoot#113]
`spiderfoot-master# pip3 install six
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python3.4/dist-packages
Cleaning up...
`
`spiderfoot-master# export PYTHONPATH=/usr/local/lib/python2.7/dist-packages/:$PYTHONPATH
`

`spiderfoot-master# ./sf.py 

Critical Start-up Failure: No module named six
=================================
It appears you are missing a module required for SpiderFoot
to function. Please refer to the documentation for the list
of dependencies and install them.

Python modules required are: 
 - M2Crypto
 - netaddr
 - dns
 - cherrypy
 - mako
 - socks
 - pyPdf
 - metapdf
 - openxmllib
 - stem
 - bs4
 - gexf
 - phonenumbers

If you are running on Windows and getting this error, please
report this as a bug to support@spiderfoot.net.
`

**Comment by smicallef** [comment]
Only Python 2.7 is supported.
