### ISSUE TITLE
Errors and timeouts

### ISSUE THREAD

**Issue by vroomgalaxy** [smicallef/spiderfoot#114]
`SpiderFoot	ERROR	Failed to fetch content from Yahoo`.

`sflib	INFO	Fetching: https://www.facebook.com/xxxxxxxxxxxx/ [user-agent: Mozilla/5.0 (Windows NT       6.1; WOW64; rv:23.0) Gecko/20100101 Firefox/23.0] [timeout: 5]`

`sflib	INFO	Error fetching https://www.linkedin.com/slink?code=gHY7Ux3(<urlopen error [Errno 101] Network is unreachable>)`

**Comment by smicallef** [comment]
Yes this is could be a few things:

1) You temporarily lost network connectivity in general or to that host.
2) Your proxy/TOR lost connectivity temporarily.
3) In cases of Yahoo, Google, etc. possibly some kind of blocking.
