### ISSUE TITLE
"WAITING FOR THE SCAN TO INITIALIZE" Runs forever, and in 127.0.0.1:5001 it just keeps generating the scan.

### ISSUE THREAD

**Issue by neutraandoni** [smicallef/spiderfoot#1151]
Im using the latest version of Python.

I did every step right, and no requirements failed to install.

**Comment by richrumble** [comment]
Same here, new scan's never run no matter how many modules or how little I am trying to scan. They don't save when you click RUN. I let it "initialize" for 24hrs. Let me know how I can help trouble shoot. 
CLI: python3 sf.py -l 127.0.0.1:5001

**Comment by richrumble** [comment]
Upgraded to WSL2 and that fixed the issue for me. Had to reboot, and upgrade the ubuntu kernel, so I just removed the ubuntu app and reinstalled after WSL was upgraded. I hope that helps some others!
