### ISSUE TITLE
Issue with secure module

### ISSUE THREAD

**Issue by Pegase92** [smicallef/spiderfoot#1156]

**Comment by Pegase92** [comment]
Hello,

First of all, many thanks for this very usefull platform.
During the launching process, I notice one error with the module secure : 

`ImportError: cannot import name 'SecureHeaders' from 'secure' (/home/hermes/anaconda3/lib/python3.8/site-packages/secure/__init__.py)`

This not really an error. It is a matter of version for the secure module. In the requirement.txt (being used by pip install), you have just to change the line : 
secure>=0.2.1
by this line
secure==0.2.1

This solve the issue and allow you to enjoy using spiderfoot.

Have a nice day

Pegase

**Comment by bcoles** [comment]
Confirmed.

```
[2021-04-27 07:38:44] root@kali:~/Desktop/spiderfoot# ./run 
Traceback (most recent call last):
  File "/root/Desktop/spiderfoot/./sf.py", line 32, in <module>
    from sfwebui import SpiderFootWebUi
  File "/root/Desktop/spiderfoot/sfwebui.py", line 27, in <module>
    from secure import SecureHeaders
ImportError: cannot import name 'SecureHeaders' from 'secure' (/usr/local/lib/python3.9/dist-packages/secure/__init__.py)
[2021-04-27 07:38:48] root@kali:~/Desktop/spiderfoot# pip3 list | grep secure
secure                       0.3.0
[2021-04-27 07:38:57] root@kali:~/Desktop/spiderfoot# 
```

It appears [version 0.3.0 was released a few hours ago](https://github.com/TypeError/secure/releases) and makes some changes which break backwards compatibility:

> Full redesign of Secure API

Locking the version to 0.2.1 doesn't seem like a good long term solution; however, it is the easiest short term solution. I've created #1157 to fix this.

**Comment by bcoles** [comment]
Also thanks for the heads up.
