### ISSUE TITLE
Unhandled exception (ValueError) encountered during scan.

### ISSUE THREAD

**Issue by la5t5tand** [smicallef/spiderfoot#116]
Not sure that this is the forum to post this, but the error requested I post it, so here it is.

OS- Server 2008 r2

`Unhandled exception (ValueError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "sfscan.pyc", line 255, in startScan\n', '  File "sflib.pyc", line 1436, in notifyListeners\n', '  File "modules\\sfp_bingsearch.pyc", line 92, in handleEvent\n', '  File "sflib.pyc", line 1436, in notifyListeners\n', '  File "modules\\sfp_dns.pyc", line 164, in handleEvent\n', '  File "modules\\sfp_dns.pyc", line 388, in processHost\n', '  File "sflib.pyc", line 1436, in notifyListeners\n', '  File "modules\\sfp_bingsearch.pyc", line 92, in handleEvent\n', '  File "sflib.pyc", line 1436, in notifyListeners\n', '  File "modules\\sfp_spider.pyc", line 259, in handleEvent\n', '  File "modules\\sfp_spider.pyc", line 286, in spiderFrom\n', '  File "modules\\sfp_spider.pyc", line 105, in processUrl\n', '  File "modules\\sfp_spider.pyc", line 196, in contentNotify\n', '  File "sflib.pyc", line 1436, in notifyListeners\n', '  File "modules\\sfp_dns.pyc", line 164, in handleEvent\n', '  File "modules\\sfp_dns.pyc", line 388, in processHost\n', '  File "sflib.pyc", line 1436, in notifyListeners\n', '  File "modules\\sfp_dns.pyc", line 220, in handleEvent\n', '  File "modules\\sfp_dns.pyc", line 388, in processHost\n', '  File "sflib.pyc", line 1436, in notifyListeners\n', '  File "modules\\sfp_hosting.pyc", line 85, in handleEvent\n', '  File "modules\\sfp_hosting.pyc", line 66, in queryAddr\n', 'ValueError: too many values to unpack\n']`

**Comment by smicallef** [comment]
I just pushed a fix for this to the repo - could you do a git pull and re-try?

**Comment by danTaler** [comment]
Seems to be working now, I guess you can close this issue.

Thanks!
