### ISSUE TITLE
Opencorporate API

### ISSUE THREAD

**Issue by tsmitsmitonline** [smicallef/spiderfoot#1160]
Could you add search 'company name' and 'office name' on Opencorporate API search?

I have added the Opencorporate API to the module, but when I search on a "Human Name" (as company name or officer name, I don't get results.

**Comment by bcoles** [comment]
The `sfp_opencorporates` module watches for `COMPANY_NAME` events:

https://github.com/smicallef/spiderfoot/blob/b7a6cf8cdf8b2419cc10ee2ad9dfbcee52ce6b29/modules/sfp_opencorporates.py#L62-L63

It does not support searching for `HUMAN_NAME` events using the `officers/search` API endpoint. This would result in far too many false positives to be useful.
