### ISSUE TITLE
Traceback (most recent call last):   File "/root/spiderfoot/./sf.py", line 26, in <module>     import cherryPy ModuleNotFoundError: No module named 'cherryPy'

### ISSUE THREAD

**Issue by Rajmsr** [smicallef/spiderfoot#1162]
Please provide a description of the issue and any relevant error messages.

If you can provide an application stack trace that is even better.

What version of Python are you using?

What version of SpiderFoot are you using (stable release or Git `master` branch)?

You may also wish to check if your issue has been posted previously:

* https://github.com/smicallef/spiderfoot/issues

**Comment by bcoles** [comment]
Have you installed the necessary requirements with `pip3 install -r requirements.txt` ?

**Comment by Rajmsr** [comment]
┌──(root💀kali)-[~/spiderfoot]
└─# pip3 install -r requirements.txt                    
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/adblockparser/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/adblockparser/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/adblockparser/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/adblockparser/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/adblockparser/
Could not fetch URL https://pypi.org/simple/adblockparser/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/adblockparser/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement adblockparser>=0.7 (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for adblockparser>=0.7 (from -r requirements.txt (line 1))
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

**Comment by bcoles** [comment]
> WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.

Your Python installation is broken. More specifically: Your Python SSL/TLS configuration is broken... somehow. The dependencies cannot be installed without a working Python environment.

Some googling suggests installing `libssl-dev` :

~~~
apt-get install libssl-dev
```

**Comment by C4l1b3r** [comment]
> Have you installed the necessary requirements with `pip3 install -r requirements.txt` ?

I have tried but I get building wheel fails on everything

**Comment by Rajmsr** [comment]
Problem solved
