### ISSUE TITLE
Cannot Connect to Socket Solution Impletmentation

### ISSUE THREAD

**Issue by yupthatguy** [smicallef/spiderfoot#1167]
Please provide a description of the issue and any relevant error messages.
** Error Message:
```
Traceback (most recent call last):
  File "/root/python-environments/spiderfoot-env/lib/python3.7/site-packages/cherrypy/process/servers.py", line 225, in _start_http_thread
    self.httpserver.start()
  File "/root/python-environments/spiderfoot-env/lib/python3.7/site-packages/cheroot/server.py", line 1836, in start
    self.prepare()
  File "/root/python-environments/spiderfoot-env/lib/python3.7/site-packages/cheroot/server.py", line 1791, in prepare
    raise socket.error(msg)
OSError: No socket could be created -- (('--.--.---.---.', 5001): [Errno 99] Cannot assign requested address)
```

What version of Python are you using?
** Python3.7 in a virtual environment

What version of SpiderFoot are you using (stable release or Git `master` branch)?
**https://github.com/smicallef/spiderfoot/archive/v3.3.tar.gz

You may also wish to check if your issue has been posted previously:
** I believe that I have [found the solution to my problem](https://github.com/ipython/ipython/issues/6193), but I have not been able to successfully implement the solution.

Spiderfoot has successfully installed on both my local vbox test server and my vps prod server.  However, while spiderfoot works perfectly on my test server, my prod server generates the above error whenever I execute `python3 sf.py -l server-ip:5001`

This appears to be the solution from a previously closed issue.
https://github.com/ipython/ipython/issues/6193

But being completely new to python, I can't quite figure out the "_how_" part of changing the --ip=value to the suggested --ip=0.0.0.0 for vps servers.

FYI, my `/etc/hosts` file on both my prod server has the following content:
```
# cat /etc/hosts
127.0.0.1	localhost
127.0.1.1       web1.example.com web1

# The following lines are desirable for IPv6 capable hosts
#::1	localhost	ip6-localhost	ip6-loopback
#ff02::1	ip6-allnodes
#ff02::2	ip6-allrouters

XXX.XX.XX.XXX	dehwdobfurefubfu	dehwdobfurefubfu

XXX.XX.XX.XXX	cdckbcrburfbfrflncew	cdckbcrburfbfrflncew
```

Greatly appreciate a helping hand. (I don't support IPv6)

**Comment by bcoles** [comment]
Run `ifconfig` to list your network interfaces. Try one of those IP addresses.

**Comment by yupthatguy** [comment]
Thanks that solved it... For anyone who has the same problem... my vps uses a Private IP vs. Public IP system

My solution was to run:
python3 sf.py -l your-private-ip:5001

Then visiting:
http://your-public-ip:5001/

Thanks
