### ISSUE TITLE
Spiderfoot container :  can't open file 'sf.py': [Errno 13] Permission denied

### ISSUE THREAD

**Issue by AC-WhiteGlint** [smicallef/spiderfoot#1172]
Hi,

I am trying to use spiderfoot as a docker container, however I am getting this error message in the container lgos : /opt/venv/bin/python: can't open file 'sf.py': [Errno 13] Permission denied

If I comment this in the Dockerfile :

`#USER spiderfoot`

Then all is working fine

SO this is clearly a permission issue.

However I don't how to solve it.

I tried to add this line before the it switch to the spider foot user : 

`RUN chown -R spiderfoot:spiderfoot /opt/venv`

but it doesn work

Another question how to pass the file passwd to the container?

I added a few user account but the file was not passed to the container.

Best regards,

AC-WG

**Comment by bcoles** [comment]
> Another question how to pass the file passwd to the container?

As a temporary workaround, after the `COPY . .` line in `Dockerfile`, add:

```
COPY passwd $SPIDERFOOT_DATA
```

**Comment by bcoles** [comment]
> I am trying to use spiderfoot as a docker container, however I am getting this error message in the container lgos : /opt/venv/bin/python: can't open file 'sf.py': [Errno 13] Permission denied

I'm not sure what the issue is here. Are you running `docker build` with `sudo` ?

Perhaps the permissions on your repo are messed up for some reason. For trouble shooting, you could try from scratch:

```sh
git clone https://github.com/smicallef/spiderfoot
cd spiderfoot
sudo docker build -t spiderfoot .
sudo docker run -p 5001:5001 spiderfoot
```

**Comment by AC-WhiteGlint** [comment]
Issue resolved by building the image locally on my laptop and sending it to dockerhub, then pulling it.

For some reason the issue happened on Ubuntu 20.04 server.

**Comment by TimberwolfCyber** [comment]
Was able to duplicate this issue with ease, cloned the git packed, docker-compose build, and ran into the errno 13 permission denied.

This is a closed issue now, but for those who got here from Google and ran into this issue by running docker-compose, I discovered the docker-compose file puts the user in the wrong directory. 

at the end of the file change: && ./sf.py -l 0.0.0.0:5001

to: && /home/spiderfoot/sf.py -l 0.0.0.0:5001
