### ISSUE TITLE
Unable to scan URL

### ISSUE THREAD

**Issue by parag85** [smicallef/spiderfoot#119]
Hi Team,

unable to scan following URL:

URL format:     abc.xyz.com:1234

Error message:  Invalid target type. Could not recognize it as an IP address, IP subnet, domain name or host name.

**Comment by smicallef** [comment]
SpiderFoot doesn't support scanning URLs - only hostnames, domain names, subdomains, IP addresses, netblocks and in 2.8.0, e-mail addresses.
