### ISSUE TITLE
Subdomain - scanning only domain

### ISSUE THREAD

**Issue by danTaler** [smicallef/spiderfoot#120]
Scanning a subdomain shows results only for the main domain:

Target:
**xxx.nsw.gov.au** 

Source Data Element in each module shows:
**nsw.gov.au** 

Modules results:
Account on External Site -> **nsw.gov.au** 
Amazon S3 Bucket -> s3-dpc-**nsw**-website-files.s3.amazonaws.com
...
etc

![image](https://cloud.githubusercontent.com/assets/10904080/21601962/512e46f6-d198-11e6-9943-c0512356c591.png)

**Comment by smicallef** [comment]
Should now be fixed with the latest code on github. 2.9 will have it included, coming out this week.

**Comment by smicallef** [comment]
Should now be addressed in 2.9.0.
