### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by pablovidelayanez** [smicallef/spiderfoot#123]
Hi , the tool show me this error.

![image](https://cloud.githubusercontent.com/assets/9121003/22404625/8ae1a534-e613-11e6-89dd-72c543d43a45.png)

Unhandled exception (UnicodeDecodeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "sfscan.pyc", line 255, in startScan\n', '  File "sflib.pyc", line 1399, in notifyListeners\n', '  File "modules\\sfp_bingsearch.pyc", line 82, in handleEvent\n', '  File "sflib.pyc", line 1399, in notifyListeners\n', '  File "modules\\sfp_dns.pyc", line 164, in handleEvent\n', '  File "modules\\sfp_dns.pyc", line 387, in processHost\n', '  File "sflib.pyc", line 1399, in notifyListeners\n', '  File "modules\\sfp_bingsearch.pyc", line 82, in handleEvent\n', '  File "sflib.pyc", line 1399, in notifyListeners\n', '  File "modules\\sfp_dns.pyc", line 164, in handleEvent\n', '  File "modules\\sfp_dns.pyc", line 391, in processHost\n', '  File "modules\\sfp_dns.pyc", line 478, in processDomain\n', '  File "modules\\sfp_dns.pyc", line 387, in processHost\n', '  File "sflib.pyc", line 1399, in notifyListeners\n', '  File "modules\\sfp_sslcert.pyc", line 99, in handleEvent\n', "UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 47: ordinal not in range(128)\n"]

**Comment by smicallef** [comment]
Thanks for reporting this. Could you tell me (either here or via e-mail) what target you were targeting so I can re-produce it and fix it?

**Comment by pablovidelayanez** [comment]
I can tell you by email, can you give me your e-mail please, thanks!.

**Comment by pablovidelayanez** [comment]
I have an older version, i will try with the last release, if the bugs still i will open a new issue, closed please, thansk in advance.
