### ISSUE TITLE
dns.resolver and sflib module error

### ISSUE THREAD

**Issue by novitae** [smicallef/spiderfoot#1241]
After having run all the steps as written, when I try to launch the `sf.py`, I get the following message :

```
Traceback (most recent call last):
  File "/Users/u/spiderfoot/./sf.py", line 30, in <module>
    from sflib import SpiderFoot
  File "/Users/u/spiderfoot/sflib.py", line 34, in <module>
    import dns.resolver
ModuleNotFoundError: No module named 'dns'
```

I tried many times to install it manually, but It don't works.
Thanks for help.

**Comment by bcoles** [comment]
Ensure you're using Python3 and have run `pip3 install -r requirements.txt`
