### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by arnaudluti** [smicallef/spiderfoot#1245]
Hi,

Thanks for your work,

I'm trying to setup an SF instance, i get the below error when launching the startup script. Requirement "networkx" seems to be greatly satisfied:  
![image](https://user-images.githubusercontent.com/41639163/127303712-e4790c01-e2bb-4f9d-978d-d99dd1d569df.png)

--
**Deb version** : Linux version 4.19.0-13-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.160-2 (2020-11-28)
**Python version**:  3.7
**SF version**: 3.3

--
Already tried:
`sudo apt update -y && sudo apt install python3-networkx`
`sudo python3 -m install networkx`

Thanks in advance,
Arnaud

**Comment by bcoles** [comment]
You have `networkx` version 2.6.2 installed.

It appears that something has changed in `networkx` since 2.5.

As a temporary workaround, you could `pip3 install networkx==2.5`.

**Comment by arnaudluti** [comment]
Hey, thanks for your help. It's ok for networkx.  
However, i got another issue with the "secure" module

![image](https://user-images.githubusercontent.com/41639163/127344625-1c327425-d8e4-40b2-99cf-506c8186ee6e.png)

**Comment by bcoles** [comment]
> EDIT : solved with issue #1166
> Installed secure ver 0.2.1

If you're using the latest version of SpiderFoot from GitHub master branch then this is already patched. You should not need to install `secure==0.2.1`.

**Comment by arnaudluti** [comment]
Ok, i use the version 3.3, but downloaded for the tarball. I think the requirements.txt is not updated in it.
`wget https://github.com/smicallef/spiderfoot/archive/v3.3.tar.gz`
