### ISSUE TITLE
MacOS requirements.txt adaptation

### ISSUE THREAD

**Issue by etr450b** [smicallef/spiderfoot#1252]
Hello,
In order to avoid the errors on MacOS : 
`ImportError: cannot import name 'nx' from 'networkx' (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/networkx/__init__.py)`
and : 
`ImportError: cannot import name 'SecureHeaders' from 'secure' (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/secure/__init__.py)`

while trying to run Spiderfoot after installing the requirements, it is mandatory to adapt the `requirements.txt`

The changes to make inside the file are pretty simple : 
- `secure==0.2.1` instead of `secure>=0.2.1`
- `networkx==2.5` instead of `networkx>=2.5`

It would be great to specify this in the installation instructions.

Hope it helps anyone who is struggling making Spiderfoot works! 💯

**Comment by bcoles** [comment]
Are you using the latest version from the master branch on GitHub?

**Comment by bcoles** [comment]
The following requirements for `secure` and `networks` are defined in `requirements.txt`:

https://github.com/smicallef/spiderfoot/blob/d352037613080454ccdf6ef370639ac820969f98/requirements.txt#L18
https://github.com/smicallef/spiderfoot/blob/d352037613080454ccdf6ef370639ac820969f98/requirements.txt#L22

**Comment by etr450b** [comment]
In order to get the stable version I had to install it with :
`$ wget https://github.com/smicallef/spiderfoot/archive/v3.3.tar.gz`
`$ tar zxvf v3.3.tar.gz`
`$ cd spiderfoot`
`$ pip3 install -r requirements.txt`

**Comment by bcoles** [comment]
> In order to get the stable version

The stable version is a 6+ months old by now. It is about time for a new release.

**Comment by bcoles** [comment]
SpiderFoot 3.4 has been [released](https://github.com/smicallef/spiderfoot/releases/tag/v3.4) which contains an updated `requirements.txt` file.
