### ISSUE TITLE
Kali: ImportError on from cherrypy.lib import auth_digest

### ISSUE THREAD

**Issue by theguly** [smicallef/spiderfoot#128]
running latest sf from git on latest kali rolling i get:
$ python sf.py
Traceback (most recent call last):
  File "sf.py", line 53, in <module>
    from cherrypy.lib import auth_digest
ImportError: cannot import name auth_digest

$ python --version
Python 2.7.13

$ pip show cherrypy
Name: CherryPy
Version: 2.3.0
Summary: Object-Oriented web development framework
Home-page: http://www.cherrypy.org
Author: CherryPy Team
Author-email: team@cherrypy.org
License: BSD
Location: /usr/lib/python2.7/dist-packages
Requires:

**Comment by smicallef** [comment]
That CherryPy version looks pretty old.. I am developing against 5.1.0,

**Comment by theguly** [comment]
kali's package is actually quite old, i was confused by pip not installing a newer package i think.
dpkg --purge python-cherrypy && pip install cherrypy fixes the issue, maybe it breaks other .py but we'll see.

thanks
