### ISSUE TITLE
Proxy issues 

### ISSUE THREAD

**Issue by wirecutter313** [smicallef/spiderfoot#129]
When I've configured the proxy settings I never see spiderfoot hit the proxy or it might bypass it totally.

**Comment by smicallef** [comment]
Which proxy settings specifically? Could you provide some clues as to which traffic you see bypassing it?

**Comment by wirecutter313** [comment]
So for setting I have the following: 
Server type: HTTP
Server IP : Internal IP ( same subnet)
Port : 8080
No username
No Password 

When I tail the proxy log, I never see a connection from the Spiderfoot box. I also went as far to turn on debugging in spiderfoot. I see the app trying to reach out to bing and yahoo, but nothing about the proxy at all.

**Comment by smicallef** [comment]
Is the proxy a SOCKS proxy? What if you try types 4 or 5?
