### ISSUE TITLE
provide a way to install dependencies easily

### ISSUE THREAD

**Issue by mattoufoutu** [smicallef/spiderfoot#130]
While the documentation states "download latest archive, extract, and run `sf.py`", reality is far from that. This leads to having the script complain about missing dependencies, a lot of ones.

One could try to go through the different dependencies mentioned in the error message, but this actually doesn't work, as many of the dependencies listed by the script have a name that is not correct (meaning it's not a valid package name on PyPI, not using APT), so one has to find what is the real module name and install it.

But this still doesn't work, as installing the latest M2Crypto version leads to an error reported more than 3 years ago in #26 

Thus, would it be possible to provide a `requirements.txt` file listing exact requirements and their versions along with a documentation explaining how to handle dependencies that cannot be installed directly with pip or need to be patched (like M2Crypto)? In the current state of things, it's actually a PITA to get spiderfoot running (and, tbh, I gave up before I managed to).

**Comment by smicallef** [comment]
Could you tell me what distro you are using, so I can replicate the issues? Aside from that, you make fair points. I will provide a requirements.txt but also move away from M2Crypto.

**Comment by smicallef** [comment]
requirements.txt file has just been added. The replacement of M2Crypto will take a bit longer, but if you tell me the distro you are using I might be able to solve it another way in the meantime.

**Comment by mattoufoutu** [comment]
Thanks a lot, with the requirements providing all the correct dependencies versions, install is now much easier!! :)
