### ISSUE TITLE
Odd error at tail end of scan

### ISSUE THREAD

**Issue by geekspeed** [smicallef/spiderfoot#133]
Unhandled exception (ValueError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/usr/share/git-projects/spiderfoot/sfscan.py", line 259, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/usr/share/git-projects/spiderfoot/sflib.py", line 1519, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/usr/share/git-projects/spiderfoot/modules/sfp_censys.py", line 163, in handleEvent\n    self.notifyListeners(e)\n', '  File "/usr/share/git-projects/spiderfoot/sflib.py", line 1519, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/usr/share/git-projects/spiderfoot/modules/sfp_alienvault.py", line 188, in handleEvent\n    created_dt = datetime.strptime(created, \'%Y-%m-%dT%H:%M:%S\')\n', '  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime\n    (data_string, format))\n', "ValueError: time data '' does not match format '%Y-%m-%dT%H:%M:%S'\n"]

**Comment by TamanShud** [comment]
Same here: 
Unhandled exception (ValueError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/opt/spiderfoot/sfscan.py", line 259, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/opt/spiderfoot/sflib.py", line 1519, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_bingsearch.py", line 92, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1519, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_spider.py", line 259, in handleEvent\n    return self.spiderFrom(spiderTarget)\n', '  File "/opt/spiderfoot/modules/sfp_spider.py", line 286, in spiderFrom\n    links = self.processUrl(startingPoint)  # fetch first page\n', '  File "/opt/spiderfoot/modules/sfp_spider.py", line 105, in processUrl\n    self.contentNotify(url, fetched, self.urlEvents[url])\n', '  File "/opt/spiderfoot/modules/sfp_spider.py", line 196, in contentNotify\n    self.notifyListeners(event)\n', '  File "/opt/spiderfoot/sflib.py", line 1519, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_dns.py", line 166, in handleEvent\n    self.processHost(match[1], parentEvent, affiliate=False)\n', '  File "/opt/spiderfoot/modules/sfp_dns.py", line 398, in processHost\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1519, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_dns.py", line 227, in handleEvent\n    self.processHost(addr, parentEvent, False)\n', '  File "/opt/spiderfoot/modules/sfp_dns.py", line 398, in processHost\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1519, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_alienvault.py", line 188, in handleEvent\n    created_dt = datetime.strptime(created, \'%Y-%m-%dT%H:%M:%S\')\n', '  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime\n    (data_string, format))\n', "ValueError: time data '' does not match format '%Y-%m-%dT%H:%M:%S'\n"]

**Comment by smicallef** [comment]
Just pushed a fix to github, let me know how you go.
