### ISSUE TITLE
one bug

### ISSUE THREAD

**Issue by huyanshuhan** [smicallef/spiderfoot#135]
Unhandled exception (UnicodeDecodeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "sfscan.pyc", line 259, in startScan\n', '  File "sflib.pyc", line 1519, in notifyListeners\n', '  File "modules\\sfp_bingsearch.pyc", line 92, in handleEvent\n', '  File "sflib.pyc", line 1519, in notifyListeners\n', '  File "modules\\sfp_spider.pyc", line 259, in handleEvent\n', '  File "modules\\sfp_spider.pyc", line 286, in spiderFrom\n', '  File "modules\\sfp_spider.pyc", line 119, in processUrl\n', '  File "sflib.pyc", line 937, in parseLinks\n', "UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 44: ordinal not in range(128)\n"]

**Comment by theinfecteddrake** [comment]
Spiderfoot reads all data as utf-8 encoding, so this needs decoding from the default utf-8 to Unicode. Quite a serious error.
