### ISSUE TITLE
sfp_censys: Update to use API version 2.0

### ISSUE THREAD

**Issue by bcoles** [smicallef/spiderfoot#1351]
https://support.censys.io/hc/en-us/articles/360059306252-Censys-Search-2-0-FAQ-

> We will continue to post new enterprise snapshots in the legacy format until 11/30/2021, at which time we will continue to provide historical downloadable files for the IPv4 and IPv4 Banner datasets, but new files will not be published. Search 1.0 Web UI and API will be available until 11/30/2021 as well, after which they will be deprecated.

**Comment by smicallef** [comment]
Done in PR #1394
