### ISSUE TITLE
Infinite "running" scan

### ISSUE THREAD

**Issue by BillRizer** [smicallef/spiderfoot#1352]
I still have the same problem with the scan that doesn't end.
I cloned the project again today and built it using the docker.
after that I accessed the url and add new scanning with my domain and in "All" mode. after that I monitored the logs (error, debug, info) of the container and noticed that there were no new logs after a while and the scan was still "running" in the interface. after that i restarted spidefoot and when it started again the scan was like "finished".
the last logss:

`2021-09-12 21:54:23,243 [DEBUG] modules.sfp_tldsearch : Keyword extracted from mx.my_domain.com.br: `

`"spiderfoot.plugin : sfp_tldsearch.threadWorker() got event, INTERNET_NAME, from incomingEventQueue."`
(this repeated approximately 40 times)

_What version of Python are you using?_
instaled by docker build

_What version of SpiderFoot are you using (stable release or Git `master` branch)?_
master (today)

_You may also wish to check if your issue has been posted previously:_
in version 3.3 it doesn't happen, I see that it happens since the 3.4 release

**Comment by bcoles** [comment]
This should be fixed now.

**Comment by bcoles** [comment]
The failing modules (`sfp_whois`) has been fixed in #1368.

The underlying architectural issue which allowed a failed module to hang a scan has been resolved in #1379.

**Comment by BillRizer** [comment]
Thanks @bcoles,
resolved in[ #1379.](https://github.com/smicallef/spiderfoot/pull/1379)
