### ISSUE TITLE
Bug - Traceback

### ISSUE THREAD

**Issue by g1ldedm1n1on** [smicallef/spiderfoot#136]
['Traceback (most recent call last):\n', '  File "/opt/spiderfoot-2.9.0/sfscan.py", line 259, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/opt/spiderfoot-2.9.0/sflib.py", line 1519, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot-2.9.0/modules/sfp_bingsearch.py", line 92, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot-2.9.0/sflib.py", line 1519, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot-2.9.0/modules/sfp_dns.py", line 166, in handleEvent\n    self.processHost(match[1], parentEvent, affiliate=False)\n', '  File "/opt/spiderfoot-2.9.0/modules/sfp_dns.py", line 398, in processHost\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot-2.9.0/sflib.py", line 1519, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot-2.9.0/modules/sfp_dns.py", line 227, in handleEvent\n    self.processHost(addr, parentEvent, False)\n', '  File "/opt/spiderfoot-2.9.0/modules/sfp_dns.py", line 398, in processHost\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot-2.9.0/sflib.py", line 1519, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot-2.9.0/modules/sfp_dns.py", line 222, in handleEvent\n    self.processHost(addr, parentEvent, False)\n', '  File "/opt/spiderfoot-2.9.0/modules/sfp_dns.py", line 402, in processHost\n    self.processDomain(dom, evt)\n', '  File "/opt/spiderfoot-2.9.0/modules/sfp_dns.py", line 429, in processDomain\n    self.getRawDns(domainName, domevt, True)\n', '  File "/opt/spiderfoot-2.9.0/modules/sfp_dns.py", line 511, in getRawDns\n    self.processHost(name, parentEvent, affiliate=False)\n', '  File "/opt/spiderfoot-2.9.0/modules/sfp_dns.py", line 398, in processHost\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot-2.9.0/sflib.py", line 1519, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot-2.9.0/modules/sfp_bingsearch.py", line 62, in handleEvent\n    timeout=self.opts[\'_fetchtimeout\']))\n', '  File "/opt/spiderfoot-2.9.0/sflib.py", line 1226, in bingIterate\n    self.refreshTorIdent()\n', '  File "/opt/spiderfoot-2.9.0/sflib.py", line 78, in refreshTorIdent\n    self.fatal("Unable to re-circuit TOR: " + str(e))\n', '  File "/opt/spiderfoot-2.9.0/sflib.py", line 303, in fatal\n    sys.exit(-1)\n', 'SystemExit: -1\n']

**Comment by anniesbbs** [comment]
Unhandled exception (TypeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/home/$USER/spiderfoot-2.11.0/sfscan.py", line 265, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/home/$USER/spiderfoot-2.11.0/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/$USER/spiderfoot-2.11.0/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/$USER/spiderfoot-2.11.0/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/$USER/spiderfoot-2.11.0/modules/sfp_dnsresolve.py", line 150, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/home/$USER/spiderfoot-2.11.0/modules/sfp_dnsresolve.py", line 322, in processHost\n    self.notifyListeners(evt)\n', '  File "/home/$USER/spiderfoot-2.11.0/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/$USER/spiderfoot-2.11.0/modules/sfp_onioncity.py", line 86, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/$USER/spiderfoot-2.11.0/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/$USER/spiderfoot-2.11.0/modules/sfp_dnsresolve.py", line 150, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/home/$USER/spiderfoot-2.11.0/modules/sfp_dnsresolve.py", line 326, in processHost\n    self.processDomain(dom, evt)\n', '  File "/home/$USER/spiderfoot-2.11.0/modules/sfp_dnsresolve.py", line 345, in processDomain\n    self.notifyListeners(domevt)\n', '  File "/home/$USER/spiderfoot-2.11.0/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/$USER/spiderfoot-2.11.0/modules/sfp_dnsbrute.py", line 130, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/$USER/spiderfoot-2.11.0/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/$USER/spiderfoot-2.11.0/modules/sfp_dnsresolve.py", line 215, in handleEvent\n    self.processHost(addr, parentEvent, False)\n', '  File "/home/$USER/spiderfoot-2.11.0/modules/sfp_dnsresolve.py", line 322, in processHost\n    self.notifyListeners(evt)\n', '  File "/home/$USER/spiderfoot-2.11.0/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/$USER/spiderfoot-2.11.0/modules/sfp_ripe.py", line 338, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/$USER/spiderfoot-2.11.0/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/$USER/spiderfoot-2.11.0/modules/sfp_robtex.py", line 118, in handleEvent\n    self.results[str(ipaddr)] = True\n', 'TypeError: list indices must be integers, not str\n']

**Comment by smicallef** [comment]
Fix just pushed to the repo.
