### ISSUE TITLE
Sub-Domains Enumeration?

### ISSUE THREAD

**Issue by bitvijays** [smicallef/spiderfoot#138]
Dear Spiderfoot Authors,

Hope you are doing well. Thank you for creating a awesome product. I would appreciate if you could help with a few little things below?

a) Do we have a IRC Channel or Gitter channel for Spiderfoot. I believe, it would help more community contribution.

b) I was wondering if we can add [DNSDumpster](https://dnsdumpster.com/), The Harvestor, Recon-Ng sub-domain results in current module. Currently, if we enter a DomainName, Spiderfoot is unable to find all the sub-domains which other tools such as harvestor/ datasploit are finding. It would be great if the above can be included. Would be happy to contribute.

c) Frankly, I did tried to understand SpiderFoot Modules etc, to cover up the above. I reffred the documentation of Writing a module. However, couldn't figure out how to include the above. That's why asked for gitter/ IRC/ or more documentation.

Yours Sincerely,

**Comment by smicallef** [comment]
Hi Vijay,

I would rather implement the method / approach used by the tools you mention, rather than including additional libraries/tools. Do you have some information about what specific DNS recon methods you'd like to see included? If it's just a list of hostnames/subdomains to brute-force, you can add this in the sfp_dns module's configuration via the GUI or the CLI.

Thanks

**Comment by smicallef** [comment]
As for a channel for discussion - feel free to join the #spiderfoot room in the Open OSINT Slack group: https://openosint.signup.team/

**Comment by bitvijays** [comment]
Hey @smicallef 

As of now, when i scan for a domain.  I believe only DNS records are searched or brute force is done. Because of which only few of the subdomains are discovered. I believe we need to add few modules to gather more sub-domains such as

a) HackerTarget Forward DNS search API - http://api.hackertarget.com/hostsearch/?q=example.com
b) Google Certificate Transparency Report - https://www.google.com/transparencyreport/https/ct/
c) Netcraft - http://searchdns.netcraft.com/
d) Virustotal Domain Search - https://www.virustotal.com/en/documentation/searching/#getting-domain-information
e) Censys IO -Certificates - When we search for a domain name in Certificates sections of censys. We would get a lot of sub-domains. I believe currently Censys module doesn't watch for DOMAIN_NAME event to look for sub-domains.
f) Threat Crowd Domain request ?

I believe adding all of these would increase spiderfoot ability to discover more subdomains :)

I would be happy to contribute in development of these modules. Yesterday, I created a module sfp_dnsextra which listens for DOMAIN_NAME event and execute HackerTarget HostSearch API and announce INTERNET_NAME event. It worked decently well. However, performance was one of issue faced.

Let me know what are your thoughts. 
bitvijays

**Comment by bcoles** [comment]
Presuming sublist3r API also makes use of the same search engines as the [Sublist3r](https://github.com/aboul3la/Sublist3r) tool, then yeah, this issue is likely solved.

Here's the [supported_engines](https://github.com/aboul3la/Sublist3r/blob/master/sublist3r.py):

```python
    supported_engines = {'baidu': BaiduEnum,
                         'yahoo': YahooEnum,
                         'google': GoogleEnum,
                         'bing': BingEnum,
                         'ask': AskEnum,
                         'netcraft': NetcraftEnum,
                         'dnsdumpster': DNSdumpster,
                         'virustotal': Virustotal,
                         'threatcrowd': ThreatCrowd,
                         'ssl': CrtSearch,
                         'passivedns': PassiveDNS
}
```
