### ISSUE TITLE
Traceback w/ Builtwith

### ISSUE THREAD

**Issue by geekspeed** [smicallef/spiderfoot#141]
Latest GitHub pull: v2.11
Running a scan produces this after 6 items are retrieved.

Unhandled exception (TypeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/opt/spiderfoot/sfscan.py", line 265, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/opt/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 150, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 322, in processHost\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 150, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 326, in processHost\n    self.processDomain(dom, evt)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 345, in processDomain\n    self.notifyListeners(domevt)\n', '  File "/opt/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_builtwith.py", line 97, in handleEvent\n    for nb in data[\'Meta\'][\'Names\']:\n', "TypeError: 'NoneType' object is not iterable\n"]

**Comment by smicallef** [comment]
Fix just committed.
