### ISSUE TITLE
Alpine Dockerfile 

### ISSUE THREAD

**Issue by combro2k** [smicallef/spiderfoot#142]
You might be interesting to use alpine docker container instead of fat ubuntu one ..

https://github.com/combro2k/dockerfiles/tree/master/alpine-spiderfeet

You can check its size at https://store.docker.com/community/images/combro2k/alpine-spiderfeet

**Comment by combro2k** [comment]
Oops has to be called different fixed it now

https://github.com/combro2k/dockerfiles/tree/master/alpine-spiderfoot

https://store.docker.com/community/images/combro2k/alpine-spiderfoot

**Comment by smicallef** [comment]
Done, and thanks for the inspiration!
