### ISSUE TITLE
Missing modules in requirements.txt

### ISSUE THREAD

**Issue by sebastiaopf** [smicallef/spiderfoot#143]
The shipped requirements.txt file fails to include some required modules.
This patch adds the missing modules, but i've not added specific versions for them.

[requirements.patch.txt](https://github.com/smicallef/spiderfoot/files/1225494/requirements.patch.txt)

**Comment by sebastiaopf** [comment]
Also, just to leave this here and possibly help someone with the same problem.
If sf.py keeps complaining that `netaddr` module is not installed even after installing it with pip, in Ubuntu/Mint install it with `apt-get install python-netaddr` and it should work.

**Comment by smicallef** [comment]
Are you sure that's needed? Those modules are shipped with SpiderFoot, in the ext/ folder. How did you install and run it? What error did you get before you added it to requirements.txt?

**Comment by sebastiaopf** [comment]
Hello, thank you for replying.
I've downloaded the linux tarball from http://www.spiderfoot.net/download/
Decompressed it, ran `pip install -r requirements.py` and `./sf.py`
The error i got was from the initial modules check at the very start of sf.py. The 'Critical Start-up Failure' message.
