### ISSUE TITLE
UnicodeDecodeError (Windows)

### ISSUE THREAD

**Issue by SeriyVol4ishe** [smicallef/spiderfoot#145]
Start server in Windows and every scan crashes with this log:
Unhandled exception (UnicodeDecodeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "sfscan.pyc", line 265, in startScan\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 210, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 322, in processHost\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_googlesearch.pyc", line 93, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_spider.pyc", line 261, in handleEvent\n', '  File "modules\\sfp_spider.pyc", line 285, in spiderFrom\n', '  File "modules\\sfp_spider.pyc", line 134, in processUrl\n', '  File "modules\\sfp_spider.pyc", line 191, in linkNotify\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_sslcert.pyc", line 100, in handleEvent\n', "UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 14: ordinal not in range(128)\n"]

**Comment by smicallef** [comment]
Thanks for reporting this - it is fixed in the repo and will be addressed in the next release.
