### ISSUE TITLE
sfp_censys: Add support for IPv6

### ISSUE THREAD

**Issue by bcoles** [smicallef/spiderfoot#1454]

**Comment by bcoles** [comment]
Ignoring this for now.

Every IPv6 address I've tried with the `/api/v2/hosts/:ip` API endpoint returns an effectively empty response:

```
{"ip": "<redacted>", "services": [], "location": {}, "autonomous_system": {"asn": 0}, "operating_system": {}}
```

It seems Censys IPv6 coverage is not great, yet.

**Comment by thehappydinoa** [comment]
Hi @bcoles,

We have recently added ipv6 support in our v2 API. Check out https://search.censys.io/api for more details.
