### ISSUE TITLE
Broken link on website

### ISSUE THREAD

**Issue by Themercee** [smicallef/spiderfoot#148]
On the website, the link to see the schema of the database is broken. 

http://www.spiderfoot.net/documentation/

Nice tool by the way! 👍

**Comment by smicallef** [comment]
Ah yes it's since been removed seeing as sfdb.py now creates it each time. I'll remove the link from the webpage, but meanwhile to inspect the schema you can simply use the SQLite command line.

**Comment by smicallef** [comment]
Link updated.
