### ISSUE TITLE
Bitcoin address error

### ISSUE THREAD

**Issue by thiagocaparelli** [smicallef/spiderfoot#1486]
First, I've tried to insert an bitcoin adress containing 40 characteres but I got this error:
Invalid target type. Could not recognize it as a target SpiderFoot supports.

Second, there are some plugins not availables like Bicoin Finder who does web scrapping for a specific address.
How do I add a module to the tool?

**Comment by bcoles** [comment]
> Second, there are some plugins not availables like Bicoin Finder who does web scrapping for a specific address.

Are you referring to the `sfp_bitcoin` module aka "Bitcoin Finder" ? This module was added to SpiderFoot in 2067561c08bc3d2a04af051b563504a992442bec in 2017. What version of SpiderFoot are you using?
