### ISSUE TITLE
Error execution

### ISSUE THREAD

**Issue by tXambe** [smicallef/spiderfoot#1490]
Please provide a description of the issue and any relevant error messages.

Hello when execute spiderfoot stop the execution with this error:

```
[Error] Unhandled exception (UnicodeEncodeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/usr/share/spiderfoot/sfscan.py", line 180, in startScan\n    mod.setup(self.ts.sf, self.ts.modconfig[modName])\n', '  File "/usr/share/spiderfoot/modules/sfp_accounts.py", line 77, in setup\n    self.sf.cachePut("sfaccounts", data[\'content\'])\n', '  File "/usr/share/spiderfoot/sflib.py", line 437, in cachePut\n    fp.write(data)\n', "UnicodeEncodeError: 'latin-1' codec can't encode characters in position 1991-1994: ordinal not in range(256)\n"]
[*] Scan [422296EA] failed: 'latin-1' codec can't encode characters in position 1991-1994: ordinal not in range(256)
[*] Scan completed with status ERROR-FAILED


```

If you can provide an application stack trace that is even better.

What version of Python are you using?
3.9.7

What version of SpiderFoot are you using (stable release or Git `master` branch)?  
3.0

You may also wish to check if your issue has been posted previously:

* https://github.com/smicallef/spiderfoot/issues

**Comment by bcoles** [comment]
> What version of SpiderFoot are you using (stable release or Git master branch)?
> 3.0

3.0 is very old.

This issue should be fixed in 3,4 and should also be fixed on the `master` branch due to be released as 3.5 soon.

Check the [releases](https://github.com/smicallef/spiderfoot/releases) for the latest releases.
