### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by craigz28** [smicallef/spiderfoot#150]
Received this error on a scan. Attempted twice and received the same error both times.

Unhandled exception (KeyError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/root/spiderfoot/sfscan.py", line 265, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/root/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/root/spiderfoot/modules/sfp_dnsresolve.py", line 210, in handleEvent\n    self.processHost(addr, parentEvent, False)\n', '  File "/root/spiderfoot/modules/sfp_dnsresolve.py", line 322, in processHost\n    self.notifyListeners(evt)\n', '  File "/root/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/root/spiderfoot/modules/sfp_virustotal.py", line 215, in handleEvent\n    self.notifyListeners(e)\n', '  File "/root/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/root/spiderfoot/modules/sfp_dnsresolve.py", line 210, in handleEvent\n    self.processHost(addr, parentEvent, False)\n', '  File "/root/spiderfoot/modules/sfp_dnsresolve.py", line 322, in processHost\n    self.notifyListeners(evt)\n', '  File "/root/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/root/spiderfoot/modules/sfp_ipinfo.py", line 88, in handleEvent\n    self.sf.info("Found GeoIP for " + eventData + ": " + hostip[\'country\'])\n', "KeyError: 'country'\n"]
--

**Comment by smicallef** [comment]
Can you try the latest codebase from the repo? I believe I fixed this.

**Comment by craigz28** [comment]
Giving it a go.

**Comment by craigz28** [comment]
Looks like getting the latest codebase took care of it. Much appreciated.
