### ISSUE TITLE
Scan [xxx] failed: 'SpiderFootEvent' object has no attribute 'actualSource'

### ISSUE THREAD

**Issue by nmbshiva** [smicallef/spiderfoot#151]
Scan failed due to the below error. Immediately before the error occured, the module "modules.sfp_spider" from sfp_bingsearch was called, which initiated a spider of a found URL. All libraries accordingly requirements.txt are installed.

Unhandled exception (AttributeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "spiderfoot/sfscan.py", line 265, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "spiderfoot/sflib.py", line 1525, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "spiderfoot/sflib.py", line 1525, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "spiderfoot/modules/sfp_dnsresolve.py", line 151, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "spiderfoot/modules/sfp_dnsresolve.py", line 323, in processHost\n    self.notifyListeners(evt)\n', '  File "spiderfoot/sflib.py", line 1525, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "spiderfoot/sflib.py", line 1525, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "spiderfoot/modules/sfp_dnsresolve.py", line 151, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "spiderfoot/modules/sfp_dnsresolve.py", line 327, in processHost\n    self.processDomain(dom, evt)\n', '  File "spiderfoot/modules/sfp_dnsresolve.py", line 346, in processDomain\n    self.notifyListeners(domevt)\n', '  File "spiderfoot/sflib.py", line 1525, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "spiderfoot/modules/sfp_dnsbrute.py", line 131, in handleEvent\n    self.notifyListeners(evt)\n', '  File "spiderfoot/sflib.py", line 1525, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "spiderfoot/modules/sfp_dnsresolve.py", line 216, in handleEvent\n    self.processHost(addr, parentEvent, False)\n', '  File "spiderfoot/modules/sfp_dnsresolve.py", line 323, in processHost\n    self.notifyListeners(evt)\n', '  File "spiderfoot/sflib.py", line 1525, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "spiderfoot/modules/sfp_dnsneighbor.py", line 121, in handleEvent\n    ev = self.processHost(sip, parentEvent, affil)\n', '  File "spiderfoot/modules/sfp_dnsneighbor.py", line 243, in processHost\n    self.notifyListeners(evt)\n', '  File "spiderfoot/sflib.py", line 1525, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "spiderfoot/modules/sfp_dnsneighbor.py", line 121, in handleEvent\n    ev = self.processHost(sip, parentEvent, affil)\n', '  File "spiderfoot/modules/sfp_dnsneighbor.py", line 243, in processHost\n    self.notifyListeners(evt)\n', '  File "spiderfoot/sflib.py", line 1525, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "spiderfoot/modules/sfp_dnsneighbor.py", line 121, in handleEvent\n    ev = self.processHost(sip, parentEvent, affil)\n', '  File "spiderfoot/modules/sfp_dnsneighbor.py", line 243, in processHost\n    self.notifyListeners(evt)\n', '  File "spiderfoot/sflib.py", line 1525, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "spiderfoot/modules/sfp_dnsneighbor.py", line 121, in handleEvent\n    ev = self.processHost(sip, parentEvent, affil)\n', '  File "spiderfoot/modules/sfp_dnsneighbor.py", line 243, in processHost\n    self.notifyListeners(evt)\n', '  File "spiderfoot/sflib.py", line 1525, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "spiderfoot/modules/sfp_dnsneighbor.py", line 121, in handleEvent\n    ev = self.processHost(sip, parentEvent, affil)\n', '  File "spiderfoot/modules/sfp_dnsneighbor.py", line 243, in processHost\n    self.notifyListeners(evt)\n', '  File "spiderfoot/sflib.py", line 1525, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "spiderfoot/modules/sfp_dnsresolve.py", line 216, in handleEvent\n    self.processHost(addr, parentEvent, False)\n', '  File "spiderfoot/modules/sfp_dnsresolve.py", line 323, in processHost\n    self.notifyListeners(evt)\n', '  File "spiderfoot/sflib.py", line 1525, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "spiderfoot/modules/sfp_ripe.py", line 334, in handleEvent\n    self.notifyListeners(evt)\n', '  File "spiderfoot/sflib.py", line 1525, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "spiderfoot/modules/sfp_bingsharedip.py", line 133, in handleEvent\n    self.notifyListeners(evt)\n', '  File "spiderfoot/sflib.py", line 1525, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "spiderfoot/modules/sfp_dnsresolve.py", line 151, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "spiderfoot/modules/sfp_dnsresolve.py", line 323, in processHost\n    self.notifyListeners(evt)\n', '  File "spiderfoot/sflib.py", line 1525, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "spiderfoot/sflib.py", line 1525, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "spiderfoot/modules/sfp_spider.py", line 262, in handleEvent\n    return self.spiderFrom(spiderTarget)\n', '  File "spiderfoot/modules/sfp_spider.py", line 286, in spiderFrom\n    links = self.processUrl(startingPoint)  # fetch first page\n', '  File "spiderfoot/modules/sfp_spider.py", line 107, in processUrl\n    self.contentNotify(url, fetched, self.urlEvents[url])\n', '  File "spiderfoot/modules/sfp_spider.py", line 199, in contentNotify\n    self.notifyListeners(event)\n', '  File "spiderfoot/sflib.py", line 1525, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "spiderfoot/modules/sfp_errors.py", line 80, in handleEvent\n    eventSource = event.actualSource\n', "AttributeError: 'SpiderFootEvent' object has no attribute 'actualSource'\n"]

**Comment by smicallef** [comment]
Should be fixed now, merged the wrong change.

**Comment by nmbshiva** [comment]
Sorry for the late reply mate, looks to be working all good now!
