### ISSUE TITLE
start failure : no module named cherrypy

### ISSUE THREAD

**Issue by Darkwinder** [smicallef/spiderfoot#152]
Hi there,

I unfortunately still fail while trying to install spiderfoot on a clean system (VM).
What I did:
* Fresh Install of Ubuntu 17.04 64bit Server
* sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade
* wget spiderfoot-2.11.0-src.tar.gz
* gunzip spiderfoot-2.11.0-src.tar.gz
* tar -xvf spiderfoot-2.11.0-src.tar
* sudo apt-get install python-pip
* pip install lxml netaddr M2Crypto cherrypy mako requests bs4
* Error with M2Crypto : compilation terminated. command 'x86_64-linux-gnu-gcc' failed
* The other modules installed without errors
* I did as suggested: sudo apt-get install python-m2crypto
* cd spiderfoot-2.11.0
* sf.py

It starts with "no module named cherrypy". 

I deleted the vm and tried the same steps again - again the same effect. Still no idea what went wrong...

Dirk

**Comment by shamlikt** [comment]
Hi Darkwinder,
Please install python-dev first (**sudo apt-get install python-dev**) . Also please try ** pip install -r requirements.txt" instead of manual pip package installation. it will read all packages from requirements.txt and install it for you.

**Comment by shamlikt** [comment]
Hi Darkwinder,
You need to install "cherrypy mako requests bs4" these packages again. 
Usually there will be a requirements.txt file. so user can install all the packages using one command
" pip install -r requirements.txt"

**Comment by pentestgirl** [comment]
I have the same problem, but the requirements can't be installed correctly on kali linux: 

M2Crypto/SWIG -c SWIG/_m2crypto_wrap.c -o build/temp.linux-x86_64-3.5/SWIG/_m2crypto_wrap.o -DTHREADING
    SWIG/_m2crypto_wrap.c:151:21: fatal error: Python.h: No such file or directory
     # include <Python.h>
                         ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Can anyone help me?

**Comment by theinfecteddrake** [comment]
Simply run `pip install cherrypy` and that should fix that.

**Comment by black-snow** [comment]
Should be added to the install section of the documentation.

**Comment by renobrdf** [comment]
i had the same issue, had to go single install, after cherrypie i had to do the same install for stem,networkx and others, idk why my requirements.txt install doesnt work.
