### ISSUE TITLE
API Provider

### ISSUE THREAD

**Issue by rider8581** [smicallef/spiderfoot#1523]
Hi there,

Thank you for your contribution.

I have a question while using this project. Does this project have APIs to create the scan or get the scanned result?

I checked the documentation but couldn't find the related parts.

**Comment by bcoles** [comment]
> Are there any references or documentation about the above web URL routes?

The source code is the best documentation.

You could also start a new scan using a web browser and inspect the HTTP request using the browser developer tools.

The HTTP requests and response are simple.

> When do you plan to implement the REST APIs?

Not any time soon. There are many things with higher priorities.
