### ISSUE TITLE
Error encountered during scan

### ISSUE THREAD

**Issue by peteneve** [smicallef/spiderfoot#153]
Unhandled exception (TypeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/sfscan.py", line 265, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/modules/sfp_dnsresolve.py", line 150, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/modules/sfp_dnsresolve.py", line 322, in processHost\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/modules/sfp_dnsresolve.py", line 150, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/modules/sfp_dnsresolve.py", line 326, in processHost\n    self.processDomain(dom, evt)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/modules/sfp_dnsresolve.py", line 345, in processDomain\n    self.notifyListeners(domevt)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/modules/sfp_builtwith.py", line 124, in handleEvent\n    self.notifyListeners(ev)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/modules/sfp_virustotal.py", line 205, in handleEvent\n    self.notifyListeners(e)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/modules/sfp_virustotal.py", line 205, in handleEvent\n    self.notifyListeners(e)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/modules/sfp_dnsresolve.py", line 210, in handleEvent\n    self.processHost(addr, parentEvent, False)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/modules/sfp_dnsresolve.py", line 322, in processHost\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/modules/sfp_virustotal.py", line 205, in handleEvent\n    self.notifyListeners(e)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/modules/sfp_dnsresolve.py", line 215, in handleEvent\n    self.processHost(addr, parentEvent, False)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/modules/sfp_dnsresolve.py", line 322, in processHost\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/spiderfoot-2.11.0/modules/sfp_hosting.py", line 91, in handleEvent\n    evt = SpiderFootEvent("PROVIDER_HOSTING", ret[0] + ": " + ret[1],\n', "TypeError: 'NoneType' object has no attribute '__getitem__'\n"]

**Comment by ajohnson8503** [comment]
I have gotten the same error last night.

Unhandled exception (TypeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "sfscan.pyc", line 265, in startScan\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_robtex.pyc", line 118, in handleEvent\n', 'TypeError: list indices must be integers, not str\n']

**Comment by smicallef** [comment]
Fixes just pushed.

**Comment by peteneve** [comment]
Thanks for the super fast response! I'm getting the following error with the latest pull:

Unhandled exception (KeyError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/opt/spiderfoot/sfscan.py", line 265, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/opt/spiderfoot/sflib.py", line 1525, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1525, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 151, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 323, in processHost\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1525, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1525, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 151, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 327, in processHost\n    self.processDomain(dom, evt)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 346, in processDomain\n    self.notifyListeners(domevt)\n', '  File "/opt/spiderfoot/sflib.py", line 1525, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_accounts.py", line 199, in handleEvent\n    res = self.batchSites(kw)\n', '  File "/opt/spiderfoot/modules/sfp_accounts.py", line 163, in batchSites\n    for site in self.sites[\'sites\']:\n', "KeyError: 'sites'\n"]

Is this a related error or should I raise another issue?

**Comment by smicallef** [comment]
This is a different issue - probably the JSON file containing all the sites on Github was temporarily unreachable. I've updated the module to be less error-prone, try now..

**Comment by peteneve** [comment]
Runs through without errors now. Thanks.
