### ISSUE TITLE
Bug when scanning

### ISSUE THREAD

**Issue by 116597** [smicallef/spiderfoot#154]
Unhandled exception (TypeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "sfscan.pyc", line 255, in startScan\n', '  File "sflib.pyc", line 1399, in notifyListeners\n', '  File "modules\\sfp_dns.pyc", line 220, in handleEvent\n', '  File "modules\\sfp_dns.pyc", line 387, in processHost\n', '  File "sflib.pyc", line 1399, in notifyListeners\n', '  File "modules\\sfp_vuln.pyc", line 160, in handleEvent\n', "TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'\n"]

**Comment by smicallef** [comment]
Have you tried the latest version? This should be resolved in 2.11.
