### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by szeghybarna** [smicallef/spiderfoot#156]
Unhandled exception (TypeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/home/spiderfoot/spiderfoot/sfscan.py", line 265, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/home/spiderfoot/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/spiderfoot/modules/sfp_dnsresolve.py", line 150, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/home/spiderfoot/spiderfoot/modules/sfp_dnsresolve.py", line 326, in processHost\n    self.processDomain(dom, evt)\n', '  File "/home/spiderfoot/spiderfoot/modules/sfp_dnsresolve.py", line 345, in processDomain\n    self.notifyListeners(domevt)\n', '  File "/home/spiderfoot/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/spiderfoot/modules/sfp_dnsbrute.py", line 130, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/spiderfoot/modules/sfp_dnsresolve.py", line 215, in handleEvent\n    self.processHost(addr, parentEvent, False)\n', '  File "/home/spiderfoot/spiderfoot/modules/sfp_dnsresolve.py", line 322, in processHost\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/spiderfoot/modules/sfp_ripe.py", line 338, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/spiderfoot/modules/sfp_robtex.py", line 118, in handleEvent\n    self.results[str(ipaddr)] = True\n', 'TypeError: list indices must be integers, not str\n']

**Comment by smicallef** [comment]
Have you tried to pull the latest version from the repo? This should already be fixed.

**Comment by szeghybarna** [comment]
Well, I downloaded spiderfoot from the webpage the latest version. I feel myself a bit stupid, when I found the repo on github, I not tried to update and start again the scan. It seems already solved. Thanks.
