### ISSUE TITLE
NameError: global name 'sha256' is not defined

### ISSUE THREAD

**Issue by StephenDart** [smicallef/spiderfoot#157]
Fresh install on current commit.

Unhandled exception (NameError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/opt/spiderfoot/sfscan.py", line 260, in startScan\n    psMod.notifyListeners(rootEvent)\n', '  File "/opt/spiderfoot/sflib.py", line 1526, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 121, in handleEvent\n    eventDataHash = self.sf.hashstring(eventData)\n', '  File "/opt/spiderfoot/sflib.py", line 376, in hashstring\n    return sha256(s).hexdigest()\n', "NameError: global name 'sha256' is not defined\n"]

**Comment by smicallef** [comment]
Should be fixed now, please pull from the repo.

**Comment by StephenDart** [comment]
Working now, thanks for the quick commit fix.
