### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Frenzyvn** [smicallef/spiderfoot#158]
Please check 
url = url.encode('ascii', 'ignore')

Error: 
"Applications/SpiderFoot/sflib.py", line 979, in fetchUrl\n    url = url.encode(\'ascii\', \'ignore\')\n', "UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 48: ordinal not in range(128)\n".

Thanks

**Comment by smicallef** [comment]
Could you please e-mail me the target you scanned and modules you enabled at support@spiderfoot.net, so I can try and re-produce this?

**Comment by Frenzyvn** [comment]
I deleted the scan, so cannot remember which module is enabled. BTW, I use
Footprint option with target: vietnamthoibao.org

Thanks

**Comment by smicallef** [comment]
OK, I'm looking into it. What version are you using?

**Comment by Frenzyvn** [comment]
The lastest version. I added try execption so it can bypass this bug.
Everything works fine until now. But the scan is so long. It took me nearly
2 days, but still not completed. Any idea?
