### ISSUE TITLE
Scan failed: list indices must be integers, not str

### ISSUE THREAD

**Issue by michaelhovedk** [smicallef/spiderfoot#159]
Crash in SpiderFoot 2.11 on WIN32 - ping me for logs, settings and scan target.

Unhandled exception (TypeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "sfscan.pyc", line 265, in startScan\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_bingsearch.pyc", line 93, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 150, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 322, in processHost\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_bingsearch.pyc", line 93, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 150, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 326, in processHost\n', '  File "modules\\sfp_dnsresolve.pyc", line 345, in processDomain\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_dnsbrute.pyc", line 130, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_spider.pyc", line 261, in handleEvent\n', '  File "modules\\sfp_spider.pyc", line 285, in spiderFrom\n', '  File "modules\\sfp_spider.pyc", line 106, in processUrl\n', '  File "modules\\sfp_spider.pyc", line 198, in contentNotify\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 150, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 322, in processHost\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_spider.pyc", line 261, in handleEvent\n', '  File "modules\\sfp_spider.pyc", line 285, in spiderFrom\n', '  File "modules\\sfp_spider.pyc", line 134, in processUrl\n', '  File "modules\\sfp_spider.pyc", line 191, in linkNotify\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_crossref.pyc", line 131, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 150, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 322, in processHost\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_spider.pyc", line 261, in handleEvent\n', '  File "modules\\sfp_spider.pyc", line 311, in spiderFrom\n', '  File "modules\\sfp_spider.pyc", line 106, in processUrl\n', '  File "modules\\sfp_spider.pyc", line 198, in contentNotify\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 150, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 322, in processHost\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_spider.pyc", line 261, in handleEvent\n', '  File "modules\\sfp_spider.pyc", line 311, in spiderFrom\n', '  File "modules\\sfp_spider.pyc", line 134, in processUrl\n', '  File "modules\\sfp_spider.pyc", line 191, in linkNotify\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_crossref.pyc", line 131, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 150, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 322, in processHost\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_bingsearch.pyc", line 93, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_spider.pyc", line 261, in handleEvent\n', '  File "modules\\sfp_spider.pyc", line 285, in spiderFrom\n', '  File "modules\\sfp_spider.pyc", line 106, in processUrl\n', '  File "modules\\sfp_spider.pyc", line 198, in contentNotify\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 150, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 322, in processHost\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_bingsearch.pyc", line 93, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_spider.pyc", line 261, in handleEvent\n', '  File "modules\\sfp_spider.pyc", line 311, in spiderFrom\n', '  File "modules\\sfp_spider.pyc", line 134, in processUrl\n', '  File "modules\\sfp_spider.pyc", line 191, in linkNotify\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_crossref.pyc", line 131, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 150, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 322, in processHost\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_virustotal.pyc", line 205, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_spider.pyc", line 261, in handleEvent\n', '  File "modules\\sfp_spider.pyc", line 311, in spiderFrom\n', '  File "modules\\sfp_spider.pyc", line 106, in processUrl\n', '  File "modules\\sfp_spider.pyc", line 198, in contentNotify\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 150, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 322, in processHost\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_virustotal.pyc", line 205, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_virustotal.pyc", line 205, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_virustotal.pyc", line 205, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_virustotal.pyc", line 205, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_bingsearch.pyc", line 93, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_spider.pyc", line 261, in handleEvent\n', '  File "modules\\sfp_spider.pyc", line 285, in spiderFrom\n', '  File "modules\\sfp_spider.pyc", line 134, in processUrl\n', '  File "modules\\sfp_spider.pyc", line 191, in linkNotify\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_crossref.pyc", line 131, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 150, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 322, in processHost\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_virustotal.pyc", line 205, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_virustotal.pyc", line 205, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_bingsearch.pyc", line 93, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_spider.pyc", line 261, in handleEvent\n', '  File "modules\\sfp_spider.pyc", line 285, in spiderFrom\n', '  File "modules\\sfp_spider.pyc", line 106, in processUrl\n', '  File "modules\\sfp_spider.pyc", line 198, in contentNotify\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 150, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 322, in processHost\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_virustotal.pyc", line 205, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 210, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 322, in processHost\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_spider.pyc", line 261, in handleEvent\n', '  File "modules\\sfp_spider.pyc", line 285, in spiderFrom\n', '  File "modules\\sfp_spider.pyc", line 134, in processUrl\n', '  File "modules\\sfp_spider.pyc", line 191, in linkNotify\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_crossref.pyc", line 131, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 150, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 322, in processHost\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_intfiles.pyc", line 136, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 150, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 322, in processHost\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_bingsearch.pyc", line 93, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_spider.pyc", line 261, in handleEvent\n', '  File "modules\\sfp_spider.pyc", line 311, in spiderFrom\n', '  File "modules\\sfp_spider.pyc", line 134, in processUrl\n', '  File "modules\\sfp_spider.pyc", line 191, in linkNotify\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_crossref.pyc", line 131, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 150, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 322, in processHost\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_bingsearch.pyc", line 93, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_spider.pyc", line 261, in handleEvent\n', '  File "modules\\sfp_spider.pyc", line 285, in spiderFrom\n', '  File "modules\\sfp_spider.pyc", line 134, in processUrl\n', '  File "modules\\sfp_spider.pyc", line 191, in linkNotify\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_crossref.pyc", line 131, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 150, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 322, in processHost\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_bingsearch.pyc", line 93, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_spider.pyc", line 261, in handleEvent\n', '  File "modules\\sfp_spider.pyc", line 285, in spiderFrom\n', '  File "modules\\sfp_spider.pyc", line 106, in processUrl\n', '  File "modules\\sfp_spider.pyc", line 198, in contentNotify\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 150, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 322, in processHost\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_virustotal.pyc", line 205, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 215, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 322, in processHost\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_robtex.pyc", line 146, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 150, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 322, in processHost\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_virustotal.pyc", line 205, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 210, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 322, in processHost\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_virustotal.pyc", line 205, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 215, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 322, in processHost\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_censys.pyc", line 164, in handleEvent\n', '  File "sflib.pyc", line 1523, in notifyListeners\n', '  File "modules\\sfp_robtex.pyc", line 118, in handleEvent\n', 'TypeError: list indices must be integers, not str\n']

**Comment by smicallef** [comment]
This has been fixed in the repo and will be included with 2.12.
