### ISSUE TITLE
Adding module containing snallygaster

### ISSUE THREAD

**Issue by security-companion** [smicallef/spiderfoot#1598]
Hi,
I thought about adding a module that contains tests done by [snallygaster](https://github.com/hannob/snallygaster) but before doing so I wanted to ask first if this is something that you would like to integrate in spiderfoot if I make a pull request with the new module.
Thanks in advance
Security-Companion

**Comment by smicallef** [comment]
Hi, thanks for the offer, but this is something already in the works and expected to ship in the next week. If you'd like to see other tools integrated though, feel free to raise an issue suggesting them.
