### ISSUE TITLE
Run Spiderfoot using UWSGI

### ISSUE THREAD

**Issue by Retro64XYZ** [smicallef/spiderfoot#1605]
Please provide a description of the issue and any relevant error messages.
No errors.

Is it possible to use uwsgi to run spiderfoot? If so, what would the command be? I am trying to run spiderfoot from behind an nginx proxy and it would be nice to simplify the whole process.

Thank you.

**Comment by bcoles** [comment]
The SpiderFoot web interface uses CherryPy.

You can run the web interface with `-l`; ie `./sfp.py -l 127.0.0.1:5001`.

You may also want to change the `root` in `sf.py`.

https://github.com/smicallef/spiderfoot/blob/70caf3f7617d88634e6e9e304d30eeca64b831d8/sf.py#L42-L48

This will allow cleaner route mapping if the frontend reverse proxy is not hosting SpiderFoot at `/`.
