### ISSUE TITLE
Disappearing navigation bar on devices with small screen width

### ISSUE THREAD

**Issue by Rb64** [smicallef/spiderfoot#1607]
The navigation bar disappears when the screen width gets too small. This may be a problem when using mobile devices. A clickable menu icon appears instead of the navigation bar but clicking it does nothing. I have replicated this bug on Chrome, Firefox and Edge as well as on the Mobile version of Chrome and Firefox.  
![grafik](https://user-images.githubusercontent.com/91498309/143776974-c9a58192-2da9-43ea-b37b-212e66901eaf.png)

**Comment by Rb64** [comment]
I fixed this and submitted a [pull request](https://github.com/smicallef/spiderfoot/pull/1611).

**Comment by smicallef** [comment]
Thanks!
