### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by llarocca** [smicallef/spiderfoot#162]
Using Version 2.11

Unhandled exception (UnicodeDecodeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/home/thor/Desktop/spiderfoot-2.11.0/sfscan.py", line 265, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/home/thor/Desktop/spiderfoot-2.11.0/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/thor/Desktop/spiderfoot-2.11.0/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/thor/Desktop/spiderfoot-2.11.0/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/thor/Desktop/spiderfoot-2.11.0/modules/sfp_dnsresolve.py", line 150, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/home/thor/Desktop/spiderfoot-2.11.0/modules/sfp_dnsresolve.py", line 322, in processHost\n    self.notifyListeners(evt)\n', '  File "/home/thor/Desktop/spiderfoot-2.11.0/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/thor/Desktop/spiderfoot-2.11.0/modules/sfp_googlesearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/thor/Desktop/spiderfoot-2.11.0/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/thor/Desktop/spiderfoot-2.11.0/modules/sfp_spider.py", line 261, in handleEvent\n    return self.spiderFrom(spiderTarget)\n', '  File "/home/thor/Desktop/spiderfoot-2.11.0/modules/sfp_spider.py", line 311, in spiderFrom\n    freshLinks = self.processUrl(link)\n', '  File "/home/thor/Desktop/spiderfoot-2.11.0/modules/sfp_spider.py", line 134, in processUrl\n    self.urlEvents[link] = self.linkNotify(link, self.urlEvents[url])\n', '  File "/home/thor/Desktop/spiderfoot-2.11.0/modules/sfp_spider.py", line 191, in linkNotify\n    self.notifyListeners(event)\n', '  File "/home/thor/Desktop/spiderfoot-2.11.0/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/thor/Desktop/spiderfoot-2.11.0/modules/sfp_filemeta.py", line 142, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/thor/Desktop/spiderfoot-2.11.0/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/thor/Desktop/spiderfoot-2.11.0/modules/sfp_dnsresolve.py", line 120, in handleEvent\n    eventDataHash = self.sf.hashstring(eventData)\n', '  File "/home/thor/Desktop/spiderfoot-2.11.0/sflib.py", line 374, in hashstring\n    s = string.encode(\'raw_unicode_escape\')\n', "UnicodeDecodeError: 'ascii' codec can't decode byte 0xa5 in position 1489: ordinal not in range(128)\n"]

**Comment by smicallef** [comment]
This should be fixed in the github version. Would you mind pulling from the repo and trying again?

**Comment by llarocca** [comment]
Sure, thanks.
