### ISSUE TITLE
double free or corruption (out)

### ISSUE THREAD

**Issue by citrixrep** [smicallef/spiderfoot#1620]
when type command on sfcli get this error:

double free or corruption (out)
zsh: IOT instruction  python3 sfcli.py

Python 3.9.2

**Comment by smicallef** [comment]
Could you provide the exact command like  you're using? Also I assume you're using the master branch?

**Comment by citrixrep** [comment]
yes i use master branch

![image](https://user-images.githubusercontent.com/27157014/149946978-a5bad769-5353-4529-bc6e-1587026eba61.png)

**Comment by smicallef** [comment]
I can't reproduce this using Python 3.9 and SpiderFoot from the master branch, also using zsh. Could you try on a different machine or with a different shell? Since it looks like zsh is reporting the error, maybe something is wrong with zsh on that machine?

**Comment by citrixrep** [comment]
i try with other shell in bash but same error.

![image](https://user-images.githubusercontent.com/27157014/151791555-acc847d7-1932-4263-ab74-f5a0750338d0.png)

**Comment by citrixrep** [comment]
reinstall OS and fix, thanks
