### ISSUE TITLE
Unable to 'set' module options to 'True' using CLI

### ISSUE THREAD

**Issue by quantumburnz** [smicallef/spiderfoot#1622]
Please provide a description of the issue and any relevant error messages: I'm unable to 'set' module options to 'True' using CLI. The output shows the value was set but if you check, it remains 'False'. However, you can set values to 'False' without a problem. See the example below.

sf> set module.sfp_dnsresolve.netblocklookup 
module.sfp_dnsresolve.netblocklookup = False
sf> set module.sfp_dnsresolve.netblocklookup = True
[*] module.sfp_dnsresolve.netblocklookup set to True
sf> set module.sfp_dnsresolve.netblocklookup
module.sfp_dnsresolve.netblocklookup = False
sf> # changed via GUI
sf> set module.sfp_dnsresolve.netblocklookup
module.sfp_dnsresolve.netblocklookup = True
sf> set module.sfp_dnsresolve.netblocklookup = False
[*] module.sfp_dnsresolve.netblocklookup set to False
sf> set module.sfp_dnsresolve.netblocklookup
module.sfp_dnsresolve.netblocklookup = False
sf> set module.sfp_dnsresolve.netblocklookup = True
[*] module.sfp_dnsresolve.netblocklookup set to True
sf> set module.sfp_dnsresolve.netblocklookup
module.sfp_dnsresolve.netblocklookup = False
sf> # Can't enable via CLI...

What version of Python are you using? Python 3.8.10

What version of SpiderFoot are you using (stable release or Git `master` branch)? SpiderFoot stable v3.5.0

You may also wish to check if your issue has been posted previously: I did not see any similarly reported issues.

**Comment by smicallef** [comment]
Good spotting. Looks like it's only possible using `1` and `0` but not `True` and `False`.  Will work on getting a fix out shortly.

**Comment by smicallef** [comment]
Should now be fixed on master:
```
sf> set module.sfp_dnsresolve.netblocklookup
module.sfp_dnsresolve.netblocklookup = True
sf> set module.sfp_dnsresolve.netblocklookup = 0
[*] module.sfp_dnsresolve.netblocklookup set to 0
sf> set module.sfp_dnsresolve.netblocklookup
module.sfp_dnsresolve.netblocklookup = False
sf> set module.sfp_dnsresolve.netblocklookup = True
[*] module.sfp_dnsresolve.netblocklookup set to True
sf> set module.sfp_dnsresolve.netblocklookup
module.sfp_dnsresolve.netblocklookup = True
sf> set module.sfp_dnsresolve.netblocklookup = false
[*] module.sfp_dnsresolve.netblocklookup set to false
sf> set module.sfp_dnsresolve.netblocklookup
module.sfp_dnsresolve.netblocklookup = False
sf> set module.sfp_dnsresolve.netblocklookup = 1
[*] module.sfp_dnsresolve.netblocklookup set to 1
sf> set module.sfp_dnsresolve.netblocklookup
module.sfp_dnsresolve.netblocklookup = True
```
