### ISSUE TITLE
hackertarget API queries by IP instead of range & SF continues to query after "API count exceeded"

### ISSUE THREAD

**Issue by quantumburnz** [smicallef/spiderfoot#1623]
Please provide a description of the issue and any relevant error messages:
- According to https://hackertarget.com/reverse-dns-lookup/, the query can accept an IP or range of IPs (or perhaps even a domain name). It would be more efficient to query a range, if possible.
- SpiderFoot continues to query the API even if an "API count exceeded" response is returned. Per https://hackertarget.com/ip-tools/, "If you exceed the rate limit you will receive a HTTP 429 response code from the API server." Therefore, SF should stop further queries if this is encountered.

What version of Python are you using? Python 3.8.10

What version of SpiderFoot are you using (stable release or Git `master` branch)? SpiderFoot stable v3.5.0

You may also wish to check if your issue has been posted previously: I did not see any similarly reported issues.

**Comment by bcoles** [comment]
There are two different issues here.

> It would be more efficient to query a range, if possible.

Unfortunately this is a systemic architectural issue. A known issue but undocumented until now. I've created #1625 to track this issue.

> SpiderFoot continues to query the API even if an "API count exceeded" response is returned. Per https://hackertarget.com/ip-tools/, "If you exceed the rate limit you will receive a HTTP 429 response code from the API server." Therefore, SF should stop further queries if this is encountered.

Thanks. I've submitted an untested patch PR #1626 to resolve this issue.
