### ISSUE TITLE
Implicit string concatenation possibly in error

### ISSUE THREAD

**Issue by code-review-doctor** [smicallef/spiderfoot#1629]
Implicit string concatenation on line 213, possibly in error?

https://github.com/smicallef/spiderfoot/blob/5b6e10fd7c1bad22c26772123101d495af9f81b0/spiderfoot/db.py#L212-L214

python is implicitly concatenation `'Search Engine''s Web Content'` to form `'Search Engines Web Content'`, but that does not looks right. Was that the intention of the code?

**Comment by bcoles** [comment]
Presumably this should be `"Search Engine's Web Content"`.

**Comment by code-review-doctor** [comment]
That was my assumption too. Glad yo get confirmation :) I will make a PR

**Comment by bcoles** [comment]
Personally I prefer `"Search Engine Web Content"`.
