### ISSUE TITLE
Google Search 503 CLI

### ISSUE THREAD

**Issue by JonahAndFish** [smicallef/spiderfoot#163]
I tried google search using spider foot CLI tool. And it threw me 503 error code. It seemed spiderfoot is sending too many requests to google. The same issue wasn't encountered when using GUI. Any fix on that?

**Comment by smicallef** [comment]
It's not really avoidable and nothing to do with CLI or GUI, as it's the same code that's running the searches in the end. Basically this is Google blocking scraping attempts.

**Comment by jiangang123** [comment]
Alright. thanks

**Comment by JonahAndFish** [comment]
Thanks. Appreciate the reply.

**Comment by JonahAndFish** [comment]
Is it possible for me to edit the code and avoid Google detection of web scrapping?
