### ISSUE TITLE
REQ: Email notification on scan completion.

### ISSUE THREAD

**Issue by Gyarbij** [smicallef/spiderfoot#1637]
For long running scans, an email notification on completion of scan.

N/A

3.10

Stable 3.5

Not Reported.

**Comment by Tuvines** [comment]
sᴜᴇᴛᴏᴠʏɪ     17

**Comment by smicallef** [comment]
This is a feature in SpiderFoot HX that is not planned for the open source version. You can create a custom script around the CLI to do so, if you need this kind of functionality.
