### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by eigenstein** [smicallef/spiderfoot#164]
Taken from log when running 'footprint' or 'passive:'
Unhandled exception (ValueError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/opt/spiderfoot/sfscan.py", line 116, in startScan\n    socksPort = int(self.ts.config[\'_socks3port\'])\n', "ValueError: invalid literal for int() with base 10: ''\n"]

**Comment by eigenstein** [comment]
Error disappears when I remove TOR from the SOCKS settings

**Comment by smicallef** [comment]
This would happen if you specify a SOCKS or TOR proxy, but do not specify a port. Can you check your configuration?
