### ISSUE TITLE
Module sfp wigle check credentials validity

### ISSUE THREAD

**Issue by rksh** [smicallef/spiderfoot#1641]
For whatever reason, the client has recently been delivering a lot of unparsable auth credentials on WiGLE API calls
Since the module uses pre-encoded tokens, this seems likely to be user error - possibly copy/pasting the wrong value, or including too many or two few characters in the paste. A simple check could provide a more-specific warning users by detecting the error before attempting a request - a failure to decode or subsequent mismatch on b64 re-encode could catch invalid credentials input:

```
if base64.b64encode(base64.b64decode(self.opts['api_key_encoded'])) ==  self.opts['api_key_encoded']:
    <go ahead>
else:
   <warn of credentials error>
```
It is also possible (but unlikely) that default b64 behavior is being overridden (with options such as ignoring padding or adding newlines), but that's beyond our ability to detect (we're careful not to log sensitive payloads)

Issue detected in various python versions. Unfortunately, the User-Agent header doesn't tell us the Spiderfoot version(s) affected.

**Comment by bcoles** [comment]
Thanks @rksh.

Someone on discord was struggling with the concept of an "encoded API key" the other day. I suspect users are confused about which API key to use.

PR #1642 (pending merge) updates the module to validate the API key is valid bas64 and updates the module documentation to clearly indicate which API key should be used.

**Comment by smicallef** [comment]
Fix has been merged. Thanks @bcoles!
