### ISSUE TITLE
File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode\n raise ValueError("No JSON object could be decoded"

### ISSUE THREAD

**Issue by HachimanSec** [smicallef/spiderfoot#166]
Hi,

I just got the latest version via GitHub and tried to execute a scan which ended up in the error message listed below. 

Do you have any idea what this might be? 
I run the latest version of Kali Linux 

`Linux kali 4.14.0-kali3-amd64 #1 SMP Debian 4.14.13-1kali1 (2018-01-25) x86_64 GNU/Linux
`
`Unhandled exception (ValueError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/opt/spiderfoot/sfscan.py", line 265, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 162, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 334, in processHost\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 162, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 338, in processHost\n    self.processDomain(dom, evt)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 357, in processDomain\n    self.notifyListeners(domevt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_builtwith.py", line 113, in handleEvent\n    self.notifyListeners(e)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_accounts.py", line 234, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_github.py", line 138, in handleEvent\n    ret = json.loads(res[\'content\'])\n', '  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads\n    return _default_decoder.decode(s)\n', '  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n', '  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode\n    raise ValueError("No JSON object could be decoded")\n', 'ValueError: No JSON object could be decoded\n']`

**Comment by TomHubGit** [comment]
Additional info: the target was a domainname
