### ISSUE TITLE
Bug while scanning

### ISSUE THREAD

**Issue by tnektnek** [smicallef/spiderfoot#167]
Unhandled exception (TypeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/home/spiderfoot/sfscan.py", line 265, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/home/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_censys.py", line 164, in handleEvent\n    self.notifyListeners(e)\n', '  File "/home/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_robtex.py", line 118, in handleEvent\n    self.results[str(ipaddr)] = True\n', 'TypeError: list indices must be integers, not str\n']

This occurred yesterday while scanning an IP. I had installed spiderfoot straight from the current repo as well.

**Comment by smicallef** [comment]
This is already fixed on the master branch - could you do a git pull and try again?
