### ISSUE TITLE
Feature request: module marketplace

### ISSUE THREAD

**Issue by dhombios** [smicallef/spiderfoot#1681]
It would be a nice feature to have an addon marketplace, as it will simplify publishing your custom made modules by making them easier to be located. Additionally, as SpiderfootHX allows integrating custom modules, it would also be benefited from this feature.

As an example, other osint frameworks have implemented it by uploading those addons to a separate github repo in order to avoid having a dedicated server for that  (for example that seems to  be what [sn0int](https://github.com/kpcyrd/sn0int) does)

**Comment by smicallef** [comment]
It's an interesting idea, but for the foreseeable future I'd like things to remain as-is, i.e. contributors submit to this repo, they get reviewed and (hopefully) eventually merged to be a part of the main package.
