### ISSUE TITLE
Problem as lack of disk space

### ISSUE THREAD

**Issue by 1Suprem3** [smicallef/spiderfoot#1685]
Hello. I have encountered such a problem as lack of disk space when scanning different projects for a long time. (If this problem has been solved before, let me know)
So far, I have found the only solution - to delete the file in .../.spiderfoot/spiderfoot.db-wal, which weighs the most + clean the logs folder. But this sometimes causes errors, and I have to completely delete the .spider foot folder and re-configure the project. Is there a simpler solution to this problem?
Thank you in advance!

**Comment by bcoles** [comment]
> Is there a simpler solution to this problem?

Free up some disk space.

> delete the file in .../.spiderfoot/spiderfoot.db-wal
> But this sometimes causes errors,

This is the [write ahead log](https://sqlite.org/wal.html). Do not delete this file while running scans.
