### ISSUE TITLE
Scan stopped "ERROR"

### ISSUE THREAD

**Issue by mschiessl** [smicallef/spiderfoot#169]
We're on a debian stretch - latest.
Most API KEYS have been populated.

`Unhandled exception (KeyError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/opt/spiderfoot/sfscan.py", line 265, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 162, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 334, in processHost\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 162, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 338, in processHost\n    self.processDomain(dom, evt)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 357, in processDomain\n    self.notifyListeners(domevt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_builtwith.py", line 127, in handleEvent\n    self.notifyListeners(ev)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_spider.py", line 262, in handleEvent\n    return self.spiderFrom(spiderTarget)\n', '  File "/opt/spiderfoot/modules/sfp_spider.py", line 312, in spiderFrom\n    freshLinks = self.processUrl(link)\n', '  File "/opt/spiderfoot/modules/sfp_spider.py", line 135, in processUrl\n    self.urlEvents[link] = self.linkNotify(link, self.urlEvents[url])\n', '  File "/opt/spiderfoot/modules/sfp_spider.py", line 192, in linkNotify\n    self.notifyListeners(event)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_crossref.py", line 135, in handleEvent\n    self.notifyListeners(evt2)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_email.py", line 98, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_names.py", line 86, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_socialprofiles.py", line 167, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_email.py", line 98, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_fullcontact.py", line 151, in handleEvent\n    e = SpiderFootEvent("HUMAN_NAME", data[\'fullName\'], self.__name__, event)\n', "KeyError: 'fullName'\n"]`

**Comment by mschiessl** [comment]
Reviewing the logfile the "fullcontact" API returned an "invalid API Token" error.
I just genereated a new key and restarted the scan  - will report back

**Comment by mschiessl** [comment]
Ok - even the newly created key returns "error":

`
SpiderFoot | ERROR | API key rejected by fullcontact.com
-- | -- | --
`

**Comment by smicallef** [comment]
Are you sure you haven't hit some kind of limit with your account? I've tried it with my key and it works.

**Comment by mschiessl** [comment]
well it was a completely new key in a new account  :/

**Comment by smicallef** [comment]
Could you re-try with the latest master? Seems to be a bug which I've now fixed.

**Comment by mschiessl** [comment]
Looks better now, bot it had a stop error once again.

I do not think it is related to the original issue but i will drop it here for your information:
`Unhandled exception (AttributeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/opt/spiderfoot/sfscan.py", line 265, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 162, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 334, in processHost\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 162, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 338, in processHost\n    self.processDomain(dom, evt)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 357, in processDomain\n    self.notifyListeners(domevt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_builtwith.py", line 127, in handleEvent\n    self.notifyListeners(ev)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_spider.py", line 262, in handleEvent\n    return self.spiderFrom(spiderTarget)\n', '  File "/opt/spiderfoot/modules/sfp_spider.py", line 286, in spiderFrom\n    links = self.processUrl(startingPoint)  # fetch first page\n', '  File "/opt/spiderfoot/modules/sfp_spider.py", line 135, in processUrl\n    self.urlEvents[link] = self.linkNotify(link, self.urlEvents[url])\n', '  File "/opt/spiderfoot/modules/sfp_spider.py", line 192, in linkNotify\n    self.notifyListeners(event)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_crossref.py", line 135, in handleEvent\n    self.notifyListeners(evt2)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 162, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 334, in processHost\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_spider.py", line 262, in handleEvent\n    return self.spiderFrom(spiderTarget)\n', '  File "/opt/spiderfoot/modules/sfp_spider.py", line 286, in spiderFrom\n    links = self.processUrl(startingPoint)  # fetch first page\n', '  File "/opt/spiderfoot/modules/sfp_spider.py", line 107, in processUrl\n    self.contentNotify(url, fetched, self.urlEvents[url])\n', '  File "/opt/spiderfoot/modules/sfp_spider.py", line 203, in contentNotify\n    self.notifyListeners(event)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 162, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 334, in processHost\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_sslcert.py", line 108, in handleEvent\n    self.notifyListeners(rawevt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 162, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 334, in processHost\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_tldsearch.py", line 165, in handleEvent\n    self.tryTldWrapper(targetList, event)\n', '  File "/opt/spiderfoot/modules/sfp_tldsearch.py", line 100, in tryTldWrapper\n    self.sendEvent(sourceEvent, res)\n', '  File "/opt/spiderfoot/modules/sfp_tldsearch.py", line 116, in sendEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_crossref.py", line 135, in handleEvent\n    self.notifyListeners(evt2)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 162, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 334, in processHost\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_spider.py", line 262, in handleEvent\n    return self.spiderFrom(spiderTarget)\n', '  File "/opt/spiderfoot/modules/sfp_spider.py", line 286, in spiderFrom\n    links = self.processUrl(startingPoint)  # fetch first page\n', '  File "/opt/spiderfoot/modules/sfp_spider.py", line 107, in processUrl\n    self.contentNotify(url, fetched, self.urlEvents[url])\n', '  File "/opt/spiderfoot/modules/sfp_spider.py", line 199, in contentNotify\n    self.notifyListeners(event)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 162, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/opt/spiderfoot/modules/sfp_dnsresolve.py", line 334, in processHost\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot/modules/sfp_spider.py", line 262, in handleEvent\n    return self.spiderFrom(spiderTarget)\n', '  File "/opt/spiderfoot/modules/sfp_spider.py", line 286, in spiderFrom\n    links = self.processUrl(startingPoint)  # fetch first page\n', '  File "/opt/spiderfoot/modules/sfp_spider.py", line 107, in processUrl\n    self.contentNotify(url, fetched, self.urlEvents[url])\n', '  File "/opt/spiderfoot/modules/sfp_spider.py", line 203, in contentNotify\n    self.notifyListeners(event)\n', '  File "/opt/spiderfoot/sflib.py", line 1501, in notifyListeners\n    prevEvent.sourceEvent.data.lower() == sfEvent.data.lower():\n', "AttributeError: 'dict' object has no attribute 'lower'\n"]`

**Comment by mschiessl** [comment]
Updated all python modules on my debian stretch and now it seems to work.

/close
