### ISSUE TITLE
failed: 'charmap' codec can't decode byte ..

### ISSUE THREAD

**Issue by danieltran95** [smicallef/spiderfoot#1695]
Hey guys,

I tried to scan for e-mails and got the following error:

```python3
2022-06-09 04:21:47,904 [INFO] sfwebui : Waiting for the scan to initialize...
Process Process-3:
Traceback (most recent call last):
  File "C:\Users\d.tran\Anaconda3\envs\spiderfoot\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\d.tran\Anaconda3\envs\spiderfoot\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\d.tran\Downloads\spiderfoot\sfscan.py", line 30, in startSpiderFootScanner
    return SpiderFootScanner(*args, **kwargs)
  File "C:\Users\d.tran\Downloads\spiderfoot\sfscan.py", line 202, in __init__
    tld_data = self.__sf.cacheGet("internet_tlds", self.__config['_internettlds_cache'])
  File "C:\Users\d.tran\Downloads\spiderfoot\sflib.py", line 303, in cacheGet
    return fp.read()
  File "C:\Users\d.tran\Anaconda3\envs\spiderfoot\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 10466: character maps to <undefined>
```

After a littler reasearch I found out that, this error is caused by the missing encoding during opening the cache file in sflib.py - line 302. Dunno whether this is the correct way to solve it, but I wanna share it for all other people which having problems.

Note: Forgive my, maybe, not correct way to inform you about this. It's the first I'am doing this.

Cheers,
Daniel ✌️

**Comment by bcoles** [comment]
Yeah there's issues with caching. I started working on a patch for this but got sidetracked.

**Comment by bcoles** [comment]
I still intend to fix the caching issues, but I suggest not running SpiderFoot on Windows, if possible. Windows is not officially supported, and all development and testing is performed on non-Windows systems.

It is possible that once the caching issues are resolved you'll still encounter issues when information is printed to terminal.

https://stackoverflow.com/questions/388490/how-to-use-unicode-characters-in-windows-command-line

Using Lucida Console font family for command prompt may or may not help:

https://docs.microsoft.com/en-us/typography/font-list/lucida-console

**Comment by guylando** [comment]
@danieltran95 Simple fix:
In sflib.py in cacheGet in the line:
`with open(cacheFile, "r") as fp:`
change it to
`with open(cacheFile, "r", encoding="utf-8") as fp:`

**Comment by danieltran95** [comment]
@guylando thanks for you'r reply solved it for myself already.
Only wanted to inform you guys about the bug.

**Comment by smicallef** [comment]
This has now been fixed (applied the PR from @guylando - thanks again).
