### ISSUE TITLE
API Keys Not Saving in Docker

### ISSUE THREAD

**Issue by dsgntechloyno** [smicallef/spiderfoot#170]
Hello, 

I've just started using Spiderfoot, currently running it in Docker on a fully up to date Kali install. I'm having a small issue where the API keys I add and save into Spiderfoot do not persist through a restart of either Spiderfoot or the machine. Is this expected behavior, user error, or a bug? Thank you.

**Comment by mbudge** [comment]
Using docker run which create a fresh image?

**Comment by dieee** [comment]
It seems reasonable to me. Docker should be used for fast deployment or testing.

**Comment by genevera** [comment]
have you tried to mount in the config files from your host machine?
