### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by efdsa** [smicallef/spiderfoot#171]
Unhandled exception (TypeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/home/spiderfoot/sfscan.py", line 265, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/home/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 210, in handleEvent\n    self.processHost(addr, parentEvent, False)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 322, in processHost\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_ripe.py", line 338, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1523, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_robtex.py", line 118, in handleEvent\n    self.results[str(ipaddr)] = True\n', 'TypeError: list indices must be integers, not str\n']

**Comment by smicallef** [comment]
Could you try the latest version (2.12)? This was fixed some time ago.
