### ISSUE TITLE
Malware packages

### ISSUE THREAD

**Issue by reinethernal** [smicallef/spiderfoot#1714]
After scanning requiremets.txt by https://packj.dev/ got a report that there's 5 dependencies thar have malwares.
![image](https://user-images.githubusercontent.com/35932698/177137952-1162d845-3950-447f-b4a7-4859c43bc39f.png)

**Comment by bcoles** [comment]
Are you sure? Which `requirements.txt` file did you upload? None of those dependencies you've listed are directly defined in `requirements.txt`. Although it is possible that some of the dependencies are dependent on these dependencies (`i-am-malicious` seems unlikely...).

I uploaded the [latest](https://github.com/smicallef/spiderfoot/blob/6a7aab0819d62ad98e3f84c9cb273ac66c73eb8f/requirements.txt) `requirements.txt` from the master branch to https://packj.dev/ and it found zero matches.

The `requirements.txt` file forces a minimum version for each dependency but does not lock to a specific version.

**Comment by reinethernal** [comment]
That one
[requirements.txt](https://github.com/smicallef/spiderfoot/files/9038891/requirements.txt)

**Comment by bcoles** [comment]
> That one [requirements.txt](https://github.com/smicallef/spiderfoot/files/9038891/requirements.txt)

Are you sure? That's the `requirements.txt` from the SiderFoot 4.0 release. It is out of date.

None the less, I uploaded it and no matches were returned.

```
Found 0/26 packages.
```

**Comment by reinethernal** [comment]
Tried your file, and the same result

**Comment by bcoles** [comment]
I think you misunderstand how https://packj.dev/ works.

If you browse to https://packj.dev/malware now it will list 5 known malicious packages. These are unrelated to the file you upload.
