### ISSUE TITLE
How i find others informations in website ? 

### ISSUE THREAD

**Issue by faust87280** [smicallef/spiderfoot#1716]
I'm really sorry my question is probably stupid,
but how i find information from a website? 
I mean, how can i add a class or id in the search? 
Thanks in advance

**Comment by bcoles** [comment]
I don't know what you mean. Is this question about SpiderFoot? Are you writing a SpiderFoot module? What are you trying to do?

Some modules use BeautifulSoup to parse HTML. Other modules use regex or simple string comparison.

**Comment by faust87280** [comment]
I explain : i did this tutorial https://null-byte.wonderhowto.com/how-to/extract-bitcoin-wallet-addresses-balances-from-websites-with-spiderfoot-cli-0238107/
and i want to create a module which search on the same site for the private keys. 
Can  you help? 
Thanks for your time.

**Comment by faust87280** [comment]
or maybee this is only a command? Because in the website i found there is private key under the id and class privkey but odn't know how to make them appears on the results
again thanks for your time.

**Comment by bcoles** [comment]
> and i want to create a module which search on the same site for the private keys.

The `sfp_bitcoin` module uses regex to extract Bitcoin addresses from `TARGET_WEB_CONTENT` events:

https://github.com/smicallef/spiderfoot/blob/4a0637eb342b9af5a3e088a705555c2346bcda50/modules/sfp_bitcoin.py#L43-L44

https://github.com/smicallef/spiderfoot/blob/4a0637eb342b9af5a3e088a705555c2346bcda50/modules/sfp_bitcoin.py#L79-L94

Valid addresses are stored as `BITCOIN_ADDRESS` events.

> in the website i found there is private key under the id and class privkey but odn't know how to make them appears on the results

SpiderFoot does not retrieve private keys.

**Comment by faust87280** [comment]
thanks, but you don't answer to my question.how i can search for an id or a class in a website then? 
i can't?

**Comment by bcoles** [comment]
> thanks, but you don't answer to my question.how i can search for an id or a class in a website then? i can't?

There is no existing functionality in SpiderFoot to search for a specified id or class as scan input.

SpiderFoot can only accept a few data types as input for a scan:

https://github.com/smicallef/spiderfoot/blob/4a0637eb342b9af5a3e088a705555c2346bcda50/spiderfoot/target.py#L14-L16

Some modules use BeautifulSoup to parse HTML. Other modules use regex or simple string comparison.

The `sfp_bitcoin` code shows above uses regex.

Here is an example of a module which uses BeautifulSoup to extract a CSRF token from HTML:

https://github.com/smicallef/spiderfoot/blob/4a0637eb342b9af5a3e088a705555c2346bcda50/modules/sfp_dnsdumpster.py#L65-L73

Here are a couple of tutorials about using BeautifulSoup to parse HTML:

* https://stackabuse.com/guide-to-parsing-html-with-beautifulsoup-in-python/
* https://www.pluralsight.com/guides/extracting-data-html-beautifulsoup

**Comment by faust87280** [comment]
thanks for your time.

**Comment by faust87280** [comment]
thanks a lot
