### ISSUE TITLE
Not able to run the ./sf.py

### ISSUE THREAD

**Issue by cybertricks** [smicallef/spiderfoot#172]
<img width="516" alt="screen shot 2018-03-13 at 11 20 47 am" src="https://user-images.githubusercontent.com/33148205/37324698-a0822b6e-26b0-11e8-928e-17ab8f57b5e1.png">

I have cloned the updated code and i am getting the following error.
" python ./sf.py 
Traceback (most recent call last):
  File "./sf.py", line 54, in <module>
    from sflib import SpiderFoot
  File "/home/ubuntu/spiderfoot/sflib.py", line 25, in <module>
    import requests
ImportError: No module named requests"

**Comment by razercortex101** [comment]
Did you look at the requirements.txt file? It says that you need requests version 2.7.0. To install, run this command: `sudo pip install requests==2.7.0`. If the command runs without any errors, then rerun `python ./sf.py`.

**Comment by ozskywalker** [comment]
Alternatively, try `pip install -r requirements.txt` to make sure you have everything as dictated within the requirements file.

**Comment by matheusfelixsm** [comment]
I have the same error, can anyone help? 

Could not find platform independent libraries <prefix>
Traceback (most recent call last):
  File "C:\Users\Usuário\Downloads\Programs\spiderfoot\sf.py", line 25, in <module>
    import cherrypy
ModuleNotFoundError: No module named 'cherrypy'

**Comment by ozskywalker** [comment]
@matheusfelixsm did you complete the pip install? & are you running multiple versions of Python on your machine?  Make sure when you pip install'd that you are using the same python env for spiderfoot.

**Comment by matheusfelixsm** [comment]
@ozskywalker How can I know if I'm running multiple versions of Python?

I'm new to the area and I'm still learning. I will explain what I did. First I installed Sherlock and installed Python on it, now I bought an investigative hacking workshop and it is teaching me how to put some tools here inside my Windows.

The codes they asked me to replicate were:

For Sherlock (PowerShell)

python -m pip install -r requirements.txt

For Chocolatey (PowerShell)

Set-ExecutionPolicy Bypass -Scope Process -Force;
[System.Net.ServicePointManager]::SecurityProtocol =
[System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iwr
https://community.chocolatey.org/install.ps1 -UseBasicParsing | iex

choco install python3 youtube-dl googlechrome ffmpeg exiftool exiftoolgui ripgrep vlc torbrowser googleearthpro keepassxc mediainfo git curl unzip wget phantomjs streamlink firefox
--ignore-checksums

For Spiderfoot (CMD)

py -m pip install holehe
py -m pip install maigret
py -m pip install installaloader
mkdir %userprofile%\Downloads\Programs
cd %userprofile%\Downloads\Programs
git clone https://github.com/laramies/theHarvester.git
cd theHarvester
py -m pip install -r requirements.txt
cd %userprofile%\Downloads\Programs
git clone https://github.com/sherlock-project/sherlock.git
cd sherlock
py -m pip install -r requirements.txt
cd %userprofile%\Downloads\Programs
git clone https://github.com/smicallef/spiderfoot.git
spiderfoot cd
py -m pip install -r requirements.txt

**Comment by bcoles** [comment]
> spiderfoot cd

This should be `cd spiderfoot` to change to the spiderfoot directory prior to installing dependencies with `pip`.

Regardless, you'll likely find SpiderFoot works better on Linux rather than Windows. Windows is not officially supported.
