### ISSUE TITLE
Unable to launch spiderfoot within a script.

### ISSUE THREAD

**Issue by BandidoPabs** [smicallef/spiderfoot#1721]
I'm trying to launch spiderfoot within a bash script in order to have it run automatically when I turn on the machine, but I keep running to the error screen, when I try to access the web gui. 

Basically the commands I've tried running within the script are as follows:

- python3 ~/spiderfoot/sf.py -l 0.0.0.0:5001
- python3 ~/spiderfoot/sf.py -l 0.0.0.0:5001 &
- /usr/bin/python3 ~/spiderfoot/sf.py -l 0.0.0.0:5001
- /usr/bin/python3 ~/spiderfoot/sf.py -l 0.0.0.0:5001 &
- nohup python3 ~/spiderfoot/sf.py -l 0.0.0.0:5001 &
- nohup /usr/bin/python3 ~/spiderfoot/sf.py -l 0.0.0.0:5001 &

I have had no success running these commands from the script, but if I run them outside of the script, I don't have any issues. 

It also seems to get stuck on this part: 

![image](https://user-images.githubusercontent.com/29881876/188672894-b5b43ff4-068b-4d3f-99a4-19fab2cabd6f.png)

Any recommendations?

**Comment by bcoles** [comment]
https://github.com/smicallef/spiderfoot/issues/82#issuecomment-689016158
