### ISSUE TITLE
Termux running

### ISSUE THREAD

**Issue by irulae** [smicallef/spiderfoot#1725]
Please provide a description of the issue and any relevant error messages.

If you can provide an application stack trace that is even better.

What version of Python are you using?

What version of SpiderFoot are you using (stable release or Git `master` branch)?

You may also wish to check if your issue has been posted previously:

* https://github.com/smicallef/spiderfoot/issues

python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      Building lxml version 4.9.1.
      Building without Cython.
      Error: Please make sure the libxml2 and libxslt development packages are installed.
      [end of output]

**Comment by smicallef** [comment]
Please ensure you're running Python 3.7 or newer, and that you've installed all the prerequisites with `pip install -r requirements.txt`.
