### ISSUE TITLE
File "sf.py", line 65

### ISSUE THREAD

**Issue by bembenk18** [smicallef/spiderfoot#1727]
Hi I'm having this problem in version 4.0
 
File "sf.py", line 65
    '__database': f"{SpiderFootHelpers.dataPath()}/spiderfoot.db",
                                                                ^
SyntaxError: invalid syntax

**Comment by bcoles** [comment]
What version of Python are you using?

**Comment by bembenk18** [comment]
Python 2.7.18, 
I tried in python3 an error appears

Traceback (most recent call last):
  File "./sf.py", line 25, in <module>
    import cherrypy
ModuleNotFoundError: No module named 'cherrypy'

**Comment by bcoles** [comment]
> Python 2.7.18

SpiderFoot requires Python 3.7+

> I tried in python3 an error appears
> ModuleNotFoundError: No module named 'cherrypy'

```
pip3 install -r requirements.txt
```

**Comment by bembenk18** [comment]
Same problem
python3 sf.py
Traceback (most recent call last):
  File "sf.py", line 25, in <module>
    import cherrypy
ModuleNotFoundError: No module named 'cherrypy'

**Comment by bcoles** [comment]
If you have multiple versions of Python / pip installed you'll need to ensure you're using the same version for both.

ie:

```
pip3.7 install -r requirements.txt
python3.7 sf.py
```
