### ISSUE TITLE
support@spiderfoot.io?

### ISSUE THREAD

**Issue by sam-morin** [smicallef/spiderfoot#1731]
The invalid target type error offers a link to "Contact us". Which is a mailto: link to "support@spiderfoot.io". There is no MX record for "spiderfoot.io" and SecurityTrails shows that there never has been since the domain's existence. 

Furthermore, from what I can tell, it doesn't appear that "spiderfoot.io" is associated with SpiderFoot.

![image](https://user-images.githubusercontent.com/76404220/194709299-b7f7e2fc-8a23-48f8-93f2-7509e072ef2e.png)

**Comment by bcoles** [comment]
The error page has used `.io` since 2013. I have no idea if this was ever correct.

https://github.com/smicallef/spiderfoot/blob/2472d6951e6cf0c5f92234ad667465da00757cf5/dyn/error.tmpl#L5

The correct email address is defined in the HEADER.

```
# grep -rn support@ spiderfoot
spiderfoot/templates/HEADER.tmpl:105:    <p>If you have any bugs to report, or requests for enhancements, please contact the support mailing list at <a href=mailto:support@spiderfoot.net>support@spiderfoot.net</a>.
spiderfoot/templates/error.tmpl:5:Please go back and try again. If you're pretty sure this is a bug, please <a href='mailto:support@spiderfoot.io'>contact us</a>
```
