### ISSUE TITLE
Running Spiderfoot as systemd service

### ISSUE THREAD

**Issue by Gill-Bates** [smicallef/spiderfoot#1737]
I want to run Spiderfoot as a systemd service and using nginx as a ReverseProxy

When I run Spiderfoot from the Console, nginx works as expected:

`python3 ./etc/spiderfoot/sf.py -l 127.0.0.1:5001`

But when I run spiderfoot as a systemd service, 

```
[Unit]
Description=Spiderfoot
After=multi-user.target network-online.target

[Service]
Type=simple
Restart=always
User=root
ExecStart=python3 ./etc/spiderfoot/sf.py -l 127.0.0.1:5001

[Install]
WantedBy=default.target
```

I get an error in my browser:

![image](https://user-images.githubusercontent.com/25774289/198552408-3e85d8c7-a6aa-4111-ac59-70d51889cd9c.png)

Any idea what going on here?

**Comment by bcoles** [comment]
What do the logs say?

**Comment by Gill-Bates** [comment]
Solved by adding `WorkingDirectory=/etc/spiderfoot` in my systemd-Configuration.

Working Solution:

```
[Unit]
Description=Spiderfoot
After=multi-user.target network-online.target

[Service]
Type=simple
Restart=always
User=www-data
WorkingDirectory=/etc/spiderfoot
ExecStart=python3 /etc/spiderfoot/sf.py -l 127.0.0.1:5001

[Install]
WantedBy=default.target
```
