### ISSUE TITLE
change shebang to python2

### ISSUE THREAD

**Issue by GIJack** [smicallef/spiderfoot#175]
most if not all linux distros have changed /usr/bin/python to Python2.

please change the shebang to /usr/bin/python2, and consider porting to python3

**Comment by deadbits** [comment]
"/usr/bin/env python" is probably a better idea if you only have python2 installed, or are using it as your main Python version. It'll find the Python interpreter for you based off of appearance in $PATH. Just a quick fix imho

**Comment by GIJack** [comment]
Python2 has been depreciated with redhat dropping support and will be abandoned upstream next year. having /usr/bin/env python pointing to python2 is insane. Its reasonable to expect python to be python 3.

**Comment by deadbits** [comment]
Unless you install Python3 yourself /usr/bin/env python still points to Python 2.7 on an Ubuntu 18.04 installation for  example. Upgrading the entire app to be Python 3 compatible needs to be another ticket entirely imho.

**Comment by bcoles** [comment]
`/usr/bin/env python` makes sense as the default shebang, but should be reviewed in 6 months time.

Issue #6 relates to porting the code base from Python 2 to Python 3.
