### ISSUE TITLE
Fix UI issues

### ISSUE THREAD

**Issue by GIJack** [smicallef/spiderfoot#176]

**Comment by GIJack** [comment]
There are several issues with the web UI

* On the Graph Page, the points are unlabeled until there is a mouseover, making the entire chart close to useless as far as purpose of a point chart goes. Then you cannot copy and paste data to use it elsewhere. Aparantly you have to zoom in pretty far. You also cannot click/double click these with any function preventing you from following a point further

* Browse - many of the elements cut the data off half way, such as the PGP or TLS key, so generally about half the data gets cut off making it close to unusable

* F

**Comment by smicallef** [comment]
I'll take a look at the first point, but for the second you need to adjust the maximum data save size in the "Storage" module (default is 1024 bytes).

**Comment by GIJack** [comment]
Alright, please change max data save size to a sane default then. 1024 bytes is apparently not.
