### ISSUE TITLE
error adding API keys from some module and changing setting always ending with Invalid Token

### ISSUE THREAD

**Issue by sil2727** [smicallef/spiderfoot#1765]
What version of Python are you using? 3.11

What version of SpiderFoot are you using (stable release or Git `master` branch)? stable release 4.0.0

You may also wish to check if your issue has been posted previously: I have checked the previous issue and it was marked as complete however the solution wasn't working for me
The previous solution mentioned using scanning (and stopped them then no error) but I didn't use the scan and it's idle. However, I can't add API keys.

I have tried from VirusTotal, abuseIPDB, and abstract.

Then I tried changing general settings, but it also came as an error with an invalid token and several numbers behind them.

Is there any reason why I can't change the settings?

below is the results after changing a setting and save changes (the difference was the several numbers behind invalid token text) However it resulted with an invalid token even when I was just changing the storage > Maximum bytes to store for any piece of information retrieved (0 = unlimited.) from 1024 to 0
[https://pasteboard.co/CoNdojbMV9Nd.png](https://pasteboard.co/CoNdojbMV9Nd.png)

**Comment by bcoles** [comment]
Do you have multiple SpiderFoot tabs open? The token is a CRSF token. Try reloading the settings page.

**Comment by sil2727** [comment]
> Do you have multiple SpiderFoot tabs open? The token is a CRSF token. Try reloading the settings page.

nope I only have one tab of spiderfoot open, I have tried closing apps, reloading apps, and restarting my PC to fresh start and load only spiderfoot, I don't know why it doesn't work

**Comment by sil2727** [comment]
Hello, sorry for the late reply. I successfully found the solution.

What I tried is using incognito, if I use the default (even with a different browser) it doesn't work it only works in incognito for me.
Thank you for replying and helping me ^^
