### ISSUE TITLE
Unable to parse social media accounts list: Extra data: line 1 column 4 (char 3) and API key problems 

### ISSUE THREAD

**Issue by Nulpickle** [smicallef/spiderfoot#1769]
Please provide a description of the issue and any relevant error messages.
You enabled sfp_c99, but did not set an API key!
You enabled sfp_sociallinks but did not set an API key!
Unable to parse social media accounts list: Extra data: line 1 column 4 (char 3)

Spiderfoot seems to have an API key issue I have no idea why this is happening i am using Ubuntu Linux 20.04 and i am using python 3.0 i did install it correctly but it seems to still have this problem  
If you can provide an application stack trace that is even better.

What version of Python are you using?
3.0
What version of SpiderFoot are you using (stable release or Git `master` branch)?
I am using the latest stable version of spider foot (4.0)

**Comment by Nulpickle** [comment]
im joust dumb after looking arround i seemed to fix it 
if your having the same error uninstall spiderfoot and install it though the url instead of the Copy paste line below the repository
do
`git install https://github.com/smicallef/spiderfoot` 
instead should fix your problems

**Comment by bcoles** [comment]
```
git clone https://github.com/smicallef/spiderfoot
```
