### ISSUE TITLE
sfp_accounts - error

### ISSUE THREAD

**Issue by pyx9999** [smicallef/spiderfoot#1782]
I am unable to use the social media profile finder. I have used it in the past and it worked fine. I keep getting an error.

sfp_accounts	ERROR	Unable to parse social media accounts list: Extra data: line 1 column 4 (char 3)

I have version. 4.0.0

My system is up to date.

how do I fix this?

**Comment by bcoles** [comment]
Use the latest version from the GitHub master branch. #1763

**Comment by pyx9999** [comment]
Still getting the same error. Please fix this.

**Comment by bcoles** [comment]
> Still getting the same error. Please fix this.

That seems unlikely. The issue is fixed on the master branch.

You could try clearing your cache from `$HOME/.spiderfoot/cache`.

**Comment by pyx9999** [comment]
I also posted another issue.

**Comment by bcoles** [comment]
> Now I get no results from social media profile finder. I used to be able to get at least 3 or 4 social profiles from the target. Something does not seem right...

There is not enough information to provide guidance. Review the logs.
