### ISSUE TITLE
sfp_numverify

### ISSUE THREAD

**Issue by pyx9999** [smicallef/spiderfoot#1783]
sfp_numverify seems to not work.

I have added an api key, but still getting an error that I did not add an api key.

**Comment by bcoles** [comment]
What error message do you get exactly?

"You enabled sfp_numverify but did not set an API key!" can only occur when the API key is empty:

https://github.com/smicallef/spiderfoot/blob/b0d2ccc54a02ddce157fa9d4e5d5f8db7696c230/modules/sfp_numverify.py#L141-L144

Works for me.
