### ISSUE TITLE
sfp_seon

### ISSUE THREAD

**Issue by pyx9999** [smicallef/spiderfoot#1784]
I unable to use the seon. I have entered an api key, but I cannot use this module. I keep getting the same error 

sfp_seon | ERROR | Error retrieving search results from seon.io

**Comment by bcoles** [comment]
The error "Error retrieving search results from seon.io" occurs when the HTTP response code from the server is not `200`:

https://github.com/smicallef/spiderfoot/blob/b0d2ccc54a02ddce157fa9d4e5d5f8db7696c230/modules/sfp_seon.py#L125-L127

Unfortunately I do not have an account on seon.io so cannot verify.
