### ISSUE TITLE
Problems opening the .gexf file(s)

### ISSUE THREAD

**Issue by CodeSyncio** [smicallef/spiderfoot#1799]
Hello,
When i try to open the exported graph from spiderfoot (Export selected --> GEXF) in a program like gephi, i get the error:

`failed to import <filename.gexf>: java.lang.NumberFormatException: For input string: "None"`

How can i fix this issue / what programs should i use to open these files?

**Comment by bcoles** [comment]
SpiderFoot did not set a value for the color alpha channel. SpiderFoot uses the `networkx` library to generate gexf files. An update to this library made setting a value for the alpha channel a requirement.

This should be fixed in #1819.
