### ISSUE TITLE
Bug: unhandled exception

### ISSUE THREAD

**Issue by dhombios** [smicallef/spiderfoot#180]
Unhandled exception (UnicodeDecodeError) encountered during scan.
> ['Traceback (most recent call last):\n', '  File "sfscan.pyc", line 265, in startScan\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_bingsearch.pyc", line 93, in handleEvent\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_spider.pyc", line 262, in handleEvent\n', '  File "modules\\sfp_spider.pyc", line 286, in spiderFrom\n', '  File "modules\\sfp_spider.pyc", line 135, in processUrl\n', '  File "modules\\sfp_spider.pyc", line 192, in linkNotify\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_crossref.pyc", line 135, in handleEvent\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 162, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 334, in processHost\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_bingsearch.pyc", line 93, in handleEvent\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 162, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 338, in processHost\n', '  File "modules\\sfp_dnsresolve.pyc", line 357, in processDomain\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_dnsbrute.pyc", line 131, in handleEvent\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 222, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 334, in processHost\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_googlesearchdomain.pyc", line 109, in handleEvent\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_crossref.pyc", line 85, in handleEvent\n', '  File "sflib.pyc", line 974, in fetchUrl\n', "UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 226: ordinal not in range(128)\n"]

**Comment by smicallef** [comment]
I just pushed a fix for this - could you git pull and try again?

**Comment by dhombios** [comment]
Sorry, I didn't received any GitHub notification about your answer. I'm going to try it again

**Comment by dhombios** [comment]
Setup.py is unable to import py2exe on windows although it is installed. How do you build from sources?
