### ISSUE TITLE
Docker installation stuck

### ISSUE THREAD

**Issue by DSGuglielmo** [smicallef/spiderfoot#1802]
I am trying to install Spiderfoot on MAC using docker. I followed one of your guides to install it.

1. docker ps -> kill any spiderfoot containers
2. cd to your spiderfoot installation (cloned repo) folder.
3. docker build -t spiderfoot .
4. docker-compose -f docker-compose.yml -f docker-compose-dev.yml up

I successfully reach the last step but then it gets stuck here:

[+] Building 0.0s (0/0)
[+] Running 3/3
 ✔ Network spiderfoot_default           Cr...                              0.1s 
 ✔ Volume "spiderfoot_spiderfoot-data"  Created                            0.0s 
 ✔ Container spiderfoot                 Created                            0.2s 
Attaching to spiderfoot
spiderfoot  | 2023-07-25 09:31:56,846 [INFO] sf : Starting web server at 0.0.0.0:5001 ...
spiderfoot  | 2023-07-25 09:31:56,846 [WARNING] sf : spiderfoot  | ********************************************************************
spiderfoot  | Warning: passwd file contains no passwords. Authentication disabled.
spiderfoot  | Please consider adding authentication to protect this instance!
spiderfoot  | Refer to https://www.spiderfoot.net/documentation/#security.
spiderfoot  | ********************************************************************
spiderfoot  | 

It remains like this forever. Do you have any idea how to get it working?
Thanks in advance.

**Comment by jopcode** [comment]
you can pass the param -d for detach from console
