### ISSUE TITLE
Installation Problem Kali Linux

### ISSUE THREAD

**Issue by pentestgirl** [smicallef/spiderfoot#181]
Hi there, 

I tried to install the requirements on an actual kali linux installation and get the following error:

_M2Crypto/SWIG -c SWIG/_m2crypto_wrap.c -o build/temp.linux-x86_64-3.5/SWIG/_m2crypto_wrap.o -DTHREADING
SWIG/_m2crypto_wrap.c:151:21: fatal error: Python.h: No such file or directory
# include <Python.h>
^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1_

Can anyone help me?

Thx.

**Comment by rl1k** [comment]
use docker :p

**Comment by socketz** [comment]
@pentestgirl You need the python-dev packages. Install them with:
`apt-get update && apt-get install python-dev`

**Comment by smicallef** [comment]
Maybe this is helpful? https://asciinema.org/a/126130
