### ISSUE TITLE
Failed communicating with server: HTTPConnectionPool

### ISSUE THREAD

**Issue by AdityaND2005** [smicallef/spiderfoot#1813]
The error message shows:

Failed communicating with server: HTTPConnectionPool(host='127.0.0.1', port=5001): Max retries exceeded with url: /ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f96a1d40550>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by bcoles** [comment]
This error indicates that the SpiderFoot server is not reachable.

What were you doing when this error occurred?

**Comment by AdityaND2005** [comment]
I figured it out.
First we need to run the spiderfoot.
Then we should access it using spiderfoot-cli.

**Comment by weat01** [comment]
How did you figure it out ? I've tried with with python 2.7 and 3.11 and still can't connect. How do you get it to 'run'?

**Comment by bcoles** [comment]
> How did you figure it out ? I've tried with with python 2.7 and 3.11 and still can't connect. How do you get it to 'run'?

```
python3 ./sf.py -l 127.0.0.1:5001
```
