### ISSUE TITLE
Unhandled exception occurred

### ISSUE THREAD

**Issue by thewerdisberd** [smicallef/spiderfoot#182]
A KeyError exception is raised, below is the traceback.

Unhandled exception (KeyError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/opt/spiderfoot-2.12/sfscan.py", line 265, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/opt/spiderfoot-2.12/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot-2.12/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot-2.12/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot-2.12/modules/sfp_dnsresolve.py", line 162, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/opt/spiderfoot-2.12/modules/sfp_dnsresolve.py", line 334, in processHost\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot-2.12/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot-2.12/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot-2.12/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot-2.12/modules/sfp_dnsresolve.py", line 162, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/opt/spiderfoot-2.12/modules/sfp_dnsresolve.py", line 338, in processHost\n    self.processDomain(dom, evt)\n', '  File "/opt/spiderfoot-2.12/modules/sfp_dnsresolve.py", line 357, in processDomain\n    self.notifyListeners(domevt)\n', '  File "/opt/spiderfoot-2.12/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot-2.12/modules/sfp_builtwith.py", line 127, in handleEvent\n    self.notifyListeners(ev)\n', '  File "/opt/spiderfoot-2.12/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot-2.12/modules/sfp_dnsresolve.py", line 227, in handleEvent\n    self.processHost(addr, parentEvent, False)\n', '  File "/opt/spiderfoot-2.12/modules/sfp_dnsresolve.py", line 334, in processHost\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot-2.12/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot-2.12/modules/sfp_censys.py", line 165, in handleEvent\n    self.notifyListeners(e)\n', '  File "/opt/spiderfoot-2.12/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot-2.12/modules/sfp_ripe.py", line 305, in handleEvent\n    asn = self.netblockAs(eventData)\n', '  File "/opt/spiderfoot-2.12/modules/sfp_ripe.py", line 94, in netblockAs\n    res = self.fetchRir("https://stat.ripe.net/data/whois/data.json?resource=" + prefix)\n', '  File "/opt/spiderfoot-2.12/modules/sfp_ripe.py", line 65, in fetchRir\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot-2.12/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot-2.12/modules/sfp_email.py", line 98, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/opt/spiderfoot-2.12/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/opt/spiderfoot-2.12/modules/sfp_fullcontact.py", line 151, in handleEvent\n    e = SpiderFootEvent("HUMAN_NAME", data[\'fullName\'], self.__name__, event)\n', "KeyError: 'fullName'\n"]

The above error was preceded by the below error message one second before, no other error messages were observed.

Return code indicates no results or potential API key failure.

Could this be related to bug #180? It is failing on the same line of sfscan.py, but the rest of the traceback is different.

**Comment by smicallef** [comment]
A fix for this was made to the repo some time ago, but it's newer than 2.12. Could you do a git pull and try again?
