### ISSUE TITLE
ModuleNotFoundError: No module named 'imp'

### ISSUE THREAD

**Issue by ghh45h35** [smicallef/spiderfoot#1834]
**Please provide a description of the issue and any relevant error messages.**
(pic deleted)
i don't know how to describe it other than this picture, but if i get specific questions about the error i could try answering them
**What version of Python are you using?**
3.12.1
**What version of SpiderFoot are you using (stable release or Git `master` branch)?**
stable release
>
>
(i fixed it, the problem was that i was on version 3.12.1 instead of 3.11)

**Comment by Mohd2493** [comment]
how did you resolve this?

**Comment by ghh45h35** [comment]
> how did you resolve this?

i switched from 3.12.1 to 3.11
