### ISSUE TITLE
ModuleNotFoundError: No module named 'cherrypy'

### ISSUE THREAD

**Issue by jaseemuddinn** [smicallef/spiderfoot#1836]
Traceback (most recent call last):
  File "D:\spiderfoot\sf.py", line 25, in <module>
    import cherrypy
ModuleNotFoundError: No module named 'cherrypy'
This is the error.

already tried using `pip3 install -r requirements.txt` , 
using pip version 23.3.2 and python version 3.10.11. 

How do I solve it?

**Comment by espin086** [comment]
I had the same error, and I have been manually installing all packages manually and finally stopped after I could no longer find why pip3 install -r requirements.txt was giving me errors even after manually installing all packages, I received this error: 

Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by espin086** [comment]
@jaseemuddinn - I found the solution, look at what Zachary says here about updating Cython, I tried it and have it working now: https://discuss.python.org/t/getting-requirements-to-build-wheel-did-not-run-successfully-exit-code-1/30365
![Uploading Screenshot 2024-01-07 at 11.44.59 PM.png…]()

**Comment by jaseemuddinn** [comment]
@espin086 Thanks a lot!! Worked for me :)

and for windows there is little change: 
`echo Cython^<3 > cython_constraint.txt`

^ is used to escape the < character in the Windows command prompt.
