### ISSUE TITLE
passwd 

### ISSUE THREAD

**Issue by GreenAA** [smicallef/spiderfoot#1849]
```
Warning: passwd file contains no passwords. Authentication disabled.
Please consider adding authentication to protect this instance!
```

hello i can't understend how i can add paswword authentication

thanks

**Comment by bcoles** [comment]
https://web.archive.org/web/20221005042654/http://www.spiderfoot.net/documentation/#auth

**Comment by GreenAA** [comment]
thansk bro 

i put txt file passwd.txt
inclue adminname:user:pass 

pu it in spiderfoot folder 
restart the vscode

and still get error 

2024-03-16 08:09:50,511 [WARNING] sf : 
********************************************************************
Warning: passwd file contains no passwords. Authentication disabled.
Please consider adding authentication to protect this instance!
Refer to https://www.spiderfoot.net/documentation/#security.

**Comment by bcoles** [comment]
> i put txt file passwd.txt

`passwd` not `passwd.txt`

**Comment by GreenAA** [comment]
thank you bro

where i need puth the passwd file ? 

PS C:\PycharmP\spiderfoot> python ./sf.py -l 127.0.0.1:5001

ERROR: passwd file exists in C:\PycharmP\spiderfoot
**SpiderFoot no longer supports loading credentials from the application directory.**
The passwd file is now loaded from your home directory: C:\Users\eyal/.spiderfoot/passwd  ( i check i no loaded)
This message will go away once you move or remove passwd from C:\PycharmP\spiderfoot ( i remove, i still don't load passwd)
