### ISSUE TITLE
[!] Server and CLI version are not the same

### ISSUE THREAD

**Issue by ADL7** [smicallef/spiderfoot#185]
As of ' commit eb2f0299fe46b4d83a6db6c2c154047084d1a60e (HEAD -> master, origin/master, origin/HEAD) ', when running the client inside of the docker container, I receive the error message: 

"[!] Server and CLI version are not the same (2.11 / 2.12). This could lead to unpredictable results!"

**Comment by smicallef** [comment]
Yep, that's a warning but not a hard error. It's a typo from that release which is fixed on master. Sorry for that.
