### ISSUE TITLE
grep.app modul doesn't work for subdomains

### ISSUE THREAD

**Issue by mecserlevente** [smicallef/spiderfoot#1862]
If I try to run the grep.app modul for a regular domain for example 'test.com' it returns valid response, but when I try to query a subdomain like 'mail.test.com' then the handleEvent() function is not getting involved and It doesn't give any response.

**Comment by bcoles** [comment]
The sfp_grep_app module only watches for `DOMAIN_NAME` events.

https://github.com/smicallef/spiderfoot/blob/0f815a203afebf05c98b605dba5cf0475a0ee5fd/modules/sfp_grep_app.py#L67-L68

If you want to search for subdomains the module should also watch for `INTERNET_NAME` events.

```diff
diff --git a/modules/sfp_grep_app.py b/modules/sfp_grep_app.py
index cb4d6333..791784df 100644
--- a/modules/sfp_grep_app.py
+++ b/modules/sfp_grep_app.py
@@ -65,7 +65,7 @@ class sfp_grep_app(SpiderFootPlugin):
             self.opts[opt] = userOpts[opt]
 
     def watchedEvents(self):
-        return ["DOMAIN_NAME"]
+        return ["DOMAIN_NAME", "INTERNET_NAME"]
 
     def producedEvents(self):
         return ["EMAILADDR", "EMAILADDR_GENERIC", "DOMAIN_NAME",
```
