### ISSUE TITLE
Sublist3r module absence

### ISSUE THREAD

**Issue by ADL7** [smicallef/spiderfoot#187]
I noticed that sublist3r does not appear in the web UI, but does appear in the modules folder on github. Also, it does not appear in the CSV results once a scan is complete. Should I run spiderfoot through the spiderfoot client "sfcli.py" to have access to the sublist3r module?

**Comment by smicallef** [comment]
Did you do a git pull of the latest version from master? sublist3r is only on git for now, it wasn't included in 2.12 but will be in 2.13.
