### ISSUE TITLE
Change Scan Status Without Deleting Data

### ISSUE THREAD

**Issue by g1ldedm1n1on** [smicallef/spiderfoot#190]
I have executed a scan against a larger domain. The scan log shows that it stopped a few days ago. I tried to stop the scan through the GUI but it never stopped. I was forced to kill sf.py.  Staring it back up again, state still shows running.  When I try to stop or change state, if prompts to delete data stating that the scan is not actually running.  There is a large amount of data that I would still like to have access to that was captured. Is there a way to get the status changed but retain the data?

Thanks in advance!

**Comment by smicallef** [comment]
The state of RUNNING is misleading in this case, because once sf.py has been killed, no further scans can be running. The data remains there though, so you haven't lost anything. I would rather deal with the issue of the scan having stopped unexpectedly. How many data elements did you get to?
