### ISSUE TITLE
Shows error webpage

### ISSUE THREAD

**Issue by WithoutName12** [smicallef/spiderfoot#1901]
Hello
    When i run spiderfoot webpage, it shows Error, literally page with only <body>Error</body>. There is error in console is 500 internal service error.

![image](https://github.com/user-attachments/assets/b7c36562-4ec1-4ad1-999a-65a4bb56f0bb)

 
I am using arch linux, Python 3.12.7.
Spider foot latest stable version.

**Comment by WithoutName12** [comment]
Solved, I had to just run spiderfoot from it's directory. I made symlink and used it that, but i was not working. I still wonder how to do so I can run it outside of it's folder.

**Comment by EmailScraper** [comment]
?
