### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by madisettisunil** [smicallef/spiderfoot#192]
Unhandled exception (KeyError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/pentest/spiderfoot-2.12/sfscan.py", line 265, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/pentest/spiderfoot-2.12/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/pentest/spiderfoot-2.12/modules/sfp_pastebin.py", line 123, in handleEvent\n    self.notifyListeners(evt2)\n', '  File "/pentest/spiderfoot-2.12/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/pentest/spiderfoot-2.12/modules/sfp_email.py", line 98, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/pentest/spiderfoot-2.12/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/pentest/spiderfoot-2.12/modules/sfp_fullcontact.py", line 151, in handleEvent\n    e = SpiderFootEvent("HUMAN_NAME", data[\'fullName\'], self.__name__, event)\n', "KeyError: 'fullName'\n"]

**Comment by madisettisunil** [comment]
Sorry bit of background is it stopped after nearly 50 min of scan, no proxies, nothing simple scan on domain thats all

**Comment by smicallef** [comment]
This has since been fixed in the repo. It will be included in the upcoming 3.0 release.
