### ISSUE TITLE
Unhandled exception using Footprint profile at the start

### ISSUE THREAD

**Issue by cybgit** [smicallef/spiderfoot#195]
I get the below log info when trying to run a scan using the Footprint profile. It maybe due to SSLv3 being used and the site doesnt support SSLv3? 

Note: Git clone of spiderfoot repository done today, so latest version. 

`Unhandled exception (BaseException) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/home/XXXX/spiderfoot/sfscan.py", line 188, in startScan\n    self.ts.config[\'_internettlds\'])\n', '  File "/home/XXXX/spiderfoot/sflib.py", line 116, in optValueToData\n    self.error("Unable to open option URL, " + val + ": " + str(e))\n', '  File "/home/XXXX/spiderfoot/sflib.py", line 298, in error\n    raise BaseException("Internal Error Encountered: " + error)\n', 'BaseException: Internal Error Encountered: Unable to open option URL, https://publicsuffix.org/list/effective_tld_names.dat: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake `failure>\n']`

I can successfully download the .dat file using wget for example.

> $ wget https://publicsuffix.org/list/effective_tld_names.dat
--2018-09-13 11:15:38--  https://publicsuffix.org/list/effective_tld_names.dat
Resolving publicsuffix.org (publicsuffix.org)... 54.239.164.30, 54.239.164.83, 54.239.164.8, ...
Connecting to publicsuffix.org (publicsuffix.org)|54.239.164.30|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 208537 (204K) [text/plain]
Saving to: ‘effective_tld_names.dat’
>
>100%[===========================================================>] 208,537     --.-K/s   in 0.02s
>
>2018-09-13 11:15:38 (9.61 MB/s) - ‘effective_tld_names.dat’ saved [208537/208537]"

**Comment by bcoles** [comment]
Looks like a connection issue. Is `publicsuffix.org` resolvable and routable?

**Comment by cybgit** [comment]
Sorry for the long wait. Yeah i can wget, curl the file fine from the system. I've also update-ca-certificates --fresh to freshly install a recent list of CAs, but i still get the error.

Also done a git pull on spiderfoot so am on the lastest afaik.

I'm on python 2.7.6, as when tried python3 ./sf.py it fails

Any help appreciaated
