### ISSUE TITLE
Dockerfile currently broken

### ISSUE THREAD

**Issue by iJebus** [smicallef/spiderfoot#228]
https://github.com/smicallef/spiderfoot/blob/dfc30a970b786a725662adee1af02e44c436e5ba/Dockerfile#L18

When building with the current Dockerfile, I run into the below error:

```bash
Successfully installed CherryPy-5.1.0 M2Crypto-0.23.0 Mako-1.0.4 MarkupSafe-1.1.0 beautifulsoup4-4.4.1 certifi-2018.10.15 chardet-3.0.4 idna-2.7 lxml-3.4.4 netaddr-0.7.18 requests-2.20.1 urllib3-1.24.1
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
tar: invalid magic
tar: short read
```

Changing the `$SPIDERFOOT_VERSION` back to `2.12.0`, the build then succeeds. Looking at the github releases page, I see the latest is 2.12.0.

I assume we just need a release for 3.0.0 to be made.

**Comment by smicallef** [comment]
Pushed a fix - premature version update reverted.

**Comment by iJebus** [comment]
Nice 👍
