### ISSUE TITLE
ERROR: Unable to perform WHOIS on test.com: (5, 'bad input')

### ISSUE THREAD

**Issue by nil0x42** [smicallef/spiderfoot#230]
All whois done by spiderfoot since yesterday fail with the following message:

`ERROR`
```
Unable to perform WHOIS on test.com: (5, 'bad input')
```

**Comment by smicallef** [comment]
Is this still happening? I'm not seeing any issues in my tests.

**Comment by tcwaddell** [comment]
I am encountering this issue as well.

**Comment by LoZio** [comment]
Same here, any debug I can upload?
Running (with a hell of work...) on Raspberry + Tor
