### ISSUE TITLE
sfp_socialprofiles: unknown url type: https%3a%2f%2fwww.facebook.com%2fUSERNAME%2fabout

### ISSUE THREAD

**Issue by nil0x42** [smicallef/spiderfoot#231]
Probably missing some `urldecode` in socialprofiles module.

This is an exception, but reported as an INFO, so it's 2 bugs for the price of 1

-----
`modules.sfp_socialprofiles` | `INFO`
```
Unexpected exception occurred fetching: https%3a%2f%2fwww.facebook.com%2fUSERNAME%2fabout (unknown url type: https%3a%2f%2fwww.facebook.com%2fUSERNAME%2fabout)
```

**Comment by nil0x42** [comment]
Update: just greper "unexpected" from my scan logs, and the same happens with linkedin URLs, and probably others too

**Comment by smicallef** [comment]
Should be fixed now - could you pull and try again?
