### ISSUE TITLE
Unhandled exception (AttributeError) encountered during scan.

### ISSUE THREAD

**Issue by mahawkma** [smicallef/spiderfoot#238]
Unhandled exception (AttributeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "sfscan.pyc", line 265, in startScan\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_bingsearch.pyc", line 93, in handleEvent\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 162, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 334, in processHost\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_bingsearch.pyc", line 93, in handleEvent\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 162, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 338, in processHost\n', '  File "modules\\sfp_dnsresolve.pyc", line 357, in processDomain\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_dnsbrute.pyc", line 131, in handleEvent\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_bingsearch.pyc", line 93, in handleEvent\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_spider.pyc", line 262, in handleEvent\n', '  File "modules\\sfp_spider.pyc", line 312, in spiderFrom\n', '  File "modules\\sfp_spider.pyc", line 107, in processUrl\n', '  File "modules\\sfp_spider.pyc", line 199, in contentNotify\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 162, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 334, in processHost\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_virustotal.pyc", line 205, in handleEvent\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_googlesearch.pyc", line 93, in handleEvent\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_spider.pyc", line 262, in handleEvent\n', '  File "modules\\sfp_spider.pyc", line 312, in spiderFrom\n', '  File "modules\\sfp_spider.pyc", line 107, in processUrl\n', '  File "modules\\sfp_spider.pyc", line 203, in contentNotify\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_dnsresolve.pyc", line 162, in handleEvent\n', '  File "modules\\sfp_dnsresolve.pyc", line 334, in processHost\n', '  File "sflib.pyc", line 1527, in notifyListeners\n', '  File "modules\\sfp_spider.pyc", line 262, in handleEvent\n', '  File "modules\\sfp_spider.pyc", line 286, in spiderFrom\n', '  File "modules\\sfp_spider.pyc", line 107, in processUrl\n', '  File "modules\\sfp_spider.pyc", line 203, in contentNotify\n', '  File "sflib.pyc", line 1501, in notifyListeners\n', "AttributeError: 'dict' object has no attribute 'lower'\n"]

**Comment by smicallef** [comment]
Have you pulled from the master branch recently? The line numbers in that error do not correspond with master. Perhaps try pulling again and see if the error repeats?

**Comment by mahawkma** [comment]
This is from running the Windows binary(2.12) pulled from spiderfoot.net on a 2012 box. Going to spin up a linux VM today and run give it a try on that to see if I can reproduce the exception.

**Comment by mahawkma** [comment]
Just realized I forgot to respond. Spun up a Kali box and was able to run a scan with no exceptions.
