### ISSUE TITLE
Critical Start-up Failure: No module named ipaddr

### ISSUE THREAD

**Issue by ebolanoso** [smicallef/spiderfoot#241]
When start spiderfoot like "python sf.py", shows this error>

Critical Start-up Failure: No module named ipaddr
=================================
It appears you are missing a module required for SpiderFoot
to function. Please refer to the documentation for the list
of dependencies and install them.

Python modules required are: 
 - M2Crypto
 - netaddr
 - dns
 - cherrypy
 - mako
 - socks
 - whois
 - PyPDF2
 - openxmllib
 - stem
 - bs4
 - gexf
 - phonenumbers
 - ipaddr
 - ipwhois

If you are running on Windows and getting this error, please
report this as a bug to support@spiderfoot.net.

**Comment by bcoles** [comment]
Spiderfoot dependencies must be installed prior to running Spiderfoot,

```sh
pip install -r requirements.txt
```

**Comment by ebolanoso** [comment]
thanks

**Comment by urbanadventurer** [comment]
I had this issue on Kali Linux, when installing SpiderFoot version 3.0 from the Github repo.
 
Prior to messing this error I had already completed the installation with pip.
```
pip install -r requirements.txt
```

This solution worked for me.
```
pip install openxmllib
```
