### ISSUE TITLE
fullName Unhandled exception (KeyError)

### ISSUE THREAD

**Issue by tskorick** [smicallef/spiderfoot#242]
Unhandled exception (KeyError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/root/Tools/spiderfoot-2.12/sfscan.py", line 265, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/root/Tools/spiderfoot-2.12/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/root/Tools/spiderfoot-2.12/modules/sfp_pastebin.py", line 123, in handleEvent\n    self.notifyListeners(evt2)\n', '  File "/root/Tools/spiderfoot-2.12/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/root/Tools/spiderfoot-2.12/modules/sfp_email.py", line 98, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/root/Tools/spiderfoot-2.12/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/root/Tools/spiderfoot-2.12/modules/sfp_fullcontact.py", line 151, in handleEvent\n    e = SpiderFootEvent("HUMAN_NAME", data[\'fullName\'], self.__name__, event)\n', "KeyError: 'fullName'\n"]

**Comment by bcoles** [comment]
This should be fixed in `master`. You can resolve this issue by cloning the latest version from GitHub.

Looking at the module [history](https://github.com/smicallef/spiderfoot/commits/master/modules/sfp_fullcontact.py), I'm fairly certain this issue was fixed in 0824c74f3433981f7e77cfd6ce46e15bd5af7dd5.

**Comment by workandresearchgithub** [comment]
Is this the same error?  I just installed Tpot yesterday, so one might expect it to have the latest version.....maybe not?
--
Unhandled exception (KeyError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/home/spiderfoot/sfscan.py", line 265, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 162, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 334, in processHost\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 162, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 338, in processHost\n    self.processDomain(dom, evt)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 357, in processDomain\n    self.notifyListeners(domevt)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_dnsbrute.py", line 131, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 222, in handleEvent\n    self.processHost(addr, parentEvent, False)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 334, in processHost\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_bingsharedip.py", line 133, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 162, in handleEvent\n    self.processHost(match[1], parentEvent, False)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 334, in processHost\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_bingsearch.py", line 93, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_spider.py", line 262, in handleEvent\n    return self.spiderFrom(spiderTarget)\n', '  File "/home/spiderfoot/modules/sfp_spider.py", line 286, in spiderFrom\n    links = self.processUrl(startingPoint)  # fetch first page\n', '  File "/home/spiderfoot/modules/sfp_spider.py", line 107, in processUrl\n    self.contentNotify(url, fetched, self.urlEvents[url])\n', '  File "/home/spiderfoot/modules/sfp_spider.py", line 199, in contentNotify\n    self.notifyListeners(event)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_email.py", line 98, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_fullcontact.py", line 151, in handleEvent\n    e = SpiderFootEvent("HUMAN_NAME", data[\'fullName\'], self.__name__, event)\n', "KeyError: 'fullName'\n"]
--

**Comment by bcoles** [comment]
@workandresearchgithub yes that looks like the same bug

**Comment by bcoles** [comment]
@workandresearchgithub Looking at the T-Pot [Dockerfile](https://github.com/dtag-dev-sec/tpotce/blob/master/docker/spiderfoot/Dockerfile#L35), it looks like they're using `v2.12.0-final`. While this is the latest tagged release of SpiderFoot, it's over a year old (released on Mar 3, 2018).

@smicallef is working hard on the next release. As far as I'm aware, there's no ETA.

**Comment by workandresearchgithub** [comment]
Wow, much appreciate the incredibly fast response!
Looks like in their dockerfile they do a clone using this line:

git clone --depth=1 https://github.com/smicallef/spiderfoot -b v2.12.0-final /home/spiderfoot

Would it be out of line to ask how to change that so it clones the latest version, as you recommended above? Apologies, but I'm not that familiar with git.......

**Comment by bcoles** [comment]
I'm not sure about building the appropriate Dockerfile. T-Pot has some custom configuration, such as the database path, so they can offer clearer guidance as to T-Pot configuration requirements.

Retrieving the latest version of SpiderFoot from the `master` branch on GitHub is as simple as:

```bash
git clone https://github.com/smicallef/spiderfoot 
```

This will clone SpiderFoot into a `spiderfoot` directory in your current working directory.

**Comment by workandresearchgithub** [comment]
Looks like tpot plans to fix this in the next release (https://github.com/dtag-dev-sec/tpotce/issues/313).
I'll try removing the branch portion (-b v2.12.0-final) and see if that is the magic.
Thanks again for the lighting fast response on this!

**Comment by t3chn0m4g3** [comment]
@bcoles Thanks, cloning from master fixes it. However I noticed `future` is missing from `requirements.txt` when building from `master`.

**Comment by bcoles** [comment]
It appears that multiple dependencies may or may not be missing from `requirements.txt` including `future`.

I'm not a spiderfoot dev - just passing through. @smicallef will review.

```
# rm requirements.txt
# pipreqs `pwd`
INFO: Successfully saved requirements file in /root/Desktop/spiderfoot/requirements.txt
# git diff requirements.txt
diff --git a/requirements.txt b/requirements.txt
index 4ea0d8f..09ca26b 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,9 +1,19 @@
-CherryPy>=14.0.0
-M2Crypto>=0.29.0
-Mako>=1.0.4
-beautifulsoup4>=4.4.1
-lxml>=3.4.4
-netaddr>=0.7.18
-requests>=2.20.0
 ipwhois==1.0.0
-ipaddr>=2.2.0
+requests==2.20.0
+Mako==1.0.7
+urllib3==1.24.1
+netaddr==0.7.19
+CherryPy==17.4.1
+future==0.16.0
+lxml==4.3.0
+pycrypto==2.6.1
+M2Crypto==0.32.0
+System==0.1.14
+beautifulsoup4==4.7.1
+python_dateutil==2.8.0
+protobuf==3.7.0
+mock==2.0.0
+pep8==1.7.1
+py2exe==0.9.2.2
+pyflakes==2.1.1
+re2==0.2.24
```

**Comment by bcoles** [comment]
`future` is now included in `requirements.txt` as of 41677bcaae9495dcb70c9ac06d05c0b1de6cdcb0.

**Comment by bcoles** [comment]
I think this issue can now be closed? @t3chn0m4g3 @workandresearchgithub @tskorick

**Comment by t3chn0m4g3** [comment]
@bcoles Yes, thank you!
