### ISSUE TITLE
Cymon API is Changing 29th April 2019

### ISSUE THREAD

**Issue by Sorren1969** [smicallef/spiderfoot#245]
Hello,

I am adding API keys at present and noticed that the current Cymon API is going to be discontinued on 29th April 2019.

Fortunately there is a new V2 API. See here:

https://app.cymon.io/?utm_source=banner&utm_campaign=preview

and here:

http://docs.cymon.io/

Apologies if you are already aware.

(SpiderFoot is great, BTW.)

Cheers.

**Comment by smicallef** [comment]
Thanks for the info, and no I wasn't aware. I'll work on an update and close this once it's merged.

**Comment by smicallef** [comment]
Looks like cymon.io is being decommissioned end of April... :/

**Comment by smicallef** [comment]
Won't do anything here seeing as the service will be shut down.
