### ISSUE TITLE
Cherry cannot to pip 

### ISSUE THREAD

**Issue by hnlisf** [smicallef/spiderfoot#249]
Use docker bulid image, but cherry cannot to pip install

```
Looking in indexes: https://pypi.douban.com/simple/
Collecting CherryPy>=14.0.0 (from -r requirements.txt (line 1))
  Downloading https://pypi.doubanio.com/packages/aa/0e/4e353c47789ccb50130a44e765dae55b3e85abca01ff21930533ab36afc9/CherryPy-18.1.1-py2.py3-none-any.whl (417kB)
CherryPy requires Python '>=3.5' but the running Python is 2.7.15

(mypy) dsfs@beekeeper:~/myworkspace/spiderfoot/spiderfoot$ cat Dockerfile 
```

**Comment by hnlisf** [comment]
other :
`
Collecting more-itertools>=2.6 (from cheroot>=5.9.1->CherryPy==14.0.0->-r requirements.txt (line 1))
  Downloading https://pypi.doubanio.com/packages/29/ed/3a85eb4afdce6dc33e78dad885e17c678db8055bf65353e0de4944c72a40/more-itertools-7.0.0.tar.gz (70kB)
more-itertools requires Python '>=3.4' but the running Python is 2.7.15
`

**Comment by bcoles** [comment]
Have you tried with `pip2 install -r requirements.txt` ?

**Comment by hnlisf** [comment]
I has tried with  pip2 install -r requirements.txt, but the same mistake happened。Like this：

`
(mypy) sdfs@beekeeper:~/myworkspace/spiderfoot/spiderfoot$ pip2 list
Package    Version
---------- -------
pip        18.1   
setuptools 40.8.0 
wheel      0.33.1 
You are using pip version 18.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(mypy) sdfs@beekeeper:~/myworkspace/spiderfoot/spiderfoot$ pip2 install -r requirements.txt  -i https://pypi.douban.com/simple/
Looking in indexes: https://pypi.douban.com/simple/
Collecting CherryPy>=14.0.0 (from -r requirements.txt (line 1))
  Downloading https://pypi.doubanio.com/packages/aa/0e/4e353c47789ccb50130a44e765dae55b3e85abca01ff21930533ab36afc9/CherryPy-18.1.1-py2.py3-none-any.whl (417kB)
    100% |████████████████████████████████| 419kB 1.9MB/s 
CherryPy requires Python '>=3.5' but the running Python is 2.7.12

`

**Comment by hnlisf** [comment]
I has use another method to installed

download   tar package on "https://www.spiderfoot.net/files/spiderfoot-2.12.0-src.tar.gz" ,and "docker DockerProfile "

**Comment by bcoles** [comment]
2.12.0 is ancient - over a year old

**Comment by marc1n** [comment]
Try add ```more-itertools < 6; python_version < '3'``` to `requirements/txt` because more-itertools does not support Python 2.x from version 6.0.0.

**Comment by notTitoH** [comment]
> Have you tried with `pip2 install -r requirements.txt` ?

found this old thread, to me it worked with `pip3 install -r requirements.txt`
