### ISSUE TITLE
Docker File Issue Invalid Tar

### ISSUE THREAD

**Issue by vkimmanuelgeorge** [smicallef/spiderfoot#250]
tar: invalid magic
tar: short read

![image](https://user-images.githubusercontent.com/40862721/55358658-ee880100-549d-11e9-931c-dffca5a30434.png)

ENV SPIDERFOOT_VERSION 3.0.0

**Comment by vkimmanuelgeorge** [comment]
running this docker system prune -a helped me. Will close the issue.

**Comment by arnydo** [comment]
Same issue here...What host OS are you running?

**Comment by vkimmanuelgeorge** [comment]
@arnydo Ubuntu 18
i put a possible fix https://github.com/smicallef/spiderfoot/pull/253

**Comment by smicallef** [comment]
Should now be fixed.. please try again with the latest master, as the Dockerfile has been updated.
