### ISSUE TITLE
sfp_viewdns not working

### ISSUE THREAD

**Issue by headhu** [smicallef/spiderfoot#264]
I copied this module from github as it was not included with SF 2.12 and it does not work, I cannot figure out why. I Have a proper API key provided and this API key works (confirmed manually), but no queries from SF are being made - the query counter in viewdns interface is not increasing and no data is being downloaded to SF. Is this module still supported by SF 2.12?

**Comment by bcoles** [comment]
> does not work

Need more info. Enable debugging in the scan config.

> Is this module still supported by SF 2.12?

You should probably be using the latest version of Spiderfoot from Github `master` branch.

[sfp_viewdns](https://github.com/smicallef/spiderfoot/blob/master/modules/sfp_viewdns.py) exists in the latest version and is supported.

>  no queries from SF are being made

The module watches for the following events:

```python
["EMAILADDR", "HUMAN_NAME", "IP_ADDRESS", "PROVIDER_DNS"]
```

The module will not execute unless any of the above events are triggered.

**Comment by headhu** [comment]
I did upgrade my SF installation to the latest master branch, however your message got me thinking. Do I understand this correctly that this module will not work by itself, because it needs other modules to feed the data like IP address, email etc?

**Comment by bcoles** [comment]
> this module will not work by itself, because it needs other modules to feed the data like IP address, email etc?

Correct.


The module watches for the following events:

```python
["EMAILADDR", "HUMAN_NAME", "IP_ADDRESS", "PROVIDER_DNS"]
```

The module will not execute unless any of the above events are triggered.

When you enter a domain name into Spiderfoot, it is automatically detected and stored as an `INTERNET_NAME` object.

For whatever reason, the `sfp_viewdns` module does not watch for these events. I'm not sure the design decision behind this, without reviewing the module code; however, a simple workaround is to enable both the `DNS Resolve` module along with the ViewDNS module. The DNS Resolve module will automatically resolve the `INTERNET_NAME` to IP address(es) `IP_ADDRESS`, thus triggering the `sfp_dns` module.

**Comment by headhu** [comment]
perfect, thank you :-)

**Comment by smicallef** [comment]
Yep, @bcoles got it right. SpiderFoot needs to make it more obvious in the UI that some modules (like `sfp_dnsresolve`) are really important and should probably be enabled in every scan if possible. Also `sfp_viewdns` is not listening for `INTERNET_NAME` or `DOMAIN_NAME` by design, as it operates on other data points to interact with their API.
