### ISSUE TITLE
My domain name is misidentified as a ASN and thus no scan is started

### ISSUE THREAD

**Issue by bertjwregeer** [smicallef/spiderfoot#286]
I own the domain name `0x58.com` which I also use as my email address, and Spiderfoot seems to classify it as an ASN when I try to scan it, this leads to it attempting to get the information about the ASN, receiving a 404 and not continuing.

**Comment by bcoles** [comment]
Thanks. Fixed.

**Comment by bertjwregeer** [comment]
Wow... that was fast!
