### ISSUE TITLE
[suggestion] OPSWAT Metadefender

### ISSUE THREAD

**Issue by Dr-Flay** [smicallef/spiderfoot#311]
Metadefender has a lot in common with VirusTotal but includes a few other features.
If used with a full setup users can make use of a self hosted core (like hosting your own VirusTotal), but you can use the free API for general use of the Metadefender cloud.
https://onlinehelp.opswat.com/mdcloud/3._Public_APIs.html
They have an extension which uses the free API for virus checking files so you can have a quick look at it.
https://www.opswat.com/free-tools

**Comment by bcoles** [comment]
I've started on this, but don't have an ETA for completion.

**Comment by bcoles** [comment]
I've added a module for MetaDefender in #375.

It uses the IP reputation and domain reputation API endpoints (which require a valid API key):

* https://onlinehelp.opswat.com/mdcloud/4.1_IP_Reputation.html
* https://onlinehelp.opswat.com/mdcloud/4.5_Domain_Reputation.html
