### ISSUE TITLE
[suggestion] Pulsedive

### ISSUE THREAD

**Issue by Dr-Flay** [smicallef/spiderfoot#315]
Pulsedive OSINT lookup can be used with or without the API
https://pulsedive.com/api/
Existing examples in use;
https://chrome.google.com/webstore/detail/pulsedive-threat-intellig/gdbemlfgncdmmljmkkcemfedbbfgghcp
https://github.com/cloudtracer/ThreatPinchLookup/ (does not use the API)

**Comment by bcoles** [comment]
Using APIs is preferred, where possible, as parsing API data is generally more reliable and far easier to maintain.

Additionally, scraping is forbidden by the terms of service for some data sources. (I'm not sure if that applies to Pulsedive.)

Ultimately its @smicallef 's call. If you PR your code, others can use it, even if it doesn't get merged.

**Comment by Dr-Flay** [comment]
Yes indeed using the API is always preferred as you have more functionality.

I have yet to customise SpiderFoot as I have been spending time getting familiar with the individual services, and comparing/finding others.
Any services I add, I will indeed share

**Comment by bcoles** [comment]
I took a look at the [Pulsedive documentation](https://pulsedive.com/api/) and terms of service.

An API key is not required, but they've politely suggested that an API key should be used for programmatic access.

For this reason, the [sfp_pulsedive module](https://github.com/smicallef/spiderfoot/blob/master/modules/sfp_pulsedive.py) requires an API key. You could always comment out the `api_key` check if you don't want to use an API key.

> API Key
>
> You don't technically need an API key to access the API, but it helps us keep track of how many requests are being used. If the API key is not used with API requests (which happens when users are using Pulsedive normally), we may use other methods of tracking requests, such as your IP address and session information. But, this could be inaccurate and the rate limit is set for free users based on typical user behavior, so if you're attempting to access the API programmatically or through the command line, you should be using an API key.
