### ISSUE TITLE
start failure (loop): Linux Mint 19.1

### ISSUE THREAD

**Issue by elsaddiq** [smicallef/spiderfoot#347]
First of all, this issue is not resolved in issue #22 or #26.

Upon starting Spiderfoot, I get the you need to run "pip install -r requirements.txt" message.

After executing the command, I get Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-91bPqW/M2Crypto/"

Error code 1 "no module named setuptools."

I've tried running "pip install  M2Crypto"

Everything installs ok. After starting again, same recommendation; same errors.

**Comment by bcoles** [comment]
You probably need `setuptools`.

```sh
sudo apt-get install -y python-setuptools
```

**Comment by bcoles** [comment]
welp, I just tested on Mint 19, and that didn't work. I'm guessing this is a python environment issue.

**Comment by bcoles** [comment]
Resolved with:

```sh
sudo apt-get install python-dev
sudo apt-get install swig
sudo apt-get install python-setuptools
sudo pip2.7 install -r requirements.txt
```

Make sure the above installs `python2.7-dev` related packages and not `python3` pacakges.
Also you probably shouldn't run `pip` with sudo... `Shrug ¯\_(ツ)_/¯`

**Comment by elsaddiq** [comment]
This just created all kinds of new errors. Still a no-go for me.

     SWIG/_m2crypto.i:62: Error: Unable to find 'openssl/opensslv.h'
    SWIG/_m2crypto.i:68: Error: Unable to find 'openssl/safestack.h'
    SWIG/_evp.i:12: Error: Unable to find 'openssl/opensslconf.h'
    SWIG/_rc4.i:5: Error: Unable to find 'openssl/opensslconf.h'
    SWIG/_ec.i:7: Error: Unable to find 'openssl/opensslconf.h'
    error: command 'swig' failed with exit status 1
    ----------------------------------------
  Rolling back uninstall of M2Crypto
  Moving to /usr/lib/python2.7/dist-packages/M2Crypto
   from /usr/lib/python2.7/dist-packages/~2Crypto
  Moving to /usr/lib/python2.7/dist-packages/M2Crypto-0.27.0.egg-info
   from /usr/lib/python2.7/dist-packages/~2Crypto-0.27.0.egg-info
ERROR: Command "/usr/bin/python2.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-zNJdHJ/M2Crypto/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-hI6U37/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-zNJdHJ/M2Crypto/

**Comment by bcoles** [comment]
Looks like you have issues related to OpenSSL. You'll likely need some combination of:

* libssl-dev
* python-openssl

**Comment by elsaddiq** [comment]
This solved the problem. Thank you.
(My touchpad is buggy now, but I'm not sure if that's related.)
