### ISSUE TITLE
Integration missing

### ISSUE THREAD

**Issue by KlausItem** [smicallef/spiderfoot#351]
Hello 
i found a info on https://n0where.net/open-source-intelligence-automation-spiderfoot
that domaintools and some other Sources should be integrated, but i could not find them.

Can you help.

Regards 

Klaus

**Comment by bcoles** [comment]
Spiderfoot is constantly evolving. That article is 4+ years old. The domaintools module is no longer available.

You can see the list of currently available modules here:

* https://github.com/smicallef/spiderfoot/tree/master/modules

As far as I know, the framework has never contained a `sfp_domaintools` module; however, it's possible that one of the old modules made use of the Domain Tools web site.

You can find old releases of Spiderfoot here:

* https://github.com/smicallef/spiderfoot/releases
