### ISSUE TITLE
sfp_sslcert gets wrong certificate

### ISSUE THREAD

**Issue by LoZio** [smicallef/spiderfoot#353]
If you run sfp_sslcert  against a web site that has the default SSL certificate and several other virtual hosts over SSL, you will get the default certificate every time.
Python libs require a little fiddling to have SNI working correctly, and not always do, but getting the wrong certificate is a problem. I better have no info instead of wrong info.

**Comment by Dr-Flay** [comment]
Does Qualys SSL Labs get the correct cert if you test it with their service ?
If so, perhaps another reason to use their API.

**Comment by LoZio** [comment]
Yes it does, as any other tool that considers SNI. Just look at the different results you get using:
`openssl s_client -servername mysite.com -connect mysite.com:443`
Gets the correct certificate since it forces SNI with 

> -servername

. The same command wiyhout SNI:
`openssl s_client -connect chrismeller.com:443`
gets the default certificate because it just makes the connection to the default endpoint, usually the snake-oil one. You are behaving like that.
You're using sockets and this is the wrong way to get certificate. In Python addressing SNI is not always easy or reliable, I found myself in trouble with each library and version within it.
I would replace the lines 113-120 with something using **ssl.get_server_certificate** and decode the result with **OpenSSL.crypto.load_certificate**. This works most of the times but depending on the server setup may again fail with TLS 1.3.
Last resource to make it more reliable (and slower) is to fork out to openssl command to fetch the certificate, you can then decode in process or let openssl binary do the whole thing and grab the result.

**Comment by smicallef** [comment]
Does this issue still exist with SpiderFoot 3.x, since it's no longer using M2Crypto?

**Comment by LoZio** [comment]
I run a scan yesterday and it seems fine now
