### ISSUE TITLE
Module seem to not be able to act on their own

### ISSUE THREAD

**Issue by fakeNews-jpg** [smicallef/spiderfoot#357]
Hello,

First, thanks for this great tool.

In `sfp_template.py`, it is written :

```
# If you intend for this module to act on its own (e.g. not solely rely
    # on events from other modules, then you need to have a start() method
    # and within that method call self.checkForStop() to see if you've been
    # politely asked by the controller to stop your activities (user abort.)
```

Because it's exactly what i try to do, I wrote a "start()" method in my plugin class who run my action. 
Yet, the action is not begun by this method and nothing happen.

Do I do it wrong or is there a bug here ? 

Thanks a lot in advance,
_JK_

Note : the same code works with handleEvent but that's not what I'm trying to do

**Comment by smicallef** [comment]
Closed this due to its age, but if you share the code please re-open and I'll take a look.
