### ISSUE TITLE
Modules notloading properly

### ISSUE THREAD

**Issue by yodatron** [smicallef/spiderfoot#358]
I have tried to install the modules with every package manager I can imagine on Mint. I've used apt-get, pip, pip3, east_install while cd'd into spiderfoot dir...everytime I MacGyver my way into accidentally fixing one another has the same problem:

Critical Start-up Failure: No module named openxmllib
=================================
It appears you are missing a module required for SpiderFoot
to function. Please refer to the documentation for the list
of dependencies and install them.

Python modules required are: 
 - M2Crypto
 - netaddr
 - dns
 - cherrypy
 - mako
 - socks
 - whois
 - PyPDF2
 - openxmllib
 - stem
 - bs4
 - gexf
 - phonenumbers
 - ipaddr
 - ipwhois

****************************************************************
Please note that if you are seeing this after doing a git pull
then you just need to do a `pip install -r requirements.txt` as
dependencies previously bundled with SpiderFoot are now
unbundled.
****************************************************************

**Comment by smicallef** [comment]
I haven't tested on Mint but based on the error have your tried to `pip install openxmllib`?

**Comment by bcoles** [comment]
Ensure you're using Python2 and refer to #347
