### ISSUE TITLE
How to store configuration?

### ISSUE THREAD

**Issue by h51un6** [smicallef/spiderfoot#370]
Hello,

I am using Spiderfoot with Docker. The app in stored on a dockerhub. How can I store the configuration (keys, etc.) and load them when I pull the app?

Thanks you

**Comment by sidahmed-malaoui** [comment]
This kinda has a relation with this #478 . If they move these files to a sub directory, it will be easy to save them between docker run's using this :
```bash
docker volume create spiderfoot-vol
docker run -v spiderfoot-vol:/home/spiderfoot/data -d spiderfoot
```

**Comment by smicallef** [comment]
Could you try using the volume functionality in the latest `Dockerfile`?
