### ISSUE TITLE
Feature Request: Dark Mode 

### ISSUE THREAD

**Issue by aress31** [smicallef/spiderfoot#374]
Since we live in the dark mode era, it would be very nice to add a dark mode theme to the Spider Foot/ Spider Foot HX web interface.

**Comment by bcoles** [comment]
I support this endeavor, however I don't foresee development efforts directed towards implementing this any time soon.

In the interim, here's a rudimentary bookmarklet:

```
javascript:document.body.style="background:#000";window.stop();
```

**Comment by smicallef** [comment]
This has now been implemented on the master branch and will be a part of the upcoming 3.4 release.
