### ISSUE TITLE
Static path when using with Nginx reverse proxy

### ISSUE THREAD

**Issue by gmkbenjamin** [smicallef/spiderfoot#391]
Hi all,
Is anyone using this behind a Nginx revese proxy? 
I have it configured as https://site.com/sf but it's trying to use static path. Thank you in advance.

**Comment by TrinityIsStillMyName** [comment]
I am currently running SF behind nginx reverse proxy with the following location block config and did not see any frontend or backend errors relating to static paths. Is this maybe fixed now @gmkbenjamin ?

```
        location / {
                proxy_buffering off;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass http://<BACKEND_IP>:5001/;
        }

```

**Comment by gmkbenjamin** [comment]
HI @TrinityIsStillMyName,
Thank you for that. Accessing it at the root / location is fine. My setting is 
 location /sf {
                proxy_buffering off;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass http://<BACKEND_IP>:5001/;
        }
I want to access it via https://site.com/sf/
