### ISSUE TITLE
M2Crypto build issue on Windows

### ISSUE THREAD

**Issue by waydaws** [smicallef/spiderfoot#397]
OpenSSL is installed and Lib and include set so that M2Crypt can be built, but now I get the following error:

  Running setup.py install for M2Crypto ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python27\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\temp\\pip-install-shzx
ap\\M2Crypto\\setup.py'"'"'; __file__='"'"'c:\\temp\\pip-install-shzxap\\M2Crypto\\setup.py'"'"';f=getattr(tokenize, '"'"'ope
n'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'
"'"'))' install --record 'c:\temp\pip-record-xygj76\install-record.txt' --single-version-externally-managed --compile
         cwd: c:\temp\pip-install-shzxap\M2Crypto\
    Complete output (96 lines):
    running install
    running build
    running build_py
    copying M2Crypto\ASN1.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\AuthCookie.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\BIO.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\BN.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\callback.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\DH.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\DSA.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\EC.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\Engine.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\Err.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\EVP.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\ftpslib.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\httpslib.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\m2.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\m2crypto.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\m2urllib.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\m2urllib2.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\m2xmlrpclib.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\Rand.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\RC4.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\RSA.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\six.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\SMIME.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\threading.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\util.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\X509.py -> build\lib.win-amd64-2.7\M2Crypto
    copying M2Crypto\__init__.py -> build\lib.win-amd64-2.7\M2Crypto
    creating build\lib.win-amd64-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\cb.py -> build\lib.win-amd64-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\Checker.py -> build\lib.win-amd64-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\Cipher.py -> build\lib.win-amd64-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\Connection.py -> build\lib.win-amd64-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\Context.py -> build\lib.win-amd64-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\Session.py -> build\lib.win-amd64-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\SSLServer.py -> build\lib.win-amd64-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\ssl_dispatcher.py -> build\lib.win-amd64-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\timeout.py -> build\lib.win-amd64-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\TwistedProtocolWrapper.py -> build\lib.win-amd64-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\__init__.py -> build\lib.win-amd64-2.7\M2Crypto\SSL
    running build_ext
    building 'M2Crypto._m2crypto' extension
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    creating build\temp.win-amd64-2.7\Release\SWIG
    C:\Users\waydaws\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD
 /W3 /GS- /DNDEBUG -Ic:\python27\include -Ic:\python27\PC -Ic:\temp\pip-install-shzxap\M2Crypto\SWIG /TcSWIG/_m2crypto_wrap.c
 /Fobuild\temp.win-amd64-2.7\Release\SWIG/_m2crypto_wrap.obj -DTHREADING -D_CRT_SECURE_NO_WARNINGS
    _m2crypto_wrap.c
    c:\temp\pip-install-shzxap\M2Crypto\SWIG\py3k_compat.h(27) : warning C4273: 'PyLong_FromLong' : inconsistent dll linkage
            c:\python27\include\longobject.h(18) : see previous definition of 'PyLong_FromLong'
    SWIG/_m2crypto_wrap.c(4331) : warning C4005: 'PyUnicode_FromString' : macro redefinition
            c:\python27\include\unicodeobject.h(194) : see previous definition of 'PyUnicode_FromString'
    SWIG/_m2crypto_wrap.c(4332) : warning C4005: 'PyUnicode_Format' : macro redefinition
            c:\python27\include\unicodeobject.h(188) : see previous definition of 'PyUnicode_Format'
    SWIG/_m2crypto_wrap.c(4446) : warning C4244: '=' : conversion from 'Py_ssize_t' to 'int', possible loss of data
    SWIG/_m2crypto_wrap.c(4513) : warning C4244: '=' : conversion from 'Py_ssize_t' to 'int', possible loss of data
    SWIG/_m2crypto_wrap.c(4815) : warning C4244: 'return' : conversion from 'Py_ssize_t' to 'int', possible loss of data
    SWIG/_m2crypto_wrap.c(5164) : warning C4267: 'return' : conversion from 'size_t' to 'int', possible loss of data
    SWIG/_m2crypto_wrap.c(5308) : warning C4267: 'function' : conversion from 'size_t' to 'long', possible loss of data
    SWIG/_m2crypto_wrap.c(5422) : warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data
    SWIG/_m2crypto_wrap.c(5444) : warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data
    SWIG/_m2crypto_wrap.c(8075) : warning C4244: 'function' : conversion from 'Py_ssize_t' to 'int', possible loss of data
    SWIG/_m2crypto_wrap.c(8118) : warning C4244: 'function' : conversion from 'Py_ssize_t' to 'int', possible loss of data
    SWIG/_m2crypto_wrap.c(8528) : warning C4244: 'function' : conversion from 'Py_ssize_t' to 'long', possible loss of data
    SWIG/_m2crypto_wrap.c(8709) : warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data
    SWIG/_m2crypto_wrap.c(8780) : warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data
    SWIG/_m2crypto_wrap.c(8895) : warning C4244: 'function' : conversion from 'Py_ssize_t' to 'long', possible loss of data
    SWIG/_m2crypto_wrap.c(8917) : warning C4244: '=' : conversion from 'Py_ssize_t' to 'long', possible loss of data
    SWIG/_m2crypto_wrap.c(9293) : warning C4244: 'function' : conversion from 'Py_ssize_t' to 'long', possible loss of data
    SWIG/_m2crypto_wrap.c(9319) : warning C4244: 'function' : conversion from 'Py_ssize_t' to 'long', possible loss of data
    SWIG/_m2crypto_wrap.c(9511) : error C2037: left of 'num' specifies undefined struct/union 'stack_st'
    SWIG/_m2crypto_wrap.c(9531) : error C2037: left of 'num' specifies undefined struct/union 'stack_st'
    SWIG/_m2crypto_wrap.c(9560) : error C2037: left of 'data' specifies undefined struct/union 'stack_st'
    SWIG/_m2crypto_wrap.c(9580) : error C2037: left of 'data' specifies undefined struct/union 'stack_st'
    SWIG/_m2crypto_wrap.c(9609) : error C2037: left of 'sorted' specifies undefined struct/union 'stack_st'
    SWIG/_m2crypto_wrap.c(9629) : error C2037: left of 'sorted' specifies undefined struct/union 'stack_st'
    SWIG/_m2crypto_wrap.c(9658) : error C2037: left of 'num_alloc' specifies undefined struct/union 'stack_st'
    SWIG/_m2crypto_wrap.c(9678) : error C2037: left of 'num_alloc' specifies undefined struct/union 'stack_st'
    SWIG/_m2crypto_wrap.c(9706) : error C2037: left of 'comp' specifies undefined struct/union 'stack_st'
    SWIG/_m2crypto_wrap.c(9726) : error C2037: left of 'comp' specifies undefined struct/union 'stack_st'
    SWIG/_m2crypto_wrap.c(9738) : error C2027: use of undefined type 'stack_st'
            C:\Program Files\OpenSSL-Win64\include\openssl/stack.h(17) : see declaration of 'stack_st'
    SWIG/_m2crypto_wrap.c(9969) : warning C4090: 'function' : different 'const' qualifiers
    SWIG/_m2crypto_wrap.c(9969) : warning C4028: formal parameter 1 different from declaration
    SWIG/_m2crypto_wrap.c(10372) : error C2037: left of 'stack' specifies undefined struct/union 'stack_st_OPENSSL_STRING'
    SWIG/_m2crypto_wrap.c(10392) : error C2037: left of 'stack' specifies undefined struct/union 'stack_st_OPENSSL_STRING'
    SWIG/_m2crypto_wrap.c(10404) : error C2027: use of undefined type 'stack_st_OPENSSL_STRING'
            C:\Program Files\OpenSSL-Win64\include\openssl/safestack.h(159) : see declaration of 'stack_st_OPENSSL_STRING'
    SWIG/_m2crypto_wrap.c(10452) : error C2037: left of 'stack' specifies undefined struct/union 'stack_st_OPENSSL_BLOCK'
    SWIG/_m2crypto_wrap.c(10472) : error C2037: left of 'stack' specifies undefined struct/union 'stack_st_OPENSSL_BLOCK'
    SWIG/_m2crypto_wrap.c(10484) : error C2027: use of undefined type 'stack_st_OPENSSL_BLOCK'
            C:\Program Files\OpenSSL-Win64\include\openssl/safestack.h(167) : see declaration of 'stack_st_OPENSSL_BLOCK'
    SWIG/_m2crypto_wrap.c(23269) : warning C4244: '=' : conversion from 'Py_ssize_t' to 'int', possible loss of data
    SWIG/_m2crypto_wrap.c(25933) : warning C4244: '=' : conversion from 'Py_ssize_t' to 'int', possible loss of data
    error: command 'C:\\Users\\waydaws\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd
64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python27\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0]
= '"'"'c:\\temp\\pip-install-shzxap\\M2Crypto\\setup.py'"'"'; __file__='"'"'c:\\temp\\pip-install-shzxap\\M2Crypto\\setup.py'
"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(c
ompile(code, __file__, '"'"'exec'"'"'))' install --record 'c:\temp\pip-record-xygj76\install-record.txt' --single-version-ext
ernally-managed --compile Check the logs for full command output.

C:\spiderfoot>

**Comment by bcoles** [comment]
What version of Python 2.7 are you using? I know someone has had issues with Python 2.7.6, which was resolved by upgrading to Python 2.7.12.

Personally, I'd recommend not using Windows.
The good news is that the M2Crypto requirement may be dropped as a dependency in the future.

**Comment by waydaws** [comment]
Thanks for the reply.  It's version 2.7.16 (64 bit).  I have to use this windows server because it's one that the team already has, and won't need a request for new resources.  It also has decent RAM and Diskspace to use. 

I did find out that installing M2 Crypto on windows doesn't build.  People had previously recommended getting around it by using pip to install M2Crypto-x.xx.x-cpxx-cp2xxm-win_amd64.whl wheel from appveyor (pip install https://ci.appveyor.com/api/buildjob...), but AppVeyor deletes artifacts older than 6 months automatically, and the wheels are now gone.

**Comment by smicallef** [comment]
M2Crypto isn't needed anymore, so this can be closed.
