### ISSUE TITLE
Debian py2exe issue on install

### ISSUE THREAD

**Issue by hwac121** [smicallef/spiderfoot#407]
LINUX Mint "Tina" | 64bit Intel System
------------------------------------------------------------
setup.py will NOT run. py2exe is unable to be found or installed, thus setup.py cannot run.
I have installed this and used it on Kali, Cain, Parrot Security OS, and Ubuntu with no problems. All debian frameworks using Mate with similar setups.

Love this app but I am on the verge of trashing it from my pentesting toolkit forever. Is there anything I can do to get this setup.py to run? 

My opinion from everything I have read py2exe is a PITA to use in any situation. I would find an alternative...

**Comment by bcoles** [comment]
Py2exe is not required. Nor is `setup.py`.

Ensuring you're using Python 2.7.

```
sudo apt-get install python-dev
sudo apt-get install swig
sudo apt-get install python-setuptools
sudo pip2.7 install -r requirements.txt
```

You'll likely also need some combination of:

* libssl-dev
* python-openssl

**Comment by smicallef** [comment]
Closing this as py2exe has been dropped in the latest release.
