### ISSUE TITLE
Getting error for openxmlib

### ISSUE THREAD

**Issue by asantoshka** [smicallef/spiderfoot#456]
Critical Start-up Failure: No module named openxmllib
=================================
It appears you are missing a module required for SpiderFoot
to function. Please refer to the documentation for the list
of dependencies and install them.

Python modules required are: 
 - netaddr
 - dns
 - cherrypy
 - mako
 - socks
 - whois
 - OpenSSL
 - PyPDF2
 - openxmllib
 - stem
 - bs4
 - gexf
 - phonenumbers
 - ipaddr
 - ipwhois

****************************************************************
Please note that if you are seeing this after doing a git pull
then you just need to do a `pip install -r requirements.txt` as
dependencies previously bundled with SpiderFoot are now
unbundled.
****************************************************************

**Comment by jayPhantomic** [comment]
Add openxmllib to requirements.txt

**Comment by asantoshka** [comment]
Thanks..It worked for me (y)
