### ISSUE TITLE
[Suggestion] Can export files be named for their scan?

### ISSUE THREAD

**Issue by NetwarSystem** [smicallef/spiderfoot#458]
How difficult would it be to have the export file option grab the scan name instead of just using Spiderfoot.csv or whatever?

I want to drop scan results into Open Semantic Search, having a disciplined naming scheme would be invaluable.

**Comment by bcoles** [comment]
You could probably create the filename programmatically if you're using `sfcli`.

However, I agree that using the scan name would be useful for the web interface.

I've created a PR (#494) to automatically generate the filename for JSON exports in the form of `<scan name>-SpiderFoot.json`.

CSV is the devil, and I'm not interested in dealing with it.
