### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by pretech86** [smicallef/spiderfoot#460]
It appears you are missing a module required for SpiderFoot
to function. Please refer to the documentation for the list
of dependencies and install them.

Python modules required are: 
 - netaddr
 - dns
 - cherrypy
 - mako
 - socks
 - whois
 - OpenSSL
 - PyPDF2
 - openxmllib
 - stem
 - bs4
 - gexf
 - phonenumbers
 - ipaddr
 - ipwhois

****************************************************************
Please note that if you are seeing this after doing a git pull
then you just need to do a `pip install -r requirements.txt` as
dependencies previously bundled with SpiderFoot are now
unbundled.

**Comment by exigentcircumstance** [comment]
This should solve your issue...it did for me.

sudo pip install openxmllib

**Comment by xiaaru** [comment]
same thing on Kali Linux 

Critical Start-up Failure: No module named cherrypy
=================================
It appears you are missing a module required for SpiderFoot
to function. Please refer to the documentation for the list
of dependencies and install them.

Python modules required are: 
 - netaddr
 - dns
 - cherrypy
 - mako
 - socks
 - whois
 - OpenSSL
 - PyPDF2
 - openxmllib
 - stem
 - bs4
 - gexf
 - phonenumbers
 - ipaddr
 - ipwhois

****************************************************************
Please note that if you are seeing this after doing a git pull
then you just need to do a `pip install -r requirements.txt` as
dependencies previously bundled with SpiderFoot are now
unbundled.
****************************************************************

**Comment by smicallef** [comment]
Master branch should have all the fixes necessary since the move to Python 3.
