### ISSUE TITLE
Missing deps in Dockerfile

### ISSUE THREAD

**Issue by dmikhev** [smicallef/spiderfoot#461]
Dockerfile has missing some deps for Pillow and Docker image can`t build.
Fix: add missing deps in "RUN" section of Dockerfile.
Missing deps are: jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev

Correct Dockerfile:
# Pull the base image.
FROM alpine:latest
COPY requirements.txt .

# Run everything as one command so that only one layer is created
RUN apk --update add --no-cache --virtual build-dependencies gcc git curl py2-pip swig jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev tcl-dev libxml2-dev libxslt-dev libffi-dev gcc musl-dev libgcc openssl-dev curl \
        tinyxml-dev python2-dev musl-dev openssl-dev libffi-dev libxslt-dev \
    && apk --update --no-cache add python2 musl openssl libxslt tinyxml \
    && pip --no-cache-dir install wheel \
    && pip --no-cache-dir install -r requirements.txt \
    && addgroup spiderfoot \
    && adduser -G spiderfoot -h /home/spiderfoot -s /sbin/nologin \
               -g "SpiderFoot User" -D spiderfoot \
    && rmdir /home/spiderfoot \
    && cd /home \
    && curl -sSL https://github.com/smicallef/spiderfoot/archive/master.tar.gz \
       | tar -v -C /home -xz \
    && mv /home/spiderfoot-master /home/spiderfoot \
    && chown -R spiderfoot:spiderfoot /home/spiderfoot \
    && apk del --purge build-dependencies \
    && rm -rf /var/cache/apk/* \
    && rm -rf /root/.cache

USER spiderfoot
WORKDIR /home/spiderfoot

EXPOSE 5001

# Run the application.
ENTRYPOINT ["/usr/bin/python"]
CMD ["./sf.py", "0.0.0.0:5001"]

**Comment by ioscanner** [comment]
What you posted worked to get it installed, but when I tried to start the docker it get this:

Traceback (most recent call last):
  File "./sf.py", line 176, in <module>
    mod = __import__('modules.' + modName, globals(), locals(), [modName])
  File "/home/spiderfoot/modules/sfp_filemeta.py", line 17, in <module>
    import pptx
  File "/usr/lib/python2.7/site-packages/pptx/__init__.py", line 14, in <module>
    from pptx.api import Presentation  # noqa
  File "/usr/lib/python2.7/site-packages/pptx/api.py", line 15, in <module>
    from .package import Package
  File "/usr/lib/python2.7/site-packages/pptx/package.py", line 14, in <module>
    from .parts.image import Image, ImagePart
  File "/usr/lib/python2.7/site-packages/pptx/parts/image.py", line 13, in <module>
    import Image as PIL_Image
ImportError: No module named Image

I tried to add PIllow to the requirement.txt file, and rebuild, but that didn't seem to fix it.

**Comment by smicallef** [comment]
Master branch should have all the fixes necessary since the move to Python 3.
