### ISSUE TITLE
Critical Start-up Failure: No module named cStringIO

### ISSUE THREAD

**Issue by Singnusit** [smicallef/spiderfoot#462]
Hello
I'm using Windows 10.
I'm stuck on the next script. I don't see a way out of it.
-----
Critical Start-up Failure: No module named 'cStringIO'
=================================
It appears you are missing a module required for SpiderFoot
to function. Please refer to the documentation for the list
of dependencies and install them.

Python modules required are:
 - netaddr
 - dns
 - cherrypy
 - mako
 - socks
 - whois
 - OpenSSL
 - PyPDF2
 - openxmllib
 - stem
 - bs4
 - gexf
 - phonenumbers
 - ipaddr
 - ipwhois

****************************************************************
Please note that if you are seeing this after doing a git pull
then you just need to do a `pip install -r requirements.txt` as
dependencies previously bundled with SpiderFoot are now
unbundled.
****************************************************************
-----
I understood that cStringIO doesn't exist anymore but I can't get around this problem.
Do you have a solution, please ?
Thank you

Sincerely

**Comment by smicallef** [comment]
Master branch should have all the fixes necessary since the move to Python 3.
