### ISSUE TITLE
Final release issue

### ISSUE THREAD

**Issue by hwac121** [smicallef/spiderfoot#471]
Debian - Parrot Security OS (latest version)
Dell laptop 64bit
--------------------------------------------------------------
python3 sf.py 
Traceback (most recent call last):
  File "sf.py", line 21, in <module>
    import cherrypy
ModuleNotFoundError: No module named 'cherrypy'

**Comment by hwac121** [comment]
Old version worked great for me, new version not at all.

**Comment by hwac121** [comment]
Yeah this just is not working at all, and I can't even roll back to the old version I tried. This used to work beautifully, I even did a tutorial on it in my youtube channel but this is just plain broken now. missing all kids of modules, errors, etc. Not very happy, I love this application you developed. Anyway, going to shutup now until you have time to reply...

**Comment by smicallef** [comment]
You definitely did a `pip3 install -r requirements.txt` ? Note that it needs to be done with `pip3`, not `pip`.

**Comment by packetvitality** [comment]
Having some issues with 3.0 as well. 
1) Downloaded package from Github
2) python sf.py -l 127.0.0.1:5001 (don't have python 2.x installed)
Missing cherrypy
3) pip install -r requirements.txt
4) Web service up
5) Run a scan
6) Results page hangs
![image](https://user-images.githubusercontent.com/45752781/73202133-a7878e00-40f7-11ea-9ba4-4f90b438221a.png)
7) Read your note about pip3, ran pip3 install -r requirements (all requirements showed as satisfied)
8) Tried restarting a couple times, can't see scan results. Tried waiting a while to see if they eventually show, maybe after the scan completes but no luck. 

Let me know if there is anything I can send that would help understand better.

**Comment by smicallef** [comment]
Yes, doing pip install won't work, it has to be pip3. Since now you've progressed and are stuck at a different point (indicating there is no issue starting SpiderFoot wrt Python dependencies) I suggest deleting the `spiderfoot.db` file and running SpiderFoot again.

**Comment by packetvitality** [comment]
Thanks for the quick reply.

I gave that a try and no luck. Also just deleted the whole folder and unzipped a new copy, no luck either. It shows the Scans tab loading as soon as I open the web page prior to running any scans. After running a scan it looks the same, no results.

![image](https://user-images.githubusercontent.com/45752781/73203826-0ac6ef80-40fb-11ea-9652-1f14c7b04b4f.png)

**Comment by smicallef** [comment]
Strange.. what version of Python are you using?

**Comment by packetvitality** [comment]
Python 3.6.5

**Comment by smicallef** [comment]
That's more or less the version I'm using so it's not that in this case. Could you enable the Javascript debugger in your browser and see if there are any Javascript errors while loading the page? Could you also try your browser in Private/Incognito mode to ensure no cache is being used from the previous sessions?

**Comment by packetvitality** [comment]
This is what I am seeing, hope I got what you were looking for.
Refused to execute script from '<URL>' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
127.0.0.1/:1 Refused to execute script from 'http://127.0.0.1:5001/static/js/spiderfoot.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
127.0.0.1/:1 Refused to execute script from 'http://127.0.0.1:5001/static/js/viz.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
127.0.0.1/:1 Refused to execute script from 'http://127.0.0.1:5001/static/js/jquery.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
127.0.0.1/:1 Refused to execute script from 'http://127.0.0.1:5001/static/js/bootstrap.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
(index):1 Refused to execute script from 'http://127.0.0.1:5001/static/js/jquery.tablesorter.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
(index):1 Refused to execute script from 'http://127.0.0.1:5001/static/js/d3.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
(index):95 Uncaught ReferenceError: sf is not defined
    at (index):95
(anonymous) @ (index):95
(index):205 Uncaught ReferenceError: sf is not defined
    at showlist ((index):205)
    at (index):324

![image](https://user-images.githubusercontent.com/45752781/73208518-d3a90c00-4103-11ea-91b5-9ba96a926ec3.png)

**Comment by smicallef** [comment]
Do you have some special browser config or plugins? I'm using both FF and Chrome with no such error.

**Comment by packetvitality** [comment]
I'm using Brave as my browser, turned off blockers etc for the page. Tried FF and Edge as well.

![image](https://user-images.githubusercontent.com/45752781/73209221-099ac000-4105-11ea-8487-54dfa80b952f.png)

**Comment by packetvitality** [comment]
I installed in fresh VM and everything worked as expected. Must be something obscure on my endpoint that I am missing. If I figure out what it is I'll post the resolution.

Sorry for the trouble.

**Comment by M3ikShizuka** [comment]
> This is what I am seeing, hope I got what you were looking for.
> Refused to execute script from '' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
> 127.0.0.1/:1 Refused to execute script from 'http://127.0.0.1:5001/static/js/spiderfoot.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
> 127.0.0.1/:1 Refused to execute script from 'http://127.0.0.1:5001/static/js/viz.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
> 127.0.0.1/:1 Refused to execute script from 'http://127.0.0.1:5001/static/js/jquery.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
> 127.0.0.1/:1 Refused to execute script from 'http://127.0.0.1:5001/static/js/bootstrap.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
> (index):1 Refused to execute script from 'http://127.0.0.1:5001/static/js/jquery.tablesorter.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
> (index):1 Refused to execute script from 'http://127.0.0.1:5001/static/js/d3.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
> (index):95 Uncaught ReferenceError: sf is not defined
> at (index):95
> (anonymous) @ (index):95
> (index):205 Uncaught ReferenceError: sf is not defined
> at showlist ((index):205)
> at (index):324
> 
> ![image](https://user-images.githubusercontent.com/45752781/73208518-d3a90c00-4103-11ea-91b5-9ba96a926ec3.png)

I got the same problem.

**Comment by hwac121** [comment]
Hello, original author here: pip or pip3 makes no difference...I get the exact same error I originally posted. Won't install, therefore can't run it at all...wish I had not tried to upgrade and left my working version alone...

**Comment by hwac121** [comment]
In fact when I try pip3 (which is installed) I get this:

Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3098, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3082, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3111, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 575, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 588, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip==19.3.1' distribution was not found and is required by the application

**Comment by smicallef** [comment]
What Linux distribution are you having this issue on?

**Comment by hwac121** [comment]
Hi, thanks for responding so quickly. =)
I am using Parrot Security OS/ Debian - Latest stable release

**Comment by smicallef** [comment]
Something is very odd with your set up. I see you're using pip3 but if you look at the errors you can see it's still making reference to Python 2.7.

**Comment by hwac121** [comment]
Trust me that didn't go unnoticed to me either... ideas?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by hwac121** [comment]
> Something is very odd with your set up. I see you're using pip3 but if you look at the errors you can see it's still making reference to Python 2.7.

So, just to get you updated - since you also noted the strangeness with my Python I thought "Ok, let me check this out I'm not the only one seeing this oddness". It turns out due to some sort of error there are parts of 3 installations that are hung in apt and will not install, in turn causing 2 libraries not to upgrade. Not sure what is the singular culprit that started it all but the easiest thing for me to do is just format and reinstall. Luckily I keep all my regular apps I use for work on an external HDD for just such a situation to quickly reinstall. Thanks for all your help, I am sure after this it will be working as normal again in no time.  =)
