### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by l0x2a** [smicallef/spiderfoot#475]
While trying to scan a whole class c netblock (e.g. a.b.c.d/24) I ran into this error:

Unhandled exception (TypeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/root/Tools/spiderfoot/sfscan.py", line 186, in startScan\n    newTarget = mod.enrichTarget(target)\n', '  File "/root/Tools/spiderfoot/modules/sfp_dnsresolve.py", line 57, in enrichTarget\n    ret = self.sf.resolveTargets(target, self.opts[\'validatereverse\'])\n', '  File "/root/Tools/spiderfoot/sflib.py", line 1020, in resolveTargets\n    if ipaddr in chk:\n', "TypeError: argument of type 'NoneType' is not iterable\n"]

I was using the webui, started in a virtual python3 env with all requirements installed.

**Comment by smicallef** [comment]
Thanks for reporting this, it's now fixed on master and the v3.1 branch.
