### ISSUE TITLE
Move config files and project files to subdirectory to save them using docker volume

### ISSUE THREAD

**Issue by sidahmed-malaoui** [smicallef/spiderfoot#478]
If you move config files and project files to a sub directory (let's call it for example `data`), it would be easier to save application state by using docker volumes this way :
```bash
docker volume create spiderfoot-vol
docker run -v spiderfoot-vol:/home/spiderfoot/data -d spiderfoot
```
This time, we can save the application state (configuration and projects) each time we launch the docker container.

PS : Your tool rocks, I'm really thankful for this wonderful work.

**Comment by smicallef** [comment]
Have you tried using the latest Dockerfile for meeting this requirement?

**Comment by sidahmed-malaoui** [comment]
Yes, and it's working now @smicallef . Thank you for implementing this dude

**Comment by smicallef** [comment]
Credit goes to @steve-bate!
