### ISSUE TITLE
Error saving configuration over the web

### ISSUE THREAD

**Issue by logicfish** [smicallef/spiderfoot#479]
> Processing one or more of your inputs failed: the JSON object must be str, not 'bytes'

**Comment by Tejaswgupta** [comment]
Please tell the steps to replicate the issue.

**Comment by nil0x42** [comment]
Hi, i just got the same issue on master branch (HEAD f4f674a834384410e09dab63a81f7c8aee57121c)

While trying to change the Storage option "Maximum bytes to store for any piece of information retreived (0 = unlimited.)" from 1024 to 10240.
