### ISSUE TITLE
Error messages 

### ISSUE THREAD

**Issue by awtsuritacuna** [smicallef/spiderfoot#489]
Hello Friends from SpiderFoot.

I hope that this email finds you guys well, the reason for this email is to ask for assistance about a couple of error messages that I get when using your application, the first is when using the the web application to perform a search I get the following  message:
"Form incomplete.
Please go back and try again. If you're pretty sure this is a bug, please contact us"

The second one is when I use the CLI  app that  I get the following error message:
[*] Version 3.0.
[!] Failed communicating with server: HTTPConnectionPool(host='127.0.0.1', port=5001): Max retries exceeded with url: /ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4bb1874090>: Failed to establish a new connection: [Errno 111] Connection refused'))
[*] Loaded previous command histor

I performed a search in github about it and found some references but I was not able to find a solution, so I will like to know if you guys could please point me to the right direction I will really appreciate it, I am a big fan of this tool and I will like to be able to keep using it.

This is the information that I found:
spiderfoot/dyn/error.tmpl
<%include file="HEADER.tmpl"/>
<div class="alert alert-error">
<h4>${message}</h4>
<br><br>
Please go back and try again. If you're pretty sure this is a bug, please <a href='mailto:support@spiderfoot.io'>contact us</a>
</div>
<%include file="FOOTER.tmpl"/>
https://github.com/smicallef/spiderfoot/blob/229a8f4c9886d72951c3c4624db88f2ca7c1e395/dyn/error.tmpl

I want to thank you in advance for your help.

Greetings from Beautiful Costa Rica.

**Comment by bcoles** [comment]
> The second one is when I use the CLI app that I get the following error message:
> [_] Version 3.0. [!] Failed communicating with server: HTTPConnectionPool(host='127.0.0.1', port=5001): Max retries exceeded with url: /ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4bb1874090>: Failed to establish a new connection: [Errno 111] Connection refused')) [_] Loaded previous command histor

`sfcli` leverages the web interface and requires the web interface to be running.

Be default `sfcli` attempts to connect to `http://127.0.0.1:5001`. You can specify a different URL using the `-s` option for `sfcli` :

```
  -s URL       Connect to SpiderFoot server on URL. By default, a connection
               to http://127.0.0.1:5001 will be attempted.
```

For example:

```
[2020-02-25 00:17:57] root@kali:~/Desktop/spiderfoot# > ./sfcli.py 
 
  _________      .__    .___          ___________            __  
 /   _____/_____ |__| __| _/__________\_   _____/___   _____/  |_ 
 \_____  \\____ \|  |/ __ |/ __ \_  __ \    __)/  _ \ /  _ \   __\
 /        \  |_> >  / /_/ \  ___/|  | \/     \(  <_> |  <_> )  |  
/_______  /   __/|__\____ |\___  >__|  \___  / \____/ \____/|__|  
        \/|__|           \/    \/          \/                     
                Open Source Intelligence Automation.
                by Steve Micallef | @spiderfoot

[*] Version 3.0.
[!] Failed communicating with server: HTTPConnectionPool(host='127.0.0.1', port=5001): Max retries exceeded with url: /ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4b375c0850>: Failed to establish a new connection: [Errno 111] Connection refused',))
[*] Loaded previous command history.
[*] Type 'help' or '?'.
sf> 
```

```
[2020-02-25 00:19:08] root@kali:~/Desktop/spiderfoot# > lsof -i :5001  # nothing listening
```

Start SpiderFoot (in another terminal):

```
[2020-02-25 00:19:27] root@kali:~/Desktop/spiderfoot# > python3 ./sf.py -l 127.0.0.1:5001
Starting web server at http://127.0.0.1:5001 ...


*************************************************************
 Use SpiderFoot by starting your web browser of choice and 
 browse to http://127.0.0.1:5001
*************************************************************


[25/Feb/2020:00:19:31] ENGINE Listening for SIGTERM.
[25/Feb/2020:00:19:31] ENGINE Listening for SIGHUP.
[25/Feb/2020:00:19:31] ENGINE Listening for SIGUSR1.
[25/Feb/2020:00:19:31] ENGINE Bus STARTING
[25/Feb/2020:00:19:31] ENGINE Serving on http://127.0.0.1:5001
[25/Feb/2020:00:19:31] ENGINE Bus STARTED
127.0.0.1 - - [25/Feb/2020:00:19:35] "GET /ping HTTP/1.1" 200 18 "" "SpiderFoot-CLI/3.0"
127.0.0.1 - - [25/Feb/2020:00:19:35] "GET /modules HTTP/1.1" 200 18513 "" "SpiderFoot-CLI/3.0"
127.0.0.1 - - [25/Feb/2020:00:19:35] "GET /eventtypes HTTP/1.1" 200 6999 "" "SpiderFoot-CLI/3.0"
```

`sfcli` should now connect successfully:

```
[2020-02-25 00:19:32] root@kali:~/Desktop/spiderfoot# > ./sfcli.py 
 
  _________      .__    .___          ___________            __  
 /   _____/_____ |__| __| _/__________\_   _____/___   _____/  |_ 
 \_____  \\____ \|  |/ __ |/ __ \_  __ \    __)/  _ \ /  _ \   __\
 /        \  |_> >  / /_/ \  ___/|  | \/     \(  <_> |  <_> )  |  
/_______  /   __/|__\____ |\___  >__|  \___  / \____/ \____/|__|  
        \/|__|           \/    \/          \/                     
                Open Source Intelligence Automation.
                by Steve Micallef | @spiderfoot

[*] Version 3.0.
[*] Server http://127.0.0.1:5001 responding.
[*] Loaded previous command history.
[*] Type 'help' or '?'.
sf> 
```

**Comment by bcoles** [comment]
> when using the the web application to perform a search I get the following message:
> "Form incomplete.
> Please go back and try again. If you're pretty sure this is a bug, please contact us"

How are you submitting your scan?

`Form incomplete` appears in the following locations in `sfwebui.py` :

```python
        if scanname == "" or scantarget == "":
            if not cli:
                return self.error("Form incomplete.")
            else:
                return json.dumps(["ERROR", "Incorrect usage."])

        if typelist == "" and modulelist == "" and usecase == "":
            if not cli:
                return self.error("Form incomplete.")
            else:
                return json.dumps(["ERROR", "Incorrect usage."])
```

This implies you've specified incorrect options.... somehow. We would need more information to know what the problem is. Try restarting Spiderfoot.

Is this a new Spiderfoot installation, or have you upgraded an existing Spiderfoot install ? If you've upgraded, you may need to clear your database, as there were some large changes in version 3.0.
