### ISSUE TITLE
Line 356 - syntaxerror

### ISSUE THREAD

**Issue by citroen510** [smicallef/spiderfoot#504]
Hello.

After installing pip and Spiderfoot in Ubuntu, when introducing the command "python sf.py" in the terminal, this is the result:

File "sf.py", line 356
print ("[", end=' ')
                     ^
SyntaxError: invalid syntax

And I cannot launch Spiderfoot.
Thanks for any help.
C.

**Comment by bcoles** [comment]
Spiderfoot requires Python3.

```sh
python3 ./sf.py -l 127.0.0.1:5001
```

Ensure you've also installed the required dependencies:

```sh
pip3 install -r requirements.txt
```

**Comment by citroen510** [comment]
Hello.

I installed python 3.6.9 and pip3.
Then I wrote "python 3.6.9 sp.fy".
It says: 
> python: can't open file '3.6.9': [Errno 2] No such file or directory

I also tried with python 3 sp.fy
Thanks.

**Comment by citroen510** [comment]
And after changing some things, it reads:
sf.py error: unrecognized arguments: -1 127.0.0.1:5001
I will try to resume tomorrow :)
C.

**Comment by bcoles** [comment]
Spiderfoot requires Python3.

```sh
python3 ./sf.py -l 127.0.0.1:5001
```

Ensure you've also installed the required dependencies:

```sh
pip3 install -r requirements.txt
```

**Comment by citroen510** [comment]
Hello.
Yes, you told me that. But it does not work.
Best,
C.

**Comment by linxon** [comment]
.

**Comment by bcoles** [comment]
> 
> 
> Hello.
> Yes, you told me that. But it does not work.
> Best,
> C.

What commands are you using? What output do you get?

**Comment by Willyhelm** [comment]
> File "sf.py", line 356
print ("[", end=' ')
^
SyntaxError: invalid syntax

The same error for me too.
But with: `python3 ./sf.py -l 127.0.0.1:5001` it works.
Note that you also need to specify the port in the browser with `:5001`

**Comment by smicallef** [comment]
Looks like you're using `-1` (note that's a 1, i.e. number one) instead of the correct argument which is `-l` (a lower case letter L). Please re-open if it's something else.
