### ISSUE TITLE
WebUI Error

### ISSUE THREAD

**Issue by SF12-Studies** [smicallef/spiderfoot#511]
When I go to SpiderFoot WebUI by typing in console:

`sf -l 127.0.0.1:5000
`

and going to `127.0.0.1:5000` in browser.
Nothing seems to load up, then I go F12 and go to console tab, I see these errors:

`Refused to execute script from '<URL>' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
(index):1 Refused to execute script from 'http://127.0.0.1:5000/static/js/spiderfoot.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
(index):1 Refused to execute script from 'http://127.0.0.1:5000/static/js/viz.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
(index):1 Refused to execute script from 'http://127.0.0.1:5000/static/js/jquery.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
(index):1 Refused to execute script from 'http://127.0.0.1:5000/static/js/bootstrap.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
(index):1 Refused to execute script from 'http://127.0.0.1:5000/static/js/jquery.tablesorter.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
(index):1 Refused to execute script from 'http://127.0.0.1:5000/static/js/d3.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
(index):95 Uncaught ReferenceError: sf is not defined
    at (index):95
(index):205 Uncaught ReferenceError: sf is not defined
    at showlist ((index):205)
    at (index):324`

**Comment by bcoles** [comment]
Looks like a dupe of #471 which turned out to be a dependency issue.

Ensure you're using Python3 and have installed the appropriate dependencies with `pip3`.

```
pip3 install -r requirements.txt
python3 ./sf.py -l 127.0.0.1:3000
```

If the problem persists, you may have some like updating CherryPy:

```
pip3 install cherrypy --upgrade
```

**Comment by joeminicucci** [comment]
Same issue here. Checked dependencies, everything looks normal:
`PS C:\Tools\spiderfoot> python --version
Python 3.8.2
PS C:\Tools\spiderfoot> pip3 install -r .\requirements.txt
Requirement already satisfied: adblockparser>=0.7 in c:\python38\lib\site-packages (from -r .\requirements.txt (line 1)) (0.7)
Requirement already satisfied: dnspython>=1.16.0 in c:\python38\lib\site-packages (from -r .\requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: exifread>=2.1.2 in c:\python38\lib\site-packages (from -r .\requirements.txt (line 3)) (2.1.2)
Requirement already satisfied: CherryPy>=18.0 in c:\python38\lib\site-packages (from -r .\requirements.txt (line 4)) (18.6.0)
Requirement already satisfied: Mako>=1.0.4 in c:\python38\lib\site-packages (from -r .\requirements.txt (line 5)) (1.1.2)
Requirement already satisfied: beautifulsoup4>=4.4.1 in c:\python38\lib\site-packages (from -r .\requirements.txt (line 6)) (4.9.0)
Requirement already satisfied: lxml>=3.4.4 in c:\python38\lib\site-packages (from -r .\requirements.txt (line 7)) (4.5.0)
Requirement already satisfied: netaddr>=0.7.18 in c:\python38\lib\site-packages (from -r .\requirements.txt (line 8)) (0.7.19)
Requirement already satisfied: pysocks>=1.7.1 in c:\python38\lib\site-packages (from -r .\requirements.txt (line 9)) (1.7.1)
Requirement already satisfied: requests>=2.20.0 in c:\python38\lib\site-packages (from -r .\requirements.txt (line 10)) (2.23.0)
Requirement already satisfied: ipwhois==1.0.0 in c:\python38\lib\site-packages (from -r .\requirements.txt (line 11)) (1.0.0)
Requirement already satisfied: ipaddr>=2.2.0 in c:\python38\lib\site-packages (from -r .\requirements.txt (line 12)) (2.2.0)
Requirement already satisfied: phonenumbers>=8.10.2 in c:\python38\lib\site-packages (from -r .\requirements.txt (line 13)) (8.12.1)
Requirement already satisfied: pygexf>=0.2.2 in c:\python38\lib\site-packages (from -r .\requirements.txt (line 14)) (0.2.2)
Requirement already satisfied: PyPDF2>=1.26.0 in c:\python38\lib\site-packages (from -r .\requirements.txt (line 15)) (1.26.0)
Requirement already satisfied: stem>=1.7.1 in c:\python38\lib\site-packages (from -r .\requirements.txt (line 16)) (1.8.0)
Requirement already satisfied: python-whois>=0.7.1 in c:\python38\lib\site-packages (from -r .\requirements.txt (line 17)) (0.7.2)
Requirement already satisfied: future in c:\python38\lib\site-packages (from -r .\requirements.txt (line 18)) (0.18.2)
Requirement already satisfied: secure in c:\python38\lib\site-packages (from -r .\requirements.txt (line 19)) (0.2.1)
Requirement already satisfied: pyOpenSSL>=16.2.0 in c:\python38\lib\site-packages (from -r .\requirements.txt (line 20)) (19.1.0)
Requirement already satisfied: python-docx>=0.8.10 in c:\python38\lib\site-packages (from -r .\requirements.txt (line 21)) (0.8.10)
Requirement already satisfied: python-pptx>=0.6.18 in c:\python38\lib\site-packages (from -r .\requirements.txt (line 22)) (0.6.18)
Requirement already satisfied: networkx==2.3 in c:\python38\lib\site-packages (from -r .\requirements.txt (line 23)) (2.3)
Requirement already satisfied: cryptography>=2.5 in c:\python38\lib\site-packages (from -r .\requirements.txt (line 24)) (2.9)
Requirement already satisfied: jaraco.collections in c:\python38\lib\site-packages (from CherryPy>=18.0->-r .\requirements.txt (line 4)) (3.0.0)
Requirement already satisfied: portend>=2.1.1 in c:\python38\lib\site-packages (from CherryPy>=18.0->-r .\requirements.txt (line 4)) (2.6)
Requirement already satisfied: pywin32; sys_platform == "win32" in c:\python38\lib\site-packages (from CherryPy>=18.0->-r .\requirements.txt (line 4)) (227)
Requirement already satisfied: cheroot>=8.2.1 in c:\python38\lib\site-packages (from CherryPy>=18.0->-r .\requirements.txt (line 4)) (8.3.0)
Requirement already satisfied: more-itertools in c:\python38\lib\site-packages (from CherryPy>=18.0->-r .\requirements.txt (line 4)) (8.2.0)
Requirement already satisfied: zc.lockfile in c:\python38\lib\site-packages (from CherryPy>=18.0->-r .\requirements.txt (line 4)) (2.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\python38\lib\site-packages (from Mako>=1.0.4->-r .\requirements.txt (line 5)) (1.1.1)
Requirement already satisfied: soupsieve>1.2 in c:\python38\lib\site-packages (from beautifulsoup4>=4.4.1->-r .\requirements.txt (line 6)) (2.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\python38\lib\site-packages (from requests>=2.20.0->-r .\requirements.txt (line 10)) (2020.4.5.1)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\python38\lib\site-packages (from requests>=2.20.0->-r .\requirements.txt (line 10)) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\python38\lib\site-packages (from requests>=2.20.0->-r .\requirements.txt (line 10)) (1.25.9)
Requirement already satisfied: idna<3,>=2.5 in c:\python38\lib\site-packages (from requests>=2.20.0->-r .\requirements.txt (line 10)) (2.9)
Requirement already satisfied: six>=1.5.2 in c:\python38\lib\site-packages (from pyOpenSSL>=16.2.0->-r .\requirements.txt (line 20)) (1.14.0)
Requirement already satisfied: Pillow>=3.3.2 in c:\python38\lib\site-packages (from python-pptx>=0.6.18->-r .\requirements.txt (line 22)) (7.1.1)
Requirement already satisfied: XlsxWriter>=0.5.7 in c:\python38\lib\site-packages (from python-pptx>=0.6.18->-r .\requirements.txt (line 22)) (1.2.8)
Requirement already satisfied: decorator>=4.3.0 in c:\python38\lib\site-packages (from networkx==2.3->-r .\requirements.txt (line 23)) (4.4.2)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in c:\python38\lib\site-packages (from cryptography>=2.5->-r .\requirements.txt (line 24)) (1.14.0)
Requirement already satisfied: jaraco.text in c:\python38\lib\site-packages (from jaraco.collections->CherryPy>=18.0->-r .\requirements.txt (line 4)) (3.2.0)
Requirement already satisfied: jaraco.classes in c:\python38\lib\site-packages (from jaraco.collections->CherryPy>=18.0->-r .\requirements.txt (line 4)) (3.1.0)
Requirement already satisfied: tempora>=1.8 in c:\python38\lib\site-packages (from portend>=2.1.1->CherryPy>=18.0->-r .\requirements.txt (line 4)) (3.0.0)
Requirement already satisfied: jaraco.functools in c:\python38\lib\site-packages (from cheroot>=8.2.1->CherryPy>=18.0->-r .\requirements.txt (line 4)) (3.0.0)
Requirement already satisfied: setuptools in c:\python38\lib\site-packages (from zc.lockfile->CherryPy>=18.0->-r .\requirements.txt (line 4)) (41.2.0)
Requirement already satisfied: pycparser in c:\python38\lib\site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.5->-r .\requirements.txt (line 24)) (2.20)
Requirement already satisfied: pytz in c:\python38\lib\site-packages (from tempora>=1.8->portend>=2.1.1->CherryPy>=18.0->-r .\requirements.txt (line 4)) (2019.3)
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
PS C:\Tools\spiderfoot> pip3 install cherrypy --upgrade
Requirement already up-to-date: cherrypy in c:\python38\lib\site-packages (18.6.0)
Requirement already satisfied, skipping upgrade: cheroot>=8.2.1 in c:\python38\lib\site-packages (from cherrypy) (8.3.0)
Requirement already satisfied, skipping upgrade: jaraco.collections in c:\python38\lib\site-packages (from cherrypy) (3.0.0)
Requirement already satisfied, skipping upgrade: more-itertools in c:\python38\lib\site-packages (from cherrypy) (8.2.0)
Requirement already satisfied, skipping upgrade: portend>=2.1.1 in c:\python38\lib\site-packages (from cherrypy) (2.6)
Requirement already satisfied, skipping upgrade: pywin32; sys_platform == "win32" in c:\python38\lib\site-packages (from cherrypy) (227)
Requirement already satisfied, skipping upgrade: zc.lockfile in c:\python38\lib\site-packages (from cherrypy) (2.0)
Requirement already satisfied, skipping upgrade: jaraco.functools in c:\python38\lib\site-packages (from cheroot>=8.2.1->cherrypy) (3.0.0)
Requirement already satisfied, skipping upgrade: six>=1.11.0 in c:\python38\lib\site-packages (from cheroot>=8.2.1->cherrypy) (1.14.0)
Requirement already satisfied, skipping upgrade: jaraco.classes in c:\python38\lib\site-packages (from jaraco.collections->cherrypy) (3.1.0)
Requirement already satisfied, skipping upgrade: jaraco.text in c:\python38\lib\site-packages (from jaraco.collections->cherrypy) (3.2.0)
Requirement already satisfied, skipping upgrade: tempora>=1.8 in c:\python38\lib\site-packages (from portend>=2.1.1->cherrypy) (3.0.0)
Requirement already satisfied, skipping upgrade: setuptools in c:\python38\lib\site-packages (from zc.lockfile->cherrypy) (41.2.0)
Requirement already satisfied, skipping upgrade: pytz in c:\python38\lib\site-packages (from tempora>=1.8->portend>=2.1.1->cherrypy) (2019.3)
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.`

**Comment by SF12-Studies** [comment]
@bcoles It works now, thanks.
