### ISSUE TITLE
module sfp_apility needs updating

### ISSUE THREAD

**Issue by nelly113113** [smicallef/spiderfoot#513]
Auth0 has taken over, use "https://signals.api.auth0.com/v2.0/ip/" plus (i think) new api key for users?. headers stay the same.
ta

**Comment by bcoles** [comment]
What needs updating? I took a look at the [API documentation](https://apility.io/apidocs/) which doesn't appear to have changed.

**Comment by nelly113113** [comment]
True, nothing has been mentioned or altered in the docs, ther is a banner on the homepage "Apility.io was recently acquired by Auth0.
Please visit auth0.com/signals/ip to search an IP’s risk level. If you are an existing Apility.io customer please use dashboard.apility.io **until we turn off the service**."

**Comment by nelly113113** [comment]
I`m sure that it will be a while before auth0 knockout https://api.apility.net url if ever. The api keys provided by auth0 works with he current endpoint so yea no change.

**Comment by bcoles** [comment]
Thanks for the heads up. I guess we'll need to keep an eye on it.

[sfp_apility](https://github.com/smicallef/spiderfoot/blob/master/modules/sfp_apility.py) has some basic error checking (auth, connection failure, rate limiting). So hopefully the module will die gracefully if something changes, rather than continuing to send doomed queries.

**Comment by supashot** [comment]
AFAIK it's not possible to create an account and get an API key anymore on https://dashboard.apility.io/
The module will work only for users who previously registered.

**Comment by bcoles** [comment]
Apility is now fully dead. `apility.net` is available for registration if you want to hijack it.

![Apility](https://user-images.githubusercontent.com/434827/135064630-40e51e73-1838-4707-868a-13bcc8258e0a.png)

> The Apility.io and IP Signals APIs will be fully deprecated on Feb. 8, 2021.

https://auth0.com/blog/auth0-sunsets-signals/
