### ISSUE TITLE
Unhandled exception (JSONDecodeError) encountered during scan. Please report this as a bug:

### ISSUE THREAD

**Issue by 1scai** [smicallef/spiderfoot#515]
I have the following issues when running an all scan on the web ui:

Unhandled exception (JSONDecodeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/root/spiderfoot/sfscan.py", line 180, in startScan\n    mod.setup(self.ts.sf, self.ts.modconfig[modName])\n', '  File "/root/spiderfoot/modules/sfp_accounts.py", line 80, in setup\n    self.sites = json.loads(content)[\'sites\']\n', '  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads\n    return _default_decoder.decode(s)\n', '  File "/usr/lib/python3.7/json/decoder.py", line 340, in decode\n    raise JSONDecodeError("Extra data", s, end)\n', 'json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)\n']

i updated the sfscan file but i still get the same issue, any help would be appreciated. 

PS. i am a total noob

Thanks

**Comment by 1scai** [comment]
Ive narrowed down my error to trying to run a scan when using the account finder module. There might be others but i know for sure it aborts the scan and gives that error message.

**Comment by bcoles** [comment]
I think this has been fixed in 9b66eff6a83ffa0fbdf29677a6ec5d08f9c54803.

**Comment by smicallef** [comment]
Yeah, this happens when, for whatever reason, there's an issue downloading the WhatsMyName JSON file from Github, and so you end up with a corrupted cached file. As @bcoles points out, that's now been fixed.
