### ISSUE TITLE
"UnicodeEncodeError: 'gbk'

### ISSUE THREAD

**Issue by h4cnull** [smicallef/spiderfoot#516]
Unhandled exception (UnicodeEncodeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "E:\\Null\\Reconnaissance\\spiderfoot\\sfscan.py", line 151, in startScan\n    self.ts.sf.cachePut("internet_tlds", self.ts.config[\'_internettlds\'])\n', '  File "E:\\Null\\Reconnaissance\\spiderfoot\\sflib.py", line 430, in cachePut\n    fp.write(line)\n', "UnicodeEncodeError: 'gbk' codec can't encode character '\\u0627' in position 0: illegal multibyte sequence\n"]

**Comment by smicallef** [comment]
Should be fixed by the linked PR.
