### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec

### ISSUE THREAD

**Issue by scythe000** [smicallef/spiderfoot#530]
`Unhandled exception (UnicodeEncodeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "C:\\Windows\\System32\\spiderfoot\\sfscan.py", line 151, in startScan\n    self.ts.sf.cachePut("internet_tlds", self.ts.config[\'_internettlds\'])\n', '  File "C:\\Windows\\System32\\spiderfoot\\sflib.py", line 431, in cachePut\n    fp.write(line)\n', '  File "C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\\lib\\encodings\\cp1252.py", line 19, in encode\n    return codecs.charmap_encode(input,self.errors,encoding_table)[0]\n', "UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined>\n"]`

I'm running Windows 10 x64 Pro, Python 3.8 and PIP 20

**Comment by scythe000** [comment]
Not sure if this is the same issue:
`Scan [0F5AD00A] failed: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined>`

**Comment by smicallef** [comment]
Should be fixed by the linked PR.
