### ISSUE TITLE
Unable to start Spiderfoot server/scan.

### ISSUE THREAD

**Issue by Yashvendra** [smicallef/spiderfoot#545]
Hi Guys, 

I am using Ubuntu 18.04, after cloning the repository, I successfully installed the dependencies `pip3 install -r requirements.txt`. But when I try to run the server `python3 sf.py -l 127.0.0.1:5001`, my terminal just stucks there, neither the server starts nor it shows any output/error. 
When I press `ctrl + c` to exit, this error comes:
```
$ python3 ./sf.py -l 127.0.0.1:5001
^CTraceback (most recent call last):
  File "/home/yash/Documents/GIT/spiderfoot/sfdb.py", line 262, in __init__
    self.dbh.execute('SELECT COUNT(*) FROM tbl_scan_config')
sqlite3.OperationalError: no such table: tbl_scan_config

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yash/Documents/GIT/spiderfoot/sfdb.py", line 267, in __init__
    self.create()
  File "/home/yash/Documents/GIT/spiderfoot/sfdb.py", line 289, in create
    with self.dbhLock:
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./sf.py", line 173, in <module>
    dbh = SpiderFootDb(sfConfig, init=True)
  File "/home/yash/Documents/GIT/spiderfoot/sfdb.py", line 270, in __init__
    self.sf.error("Tried to set up the SpiderFoot database schema, but failed: " + e.args[0])
IndexError: tuple index out of range
```
Can you please tell me what is the issue.

**Comment by steve-bate** [comment]
I believe this is an unintended site-effect of adding multithread synchronization around the database access. I've submitted a PR #546 that should fix the problem.

**Comment by Yashvendra** [comment]
#546 It surely fixed the problem. Thanks @steve-bate 
![Screen Capture_select-area_20200612104130](https://user-images.githubusercontent.com/23001311/84468906-78844a00-ac9d-11ea-8562-c989cf69cfe0.jpg)

**Comment by smicallef** [comment]
Fix has been merged.

**Comment by Cyberjummy** [comment]
Running spiderfoot on Kali Linux, was able to install but got stuck at a point of scanning. I stopped it and restart only to  display the following 

Message: 'Failed to initialize database: Tried to set up the SpiderFoot database schema, but failed\nTraceback (most recent call last):\n  File "/home/kali/spiderfoot/spiderfoot/db.py", line 353, in __init__\n    self.dbh.execute(\'SELECT COUNT(*) FROM tbl_scan_config\')\nsqlite3.OperationalError: disk I/O error\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/kali/spiderfoot/spiderfoot/db.py", line 408, in create\n    self.dbh.execute(qry)\nsqlite3.OperationalError: disk I/O error\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/home/kali/spiderfoot/spiderfoot/db.py", line 358, in __init__\n    self.create()\n  File "/home/kali/spiderfoot/spiderfoot/db.py", line 422, in create\n    raise IOError("SQL error encountered when setting up database") from e\nOSError: SQL error encountered when setting up database\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/home/kali/spiderfoot/./sf.py", line 164, in main\n    dbh = SpiderFootDb(sfConfig)\n  File "/home/kali/spiderfoot/spiderfoot/db.py", line 360, in __init__\n    raise IOError("Tried to set up the SpiderFoot database schema, but failed") from e\nOSError: Tried to set up the SpiderFoot database schema, but failed'
Arguments: None
