### ISSUE TITLE
Error when running spiderfoot on Kali

### ISSUE THREAD

**Issue by stefaanbolle** [smicallef/spiderfoot#55]
I encounter below error when I want to run spiderfoot:

prompt# python ./sf.py
Traceback (most recent call last):
  File "./sf.py", line 113, in <module>
    sfModules[modName]['object'] = getattr(mod, modName)()
AttributeError: 'module' object has no attribute 'sfp_tcpportscan'

Anyone an idea how to solve?

**Comment by smicallef** [comment]
Please use the last packaged version rather than the version on github. I will try and have 2.2.1 released today which will have all the latest functionality available on github anyhow.
