### ISSUE TITLE
Attaching the -final to the version

### ISSUE THREAD

**Issue by masterkorp** [smicallef/spiderfoot#56]
Hello,

I am packaging spiderfoot on Archlinux [AUR](https://aur.archlinux.org/) and noticed that you always [append -final to the releases](https://github.com/smicallef/spiderfoot/releases).

I would like to confirm if you plan on appending the -final  on every submission. If so I would omit that on the package version.

Regards,
Alfredo Palhares

**Comment by smicallef** [comment]
Hi Alfredo,

Yes you can make that assumption.

Thanks,

Steve
