### ISSUE TITLE
Possibly error in recognizing human names (SF 2.3.0)

### ISSUE THREAD

**Issue by karlnapp-pb** [smicallef/spiderfoot#57]
I'm just testing Spiderfoot 2.3.0; it seems that <b>every</b> two subsequent words starting 
with an uppercase letter  are recognized as human name, e.g. on page hackers-playground.de "Aktuelle Nachrichten" (german for last news)

**Comment by smicallef** [comment]
Hi,

Yes the human names module is based around the English language for now. In the future I will add support for other languages.

Thanks,

Steve

**Comment by dieee** [comment]
Is it related to this?

['Traceback (most recent call last):\n', '  File "/home/user/sv/spiderfoot/spiderfoot-2.12/sfscan.py", line 265, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/home/user/sv/spiderfoot/spiderfoot-2.12/sflib.py", line 1527, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/user/sv/spiderfoot/spiderfoot-2.12/modules/sfp_fullcontact.py", line 151, in handleEvent\n    e = SpiderFootEvent("HUMAN_NAME", data[\'fullName\'], self.__name__, event)\n', "KeyError: 'fullName'\n"]

**Comment by dieee** [comment]
This happened when scanning a malicious mail but it was outlook
