### ISSUE TITLE
Suggest to use relative paths instead of absolute

### ISSUE THREAD

**Issue by miaoski** [smicallef/spiderfoot#58]
Hi.
Thanks for the cool system.
I'd like to use it within a reverse proxy, and found the absolute paths in dyn/* blocked my way.
Is there any plan to make it relative?  Thanks.

**Comment by smicallef** [comment]
Thanks for the pull request! I'll take a look this weekend and merge it.

**Comment by smicallef** [comment]
Merged

**Comment by JohanBGJohansson** [comment]
Might it be that the relative path's caused a situation where starting sf.py from another folder then where it located results in:
IOError: [Errno 2] No such file or directory: 'dyn/scanlist.tmpl' ??

Works fine if its initiated from its home folder, less so if the service is started from elsewhere.
