### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by jspc** [smicallef/spiderfoot#6]
So... Python 3 is starting to be used more and more and, more tellingly, being shipped as default on many Linux distros.

I have started a fork at https://github.com/jspc/spiderfoot/tree/python3 which works under python3 merely as a WIP. Now this repo has no tests written for it as far as I can see (which is bad anyway) so a simple smoke test is all I've been able to do.

Alongside the changes in this fork for Python3 there is also:
- Fixed the formatting and copy on the readme
- Fixed the use of DOS line breaks
- Usage of a `.gitignore` file.

The main reason for this fork: should this project not be using Python3? Why would it not use Python3?

**Comment by doxingme** [comment]
How is it low priority when the language is going to be essentially outdated next year... wouldnt it be better  to have just written it in Python3 anyway as to avoid having to change the code fully anyway?

**Comment by doxingme** [comment]
Why is that low priority when Py2 is going to be dead next year? It would be easier and honestly more time consuming to just rewrite it in Py3 and not worry about it till like Py4 or something. On top of that, most servers and Linux distros are using Py3 by default, so your program is far from just being outdated in the next year, it will essentially be dead. Lastly it doesn't even fit in with PEP8 standards making the code likely to be insecure and have a list of various bugs.

**Comment by bcoles** [comment]
@doxingme You can learn more about porting to Python3 here:

https://docs.python.org/3/howto/pyporting.html

You can learn more about PEP8 here:

https://www.python.org/dev/peps/pep-0008/

**Comment by doxingme** [comment]
@bcoles if youre trying to say something be straight up about it. no point in linking to shit.

**Comment by smicallef** [comment]
@doxingme if you look at the age of this issue, it goes back to 2013. I stand by my comment in saying that porting to Python 3 was a low priority back then. It's a higher priority now, and will probably happen within the next before Python 2 is EOL, but it remains a lower priority to getting support for additional data feeds and improving stability / reducing false positives. Furthermore, the main challenge to porting to Python 3 is in having the various third party library dependencies also support Python 3. I haven't checked if they all do recently, but last time I checked (admittedly over a year ago), a few didn't and there were no Python 3 alternatives.

So with regard to that and PEP8-compliance of the code base, I agree with the gist of @bcoles comment. The beauty of open source is that you can contribute to it any time, so if you feel strongly about it, any PR helping to move the code base to Python 3 would be happily accepted and highly appreciated.

**Comment by bcoles** [comment]
SpiderFoot now requires Python 3.
