### ISSUE TITLE
python3 starts spiderfoot in WebUI mode, can't connect with browser

### ISSUE THREAD

**Issue by AlanHowlett** [smicallef/spiderfoot#607]
in websploit/kali linux:
after apt-get updating...

~/spiderfoot$ python3 sf.py -l 127.0.0.1:5001
starting.... stuff
then nothing.
Browser using http and https return  "Unable to connect" msg

telnet 127.0.0.1 5001
connects
GET / HTTP/1.1  returns stuff, then connection closes

**Comment by AlanHowlett** [comment]
Also tried prefacing with nohup and postfixing &

**Comment by bcoles** [comment]
There's not enough information here to understand the issue.

> ~/spiderfoot$ python3 sf.py -l 127.0.0.1:5001
> starting.... stuff
> then nothing.

What is "stuff" ? Does this "stuff" look something like this?

```
# python3 ./sf.py -l 127.0.0.1:5001 
Starting web server at http://127.0.0.1:5001 ...


*************************************************************
 Use SpiderFoot by starting your web browser of choice and 
 browse to http://127.0.0.1:5001
*************************************************************


[25/Jun/2020:02:19:54] ENGINE Listening for SIGTERM.
[25/Jun/2020:02:19:54] ENGINE Listening for SIGHUP.
[25/Jun/2020:02:19:54] ENGINE Listening for SIGUSR1.
[25/Jun/2020:02:19:54] ENGINE Bus STARTING
[25/Jun/2020:02:19:54] ENGINE Serving on http://127.0.0.1:5001
[25/Jun/2020:02:19:54] ENGINE Bus STARTED
```

> Browser using http and https return "Unable to connect" msg

Perhaps your browser has a misconfigured proxy? Perhaps you've entered the incorrect URL? The correct URL when using `sf.py -l 127.0.0.1:5001` is `http://127.0.0.1:5001/`

> telnet 127.0.0.1 5001
> connects
> GET / HTTP/1.1 returns stuff, then connection closes

Was the "stuff" the expected "stuff" ?

**Comment by AlanHowlett** [comment]
Using correct URL.  Telnet was to test if I could reach it.  Port confirmed open with nmap. 
The "stuff' returned by telnet was HTML.  The telnet connection closes immediately after.

The expected result is the WebUI would return a splash page.  All I get is "Unable to connect.  Firefox can't establish a connection..."
