### ISSUE TITLE
TypeError in dnsresolve.

### ISSUE THREAD

**Issue by donfanning** [smicallef/spiderfoot#620]
Doing my part in bug reporting.

`Unhandled exception (TypeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/home/spiderfoot/sfscan.py", line 186, in startScan\n    newTarget = mod.enrichTarget(target)\n', '  File "/home/spiderfoot/modules/sfp_dnsresolve.py", line 57, in enrichTarget\n    ret = self.sf.resolveTargets(target, self.opts[\'validatereverse\'])\n', '  File "/home/spiderfoot/sflib.py", line 1020, in resolveTargets\n    if ipaddr in chk:\n', "TypeError: argument of type 'NoneType' is not iterable\n"]`

This would be against the: sfp_dnsresolve module.  Target was a /24 subnet but I've tried larger ones.. it was just the smallest before I decided to report.  Environment is Docker container built using repo Dockerfile.

**Comment by smicallef** [comment]
Could you try pulling from master? This bug was fixed some time ago.

**Comment by smicallef** [comment]
Actually, I've changed the Dockerfile to pull from master so everyone building from the Dockerfile gets the fix.
