### ISSUE TITLE
Spiderfoot Unhandled exception (PermissionError) 

### ISSUE THREAD

**Issue by abarracu** [smicallef/spiderfoot#633]
Hello,
doing my part in bug report, one scan didn't finish and it remains in status "ERROR-FAILED" with this error to report:

```Unhandled exception (PermissionError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/usr/share/spiderfoot/sflib.py", line 1783, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/usr/share/spiderfoot/modules/sfp_flickr.py", line 149, in handleEvent\n    emails = self.sf.parseEmails(str(bytes(photo).decode(\'unicode-escape\')))\n', "TypeError: 'str' object cannot be interpreted as an integer\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/usr/share/spiderfoot/sflib.py", line 1783, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/usr/share/spiderfoot/modules/sfp_crt.py", line 128, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/usr/share/spiderfoot/sflib.py", line 1785, in notifyListeners\n    f = open("sferror.log", "a")\n', "PermissionError: [Errno 13] Permission denied: 'sferror.log'\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/usr/share/spiderfoot/sflib.py", line 1783, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/usr/share/spiderfoot/modules/sfp_mnemonic.py", line 215, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/usr/share/spiderfoot/sflib.py", line 1785, in notifyListeners\n    f = open("sferror.log", "a")\n', "PermissionError: [Errno 13] Permission denied: 'sferror.log'\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/usr/share/spiderfoot/sflib.py", line 1783, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/usr/share/spiderfoot/modules/sfp_apility.py", line 211, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/usr/share/spiderfoot/sflib.py", line 1785, in notifyListeners\n    f = open("sferror.log", "a")\n', "PermissionError: [Errno 13] Permission denied: 'sferror.log'\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/usr/share/spiderfoot/sfscan.py", line 234, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/usr/share/spiderfoot/sflib.py", line 1785, in notifyListeners\n    f = open("sferror.log", "a")\n', "PermissionError: [Errno 13] Permission denied: 'sferror.log'\n"]```

The target was a domain as an another and I'm running Spiderfoot on Parrot OS updated to the last version

**Comment by bcoles** [comment]
You can wrap code in three backticks to format code for markdown. It makes it much easier to read.

The permission error `PermissionError` is raised due to being unable to write the `sferror.log` file, which is likely an issue with the way SpiderFoot is packaged on ParrotOS.

The root cause is here:

```
File "/usr/share/spiderfoot/modules/sfp_flickr.py", line 149, in handleEvent\n emails = self.sf.parseEmails(str(bytes(photo).decode(\'unicode-escape\')))\n', "TypeError: 'str' object cannot be interpreted as an integer\n"
```

This issue should befixed in `master`. Reviewing the [sfp_flickr](https://github.com/smicallef/spiderfoot/blob/master/modules/sfp_flickr.py) module source code shows `self.sf.parseEmails(str(bytes(photo).decode(\'unicode-escape\')))` is no longer used anywhere. It was patched on May 8th in b159a8fd92594e4e9700c6b8b3cb18ba34db22c4.

I'm guessing ParrotOS is using an older version, probably based on the 3.0 release. The next release 3.1 shouldn't be too far away.

**Comment by abarracu** [comment]
Nothing urgent so will wait for the 3.1 release. Thank you for the quick answer ;)

**Comment by bcoles** [comment]
> 
> 
> Nothing urgent so will wait for the 3.1 release. Thank you for the quick answer ;)

Thanks for the report.

Unfortunately there have been a bunch of changes in the core libraries between 3.0 and 3.1-pre, else I'd suggest simply dropping the `sfp_flickr.py` file from the git repo into your `modules/` folder to overwrite the existing module.

Fortunately, the new changes are for the best and the 3.1 release isn't far away.
