### ISSUE TITLE
Unhandled exception TypeError: instanceId is <class 'NoneType'>; expected str()

### ISSUE THREAD

**Issue by Istvan-at** [smicallef/spiderfoot#634]
Hi,
Installed SpiderFoot on a Debian VM (fresh pull from master), all requirements were installed without errors.
Tried to do a test scan of a domain name in "ALL" mode. Just after the modules were loaded, this error message showed itself:

`Unhandled exception (TypeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/home/istvan/spiderfoot/sfscan.py", line 264, in startScan\n    psMod.notifyListeners(rootEvent)\n', '  File "/home/istvan/spiderfoot/sflib.py", line 2531, in notifyListeners\n    if self.checkForStop():\n', '  File "/home/istvan/spiderfoot/sflib.py", line 2598, in checkForStop\n    scanstatus = self.__sfdb__.scanInstanceGet(self.__scanId__)\n', '  File "/home/istvan/spiderfoot/sfdb.py", line 597, in scanInstanceGet\n    raise TypeError("instanceId is %s; expected str()" % type(instanceId))\n', "TypeError: instanceId is <class 'NoneType'>; expected str()\n"]`

Thank you!

**Comment by bcoles** [comment]
Thanks. Looking into this now.

**Comment by bcoles** [comment]
I was able to reproduce this and have a patch pending. I'll provide the diff and PR shortly.

```
Unhandled exception (TypeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/root/Desktop/spiderfoot/sfscan.py", line 264, in startScan\n    psMod.notifyListeners(rootEvent)\n', '  File "/root/Desktop/spiderfoot/sflib.py", line 2531, in notifyListeners\n    if self.checkForStop():\n', '  File "/root/Desktop/spiderfoot/sflib.py", line 2598, in checkForStop\n    scanstatus = self.__sfdb__.scanInstanceGet(self.__scanId__)\n', '  File "/root/Desktop/spiderfoot/sfdb.py", line 597, in scanInstanceGet\n    raise TypeError("instanceId is %s; expected str()" % type(instanceId))\n', "TypeError: instanceId is <class 'NoneType'>; expected str()\n"]
```

**Comment by bcoles** [comment]
This diff should resolve your issue. You can apply the diff by copying it to a file in the root of the SpiderFoot directory, such as `filename.diff`, then run `git apply filename.diff`.

```diff
diff --git a/sfdb.py b/sfdb.py
index dfbd57d..b92303c 100644
--- a/sfdb.py
+++ b/sfdb.py
@@ -1115,7 +1115,7 @@ class SpiderFootDb:
         if not sfEvent.data:
             raise ValueError("sfEvent.data is empty")
 
-        if not isinstance(sfEvent.sourceEventhash, str):
+        if not isinstance(sfEvent.sourceEventHash, str):
             raise TypeError("sfEvent.sourceEventHash is %s; expected str()" % type(sfEvent.sourceEventHash))
 
         if not sfEvent.sourceEventHash:
diff --git a/sflib.py b/sflib.py
index 23068b3..0f0d730 100644
--- a/sflib.py
+++ b/sflib.py
@@ -2594,11 +2594,17 @@ class SpiderFootPlugin(object):
         Returns:
             bool
         """
+        if not self.__scanId__:
+            return False
 
         scanstatus = self.__sfdb__.scanInstanceGet(self.__scanId__)
-        if scanstatus != None:              
-            if scanstatus[5] == "ABORT-REQUESTED":
-                return True
+
+        if not scanstatus:
+            return False
+
+        if scanstatus[5] == "ABORT-REQUESTED":
+            return True
+
         return False
 
     def watchedEvents(self):
```

The patch is in PR #635, which will be merged after @smicallef reviews.
