### ISSUE TITLE
error in json structure

### ISSUE THREAD

**Issue by fastfire** [smicallef/spiderfoot#636]
The json structure produced in output, from the latest versions of Spiderfoot, does not seem correct.

**This is the command used:**
`sf.py -m sfp_abusech,sfp_abuseipdb,sfp_alienvault,sfp_alienvaultiprep,sfp_greensnowsfp_badipscom,sfp_blocklistde,sfp_botscout.py,sfp_cinsscore,sfp_cleantalk,sfp_cybercrimetracker,sfp_isc,sfp_nothink,sfp_fortinet,sfp_talosintel,sfp_threatcrowd,sfp_torexits,sfp_totalhash,sfp_virustotal,sfp_sorbs -s 217.28.98.112 -o json`

**This is the output produced with version 3.0:**
[{"generated": 1594320400, "type": "IP Address", "data": "217.28.98.112", "module": "SpiderFoot UI", "source": "217.28.98.112"}]

**This is the output produced with the latest version available today:**
{"generated": 1594319181, "type": "IP Address", "data": "217.28.98.112", "module": "SpiderFoot UI", "source": "217.28.98.112"}[]

**Comment by bcoles** [comment]
Confirmed. That does not look right at all.

**Comment by bcoles** [comment]
Thanks for reporting.

For what it is worth, you can still go to the web interface and export the scan in JSON format to get your output. It should be formatted correctly.

The formatting appears to be messed up only when using `sf.py` from the comamd line.

I'll take a look at this.

**Comment by bcoles** [comment]
Here's a simple patch in the interim. I didn't write the JSON logging code and I have no idea why this works:

```diff
diff --git a/sf.py b/sf.py
index 9124040..d54f83a 100755
--- a/sf.py
+++ b/sf.py
@@ -373,7 +373,7 @@ if __name__ == '__main__':
                     print('{0:30}{1}{2:45}{3}{4}{5}{6}'.format("Source", delim, "Type", delim, "Source Data", delim, "Data"))
 
         if args.o == "json":
-            print("[", end='')
+            print("[") #, end='')
 
         while True:
             info = dbh.scanInstanceGet(scanId)
```

**Comment by fastfire** [comment]
Thank you @bcoles !
