### ISSUE TITLE
Portscan_tcp not use TOR.

### ISSUE THREAD

**Issue by lprat** [smicallef/spiderfoot#638]
Hi,

Tor isnt use in portscan_tcp... Is this normal?
(i use latest version on github)

Thanks.
Lionel

**Comment by marxenegls** [comment]
you seriously expect anyone can understand or even help you with just that statement ?
"Tor isnt use in portscan_tcp." 
wtf
 which platform are you on ? mac / windows / linux /docker /vm 
 which tor ? is it a bundle ? 
 which firewall rules if any have you set ? 
 which python version is installed ?
etc 
it's been 11 days and you got 0 comments -
what's the plan , are you gonna revise or close ? 
do you still care ??? 
hail Mary ... ...

**Comment by bcoles** [comment]
> you seriously expect anyone can understand or even help you with just that statement ?

Normally I would agree but the OP is correct and this is a legitimate issue. There is a lot of functionality which does not use TOR.

TOR support was added mostly to allowing accessing .onion addresses.

As for port scanning over TOR, this would require scanning using TCP connections rather than SYN scanning, which sucks.

> it's been 11 days and you got 0 comments

I haven't replied because it is not a simple answer and the problem is deeper than only the port scanning functionality.

**Comment by lprat** [comment]
@marxenegls:
I just checked that the tool that says go through tor actually goes through tor, and found that it doesn't have to be ... I don't know why you seem pissed off. You just have to do a scan with this module on a server that you control to verify ... My question was simple, just to know if it was wanted or not by the developers of the project.

@bcoles:
The module not use Syn Flag (https://github.com/smicallef/spiderfoot/blob/master/modules/sfp_portscan_tcp.py), it's full connexion.

I found the solution to the problem (well that was a problem for me).
In call 'safeSocket()' or 'safeSSLSocket()' [only called by sfp_portscan_tcp.py module], not use SOCKS proxy (tor).
https://github.com/smicallef/spiderfoot/blob/bcb221b06a884a9254489cb63b456cba33264530/sflib.py#L1550
https://github.com/smicallef/spiderfoot/blob/bcb221b06a884a9254489cb63b456cba33264530/sflib.py#L1556
You can add TOR use by:
26d25
< import socks
1553,1554d1551
<         socks.setdefaultproxy(socks.PROXY_TYPE_SOCKS5, "127.0.0.1", 9050)
<         socket.socket = socks.socksocket
1561,1562d1557
<         socks.setdefaultproxy(socks.PROXY_TYPE_SOCKS5, "127.0.0.1", 9050)
<         socket.socket = socks.socksocket
This code is not clean because I forced the use of TOR. Normally, you would have to look at the general conf and use TOR when you want (with the parameters of the server indicated).

In any case, thank you to the project developer, because it's a great project.
Lionel
