### ISSUE TITLE
AttributeError: 'module' object has no attribute 'engine'

### ISSUE THREAD

**Issue by fcano** [smicallef/spiderfoot#66]
I have just downloaded the tar.gz and then cloned the Github repository and when I try to execute sf.py I get the following error:

$ python sf.py 
Starting web server at http://127.0.0.1:5001 ...
Traceback (most recent call last):
  File "sf.py", line 147, in <module>
    cherrypy.engine.autoreload.unsubscribe()
AttributeError: 'module' object has no attribute 'engine'

Any ideas?

**Comment by smicallef** [comment]
What version of CherryPy are you using?

**Comment by phpsystems** [comment]
Hi,

   I get this issue too on kali linux. Cherrypy version 2.3.0-3. Running with python 2 rather than python 3.

   Tim

**Comment by smicallef** [comment]
OK, you need to be using CherryPy 3.2+, 2.3 is too old.
