### ISSUE TITLE
M2Crypto Errors (Mac OS X) - Solved

### ISSUE THREAD

**Issue by peasead** [smicallef/spiderfoot#67]
I ran into some issues with M2Crypto on my Mac. Sorry, I don't have the exact error codes, but it involved importing different modules. 

The issues appears to be with swig 3.0.5.

To fix this:
```
sudo -H pip uninstall M2Crypto
brew uninstall swig
brew install pcre
brew install homebrew/versions/swig304
sudo -H pip install M2Crypto
```

This is tangentially discussed in Issue #26

**Comment by smicallef** [comment]
Thanks for coming back with an update.. clearly I will have to produce dedicated guidance for installation on Mac soon.

**Comment by peasead** [comment]
No problem man. 

Cheers

- Andrew D. Pease
