### ISSUE TITLE
 Not able to handle multiple scan properly. Mainly DB update part ! 

### ISSUE THREAD

**Issue by priyalviroja** [smicallef/spiderfoot#68]
**System: Linux (Kali) \* 64** 

Below are the traceback log of unhandled exception (SystemExit) encountered during scan. 

1) **Scan A (Error)**

['Traceback (most recent call last):\n', '  File "/root/Downloads/spiderfoot-2.4.0/sfscan.py", line 226, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/root/Downloads/spiderfoot-2.4.0/sflib.py", line 1291, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/root/Downloads/spiderfoot-2.4.0/modules/sfp_dns.py", line 214, in handleEvent\n    self.processHost(addr, parentEvent, False)\n', '  File "/root/Downloads/spiderfoot-2.4.0/modules/sfp_dns.py", line 378, in processHost\n    self.notifyListeners(evt)\n', '  File "/root/Downloads/spiderfoot-2.4.0/sflib.py", line 1291, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/root/Downloads/spiderfoot-2.4.0/modules/sfp_spider.py", line 254, in handleEvent\n    return self.spiderFrom(spiderTarget)\n', '  File "/root/Downloads/spiderfoot-2.4.0/modules/sfp_spider.py", line 278, in spiderFrom\n    links = self.processUrl(startingPoint)  # fetch first page\n', '  File "/root/Downloads/spiderfoot-2.4.0/modules/sfp_spider.py", line 121, in processUrl\n    self.urlEvents[link] = self.linkNotify(link, self.urlEvents[url])\n', '  File "/root/Downloads/spiderfoot-2.4.0/modules/sfp_spider.py", line 183, in linkNotify\n    self.notifyListeners(event)\n', '  File "/root/Downloads/spiderfoot-2.4.0/sflib.py", line 1291, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/root/Downloads/spiderfoot-2.4.0/modules/sfp_junkfiles.py", line 87, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/root/Downloads/spiderfoot-2.4.0/sflib.py", line 1291, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/root/Downloads/spiderfoot-2.4.0/modules/sfp__stor_db.py", line 51, in handleEvent\n    self.**sfdb**.scanEventStore(self.getScanId(), sfEvent)\n', '  File "/root/Downloads/spiderfoot-2.4.0/sfdb.py", line 607, in scanEventStore\n    self.sf.fatal("SQL error encountered when storing event data (" + str(self.dbh) + ": " + e.args[0])\n', '  File "/root/Downloads/spiderfoot-2.4.0/sflib.py", line 279, in fatal\n    sys.exit(-1)\n', 'SystemExit: -1\n']

2) **Scan B (Error)**

 ['Traceback (most recent call last):\n', '  File "/root/Downloads/spiderfoot-2.4.0/sfscan.py", line 226, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/root/Downloads/spiderfoot-2.4.0/sflib.py", line 1291, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/root/Downloads/spiderfoot-2.4.0/modules/sfp_bingsearch.py", line 64, in handleEvent\n    timeout=self.opts[\'_fetchtimeout\']))\n', '  File "/root/Downloads/spiderfoot-2.4.0/sflib.py", line 1073, in bingIterate\n    timeout=opts[\'timeout\'], useragent=opts[\'useragent\'])\n', '  File "/root/Downloads/spiderfoot-2.4.0/sflib.py", line 880, in fetchUrl\n    header[\'User-Agent\'] + "] [timeout: " + str(timeout) + "]")\n', '  File "/root/Downloads/spiderfoot-2.4.0/sflib.py", line 299, in info\n    self._dblog("INFO", message, modName)\n', '  File "/root/Downloads/spiderfoot-2.4.0/sflib.py", line 263, in _dblog\n    return self.dbh.scanLogEvent(self.GUID, level, message, component)\n', '  File "/root/Downloads/spiderfoot-2.4.0/sfdb.py", line 290, in scanLogEvent\n    self.sf.fatal("Unable to log event in DB due to lock: " + e.args[0])\n', '  File "/root/Downloads/spiderfoot-2.4.0/sflib.py", line 279, in fatal\n    sys.exit(-1)\n', 'SystemExit: -1\n']

**Comment by smicallef** [comment]
Yes this seems to be a limitation of SQLite. I am working on supporting an alternative back-end for the next version.
