### ISSUE TITLE
abuse.ch no longer works for domains

### ISSUE THREAD

**Issue by hisomu** [smicallef/spiderfoot#687]
I was trying out numerous domains against the abuse.ch domain, and noticed it was returning the following in the logs:

```
Traceback (most recent call last):
   File "/home/spiderfoot/sflib.py", line 2224, in fetchUrl
    result['content'] = res.content.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 16: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spiderfoot/sflib.py", line 2226, in fetchUrl
    result['content'] = res.content.decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcd in position 10: ordinal not in range(128)

Unexpected exception ('ascii' codec can't decode byte 0xcd in position 10: ordinal not in range(128)) occurred fetching: https://urlhaus.abuse.ch/downloads/csv/
```

Based on the error above it has trouble reading https://urlhaus.abuse.ch/downloads/csv, I assume at one point it was CSV file and it is now returning as a ZIP file. Should it be changed online only active malware urls CSV (https://urlhaus.abuse.ch/downloads/csv_online/) or plain text URL List (https://urlhaus.abuse.ch/downloads/text/)?

In the source code for the abuse.ch module (https://github.com/smicallef/spiderfoot/blob/master/modules/sfp_abusech.py), it searches the following sites:
https://zeustracker.abuse.ch/blocklist.php?download=baddomains (Permanently DOWN)
https://zeustracker.abuse.ch/blocklist.php?download=badips (Permanently DOWN)
https://urlhaus.abuse.ch/downloads/csv
https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt (Permanently DOWN)
https://feodotracker.abuse.ch/downloads/ipblocklist.txt
https://sslbl.abuse.ch/blacklist/sslipblacklist.csv

Should the zeustracker and ransomwaretracker be removed, and is there any new abuse.ch sites that should be added?

**Comment by bcoles** [comment]
Hey. Thanks for the report. Yeah this module is old and needs a lot of work.

> Based on the error above it has trouble reading https://urlhaus.abuse.ch/downloads/csv, I assume at one point it was CSV file and it is now returning as a ZIP file

This is a bug and needs to be fixed.

> Should the zeustracker and ransomwaretracker be removed

The items you've listed as `Permanently DOWN` should be removed.

> and is there any new abuse.ch sites that should be added?

The module should be updated to support [bazaar.abuse.ch](https://bazaar.abuse.ch/) API and perhaps others.

**Comment by hisomu** [comment]
Thank you! Would you happen to have an ETA when it should be fixed? :)

**Comment by smicallef** [comment]
Thanks for flagging these issues. The dead sources are removed and I've replaced the now-ZIP file with a fresher 30-day text file.
