### ISSUE TITLE
add bitcoin search in Spiderfoot UI

### ISSUE THREAD

**Issue by hisomu** [smicallef/spiderfoot#695]
When searching for a bitcoin address 35ua53N3oVdJ1ZxG29dNWFUvFYwnHj7FYc in spiderfoot UI against Blockchain and IntelX, I get the following error:
`Invalid target type. Could not recognize it as a human name, IP address, IP subnet, ASN, domain name or host name.`

I also tried using quotes "35ua53N3oVdJ1ZxG29dNWFUvFYwnHj7FYc", and it came back thinking the bitcoin address was a Username.

Would it be possible to support bitcoin addresses within the search?

**Comment by smicallef** [comment]
We'll likely do this for 3.3 (so after 3.2 which is days away). If you have sources to collect info about addresses that you'd recommend (beyond what we already have), we can build some modules to query them.

**Comment by bcoles** [comment]
bitcoinabuse.com is one potential data source:

```
https://www.bitcoinabuse.com/reports/35ua53N3oVdJ1ZxG29dNWFUvFYwnHj7FYc
```

**Comment by smicallef** [comment]
bitcoinwhoiswho.com is another:

```https://bitcoinwhoswho.com/address/136h2378m9yaLpcCtfnAW93jPZ6uZUmLzN```

**Comment by smicallef** [comment]
Done in https://github.com/smicallef/spiderfoot/pull/1025
