### ISSUE TITLE
Social Media False Positivies

### ISSUE THREAD

**Issue by felixrr** [smicallef/spiderfoot#71]
Hi,

Spotted these false positives.  When actually visiting the suggested link it seems the web service is returning a custom 404 which isn't being identified correctly by SpiderFoot.  These are the sites that produce false positive:

singlemuslim (dating)
Printfection (shopping)
Muzy (images)
GeekGrade (social)
Break (video)

If I get a chance (but don't hold your breath) I will try and make some updates to correct this.

**Comment by WebBreacher** [comment]
Hey all. @jcran and I have been working to fix the original list of sites in the recon-ng source. We will probably be moving it to its own project to more-easily maintain it. The latest staging branch of recon-ng has the updated list. It still is not 100% but soon will be.

**Comment by smicallef** [comment]
That would be great @WebBreacher. For now I've made some tweaks to the various FP-producing modules which are applied in Github.

**Comment by WebBreacher** [comment]
The new "super project" for this will be at
https://github.com/WebBreacher/WhatsMyName. The data is in a different JSON
format and we will be writing/using a script to auto-check if the links are
broken. @jcran does this already in intrigue-core project.

So stay tuned.
