### ISSUE TITLE
expected string or buffer error

### ISSUE THREAD

**Issue by Kvetch** [smicallef/spiderfoot#74]
Hi,
I getting the following error whenever I run a scan.  I should note I am running 2.5.0 (downloaded from github) on OSX.  Anyone have any suggestions for a workaround or fix?
Thanks

Time	Component	Type	Event
2015-08-10 23:02:37	SpiderFoot	STATUS	
Scan [xxxxxxxxxxxxxxxxxxxxxxxx] failed: expected string or buffer
2015-08-10 23:02:37	SpiderFoot	ERROR	
Unhandled exception (TypeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/Applications/spiderfoot-master/sfscan.py", line 255, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/Applications/spiderfoot-master/sflib.py", line 1398, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/Applications/spiderfoot-master/modules/sfp_dns.py", line 220, in handleEvent\n    self.processHost(addr, parentEvent, False)\n', '  File "/Applications/spiderfoot-master/modules/sfp_dns.py", line 391, in processHost\n    self.processDomain(dom, evt)\n', '  File "/Applications/spiderfoot-master/modules/sfp_dns.py", line 408, in processDomain\n    self.notifyListeners(domevt)\n', '  File "/Applications/spiderfoot-master/sflib.py", line 1398, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/Applications/spiderfoot-master/modules/sfp_whois.py", line 75, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/Applications/spiderfoot-master/sflib.py", line 1398, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/Applications/spiderfoot-master/modules/sfp_email.py", line 81, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/Applications/spiderfoot-master/sflib.py", line 1398, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/Applications/spiderfoot-master/modules/sfp_accounts.py", line 368, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/Applications/spiderfoot-master/sflib.py", line 1398, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/Applications/spiderfoot-master/modules/sfp_coderepo.py", line 158, in handleEvent\n    repret = json.loads(res[\'content\'])\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads\n    return _default_decoder.decode(s)\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n', 'TypeError: expected string or buffer\n']

**Comment by smicallef** [comment]
Just applied a fix to Github for this. It will also be included in 2.5.1 or 2.6.0.

**Comment by smicallef** [comment]
Fixed in 2.5.1 which has just been released.
