### ISSUE TITLE
Feature Request: Mark Items as False Positives

### ISSUE THREAD

**Issue by felixrr** [smicallef/spiderfoot#75]
Hi Guys,

I use this a reasonable amount and I was thinking about the results.  I would love to be able to include the output graphs in some of my reports but as there are quite a few false positives I find myself not doing.

Would it be possible to add a feature to mark things as false positives and therefore not process them any further and not include them in graphs etc?

Thanks

Felix

**Comment by smicallef** [comment]
Yep, good idea. Will work on this for the next major release - 2.6, which I hope to have out by mid October.

**Comment by felixrr** [comment]
Awesome!

**Comment by smicallef** [comment]
The functionality for this is now on Github.. give it a shot and let me know how you go.

**Comment by smicallef** [comment]
Implemented as of 2.6.0.
