### ISSUE TITLE
Issue with regex search

### ISSUE THREAD

**Issue by Wingless-Archangel** [smicallef/spiderfoot#76]
After I tried to search via regex which they mentioned that I need to use '/' to encapsulate the regex. However, after the encapsulation, they pinged the error without any details to fix as shown below

```
Failure: AJAX Error: error
```
the query string is "/*@agoda.com/"

**Comment by smicallef** [comment]
Definitely appears to be a bug. I'll have this fixed for the next release.

**Comment by smicallef** [comment]
Fixed now.
