### ISSUE TITLE
Install on Kali2

### ISSUE THREAD

**Issue by macubergeek** [smicallef/spiderfoot#77]
Installed all the dependencies on Kali2 with apt-get install
when I run sf.py I get error:

Starting web server at http://127.0.0.1:5001 ...
Traceback (most recent call last):
  File "./sf.py", line 150, in <module>
    cherrypy.engine.autoreload.unsubscribe()
AttributeError: 'module' object has no attribute 'engine'

Please ignore.
Just updated to latest version of Cherrypy and everything works fine.

**Comment by smicallef** [comment]
Hi - could you see what version of CherryPy is installed? That error is typically associated with an older version of CherryPy being installed.

**Comment by macubergeek** [comment]
thanks checked it and installed latest version of Cherrypy and it works fine now.
