### ISSUE TITLE
no result from pastebin

### ISSUE THREAD

**Issue by Wingless-Archangel** [smicallef/spiderfoot#78]
After I tried several scan, I couldn't find any results from Pastebin. But, I could get the result by searching manually in the google.

**Comment by smicallef** [comment]
Yes, this is likely due to Google blocking you. I suggest using TOR to get around this. See http://www.spiderfoot.net/news/spiderfoot-and-tor/

**Comment by Wingless-Archangel** [comment]
got this after tried to run the pastebin module only!

```
Failed to fetch content from Google.

HTTP code 400 encountered for https://www.google.com/search?q=site:pastie.org +"agoda"&ie=utf-8&oe=utf-8&aq=t&rls=org.mozilla:en-US:official&client=firefox-a
```

**Comment by Wingless-Archangel** [comment]
Found a way to fix it. I changed the seedUrl from /search to /?gws_rd as shown below

```python
seedUrl = u"https://www.google.com/?gws_rd=cr#q={0}".format(searchString)
````

However the result return junk

```
Found a link: http://k.html.SafeStyle.f
````

**Comment by theinfecteddrake** [comment]
@smicallef Python itself has a [google](https://pypi.org/project/google) module for searching via console. I guess it would be fine enough to use that module simply while using dorks.
