### ISSUE TITLE
Adding Plugin

### ISSUE THREAD

**Issue by threatcrowd** [smicallef/spiderfoot#81]
Hi!

 I'm trying to write a plugin for the ThreatCrowd API ( https://github.com/threatcrowd/ApiV2 ) but I'm having issues getting my plugin to appear in the WebUI.

 I'm running the windows .exe - do I need to run from within python instead to get the new plugin to appear? If so I'll try linux, as I'm having some issues getting the python version to run on Windows.

Thanks!

**Comment by HackershubNL** [comment]
Hey,
according to an existing issue: #10 modules have to be compiled to function on Windows. I guess Linux is the easiest options to use for development.

**Comment by smicallef** [comment]
Yep, that's correct. On windows you cannot just drop-in a module, it has to be compiled.

**Comment by smicallef** [comment]
For this particular capability, I suggest trying to work it into sfp_malcheck.py rather than creating a separate module.

**Comment by threatcrowd** [comment]
Cool I'll take a look - thanks
