### ISSUE TITLE
I'd really like to start SpiderFoot from Opensuse systemd

### ISSUE THREAD

**Issue by lpingree** [smicallef/spiderfoot#82]
But when I do I get errors when connecting to port 5001. It runs ok when executed directly by root, but for whatever reason it doesn't like being executed during boot. It does seem that it has something to do with the path, because I get a can't find file error. Any ideas? Am I missing something stupid?

**Comment by smicallef** [comment]
Can you perhaps share the script used to start it, and the error you get?

**Comment by GIJack** [comment]
I wrote a package for ArchLinux, includes systemd unit

**Comment by lpingree** [comment]
Thanks!

**Comment by lvh** [comment]
Looks like this one can probably be closed? :)

**Comment by lpingree** [comment]
Yes thanks

**Comment by bcoles** [comment]
I'm not sure what the original issue was, but here's a service file for SystemD for anyone who stumbles on this thread in the future:

```ini
[Unit]
Description=SpiderFoot service.

[Service]
Type=simple
Restart=always
RestartSec=3
StartLimitBurst=5
User=spiderfoot
Group=spiderfoot
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=spiderfoot
ExecStart=/home/spiderfoot/venv/bin/python3 /home/spiderfoot/sf.py -l 127.0.0.1:5001
WorkingDirectory=/home/spiderfoot/

[Install]
WantedBy=multi-user.target
```

This presumes you're using a virtual environment for Python version and dependency management. You should probably do this. Alternatively, simply replace `/home/spiderfoot/venv/bin/python3` with `python3`.

**Comment by GIJack** [comment]
bcoles - Legitimately don't do this:
```
ExecStart=/home/spiderfoot/venv/bin/python3 /home/spiderfoot/sf.py -l 127.0.0.1:5001
```

Set an environment file instead of hardcoding port and listen IP.
