### ISSUE TITLE
Move downloads from SourceForge to Github

### ISSUE THREAD

**Issue by kruug** [smicallef/spiderfoot#83]
Due to recent malicious actions by SourceForge, I would recommend moving all downloads to your GitHub release page.

**Comment by smicallef** [comment]
OK, will do.

**Comment by AntonioMeireles** [comment]
@smicallef - also, while on this, FWIW, no release post 2.5.1 is properly tagged in the source git tree here on github which is kind of... sad.

**Comment by smicallef** [comment]
Ah crap, you're right! I had a script to do this automatically with each release but seems to have broken a couple of releases back. I'll tag the current codebase as 2.6.1 and ensure every release is tagged going forward. Thanks!

**Comment by AntonioMeireles** [comment]
@smicallef fwiw this can be closed now :-) (and thanks!)
