### ISSUE TITLE
Failure: AJAX Error: error 

### ISSUE THREAD

**Issue by davidmoneil** [smicallef/spiderfoot#85]
When running a query against 'website.com' on all modules I got the following error when the records reached 1000 (not sure if the number of records is related to the 

Failure: AJAX Error: error 

WHen I click OK - it shows again.

**Comment by smicallef** [comment]
The number should not be relevant to the error. Can you show me any javascript errors in your browser console?

**Comment by smicallef** [comment]
Do you still get this error with 2.6.1?

**Comment by brandybrice** [comment]
Hi

Same error here. It's seems to happen when there is many result. (I use it via docker)

**Comment by nickwinn** [comment]
Can confirm this bug is back.
