### ISSUE TITLE
failed: descriptor 'capitalize' requires a 'unicode' object but received a 'str'

### ISSUE THREAD

**Issue by mussi** [smicallef/spiderfoot#88]
Unhandled exception (TypeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/home/spiderfoot/sfscan.py", line 255, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/home/spiderfoot/sflib.py", line 1399, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_bingsearch.py", line 82, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1399, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_dns.py", line 164, in handleEvent\n    self.processHost(match[1], parentEvent, affiliate=False)\n', '  File "/home/spiderfoot/modules/sfp_dns.py", line 391, in processHost\n    self.processDomain(dom, evt)\n', '  File "/home/spiderfoot/modules/sfp_dns.py", line 408, in processDomain\n    self.notifyListeners(domevt)\n', '  File "/home/spiderfoot/sflib.py", line 1399, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_pastes.py", line 98, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1399, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_dns.py", line 164, in handleEvent\n    self.processHost(match[1], parentEvent, affiliate=False)\n', '  File "/home/spiderfoot/modules/sfp_dns.py", line 387, in processHost\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1399, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_bingsearch.py", line 103, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1399, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_spider.py", line 254, in handleEvent\n    return self.spiderFrom(spiderTarget)\n', '  File "/home/spiderfoot/modules/sfp_spider.py", line 281, in spiderFrom\n    links = self.processUrl(startingPoint)  # fetch first page\n', '  File "/home/spiderfoot/modules/sfp_spider.py", line 98, in processUrl\n    self.contentNotify(url, fetched, self.urlEvents[url])\n', '  File "/home/spiderfoot/modules/sfp_spider.py", line 190, in contentNotify\n    self.notifyListeners(event)\n', '  File "/home/spiderfoot/sflib.py", line 1399, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_dns.py", line 164, in handleEvent\n    self.processHost(match[1], parentEvent, affiliate=False)\n', '  File "/home/spiderfoot/modules/sfp_dns.py", line 387, in processHost\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1399, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_bingsearch.py", line 103, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1399, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_spider.py", line 254, in handleEvent\n    return self.spiderFrom(spiderTarget)\n', '  File "/home/spiderfoot/modules/sfp_spider.py", line 281, in spiderFrom\n    links = self.processUrl(startingPoint)  # fetch first page\n', '  File "/home/spiderfoot/modules/sfp_spider.py", line 121, in processUrl\n    self.urlEvents[link] = self.linkNotify(link, self.urlEvents[url])\n', '  File "/home/spiderfoot/modules/sfp_spider.py", line 183, in linkNotify\n    self.notifyListeners(event)\n', '  File "/home/spiderfoot/sflib.py", line 1399, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_sslcert.py", line 105, in handleEvent\n    self.notifyListeners(rawevt)\n', '  File "/home/spiderfoot/sflib.py", line 1399, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_email.py", line 84, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/home/spiderfoot/sflib.py", line 1399, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/home/spiderfoot/modules/sfp_names.py", line 89, in handleEvent\n    name = " ".join(map(unicode.capitalize, eventData.split("@")[0].split(".")))\n', "TypeError: descriptor 'capitalize' requires a 'unicode' object but received a 'str'\n"]

**Comment by smicallef** [comment]
I'm having a hard time re-producing this. Could you maybe e-mail me the target you are running this against so I can test it? support at spiderfoot.net.

**Comment by smicallef** [comment]
This should be fixed with the latest changes I've made - could you pull the latest version and try again?
