### ISSUE TITLE
docker build error : swig is unable to find opensslconf.h

### ISSUE THREAD

**Issue by glenux** [smicallef/spiderfoot#90]
Running ``docker build -t spiderfoot .`` fails with the following error.
    
    SWIG/_evp.i:12: Error: Unable to find 'openssl/opensslconf.h'
    
    SWIG/_ec.i:7: Error: Unable to find 'openssl/opensslconf.h'
    
    error: command 'swig' failed with exit status 1
    
    ----------------------------------------
    Cleaning up...
    Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/M2Crypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-aadMXe-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/M2Crypto
    Storing debug log for failure in /root/.pip/pip.log
    The command '/bin/sh -c rm -rf /var/lib/apt/lists/*   && pip install cherrypy lxml mako M2Crypto netaddr' returned a non-zero code: 1

I fixed it locally with the following changes : 

    diff --git a/Dockerfile b/Dockerfile
    index 1781df6..d868895 100644
    --- a/Dockerfile
    +++ b/Dockerfile
    @@ -25,8 +25,11 @@ RUN apt-get update && apt-get install -y \
       python-dev \
       python-lxml \
       swig \
    -  --no-install-recommends \
    -  && rm -rf /var/lib/apt/lists/* \
    +  --no-install-recommends
    +
    +RUN rm -rf /var/lib/apt/lists/* \
    +  && cd /usr/include/openssl/ \
    +  && ln -s ../x86_64-linux-gnu/openssl/opensslconf.h . \
       && pip install cherrypy lxml mako M2Crypto netaddr
     
     # Create a dedicated/non-privileged user to run the app.

Best regards,

**Comment by smicallef** [comment]
Included, thanks!
