### ISSUE TITLE
Error when running with tor 

### ISSUE THREAD

**Issue by jteslaxxx** [smicallef/spiderfoot#92]
I keep getting this error when use tor!!

 Time 	Component	Type	Event
2015-12-13 19:58:07	SpiderFoot	STATUS	

Scan [f15532d96dbac4d6c0d2ab28419704f8894352f550ce81508f45f2e45f942737] failed: -1

2015-12-13 19:58:07	SpiderFoot	ERROR	

Unhandled exception (SystemExit) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/root/Tools/Intelligence/spiderfoot/sfscan.py", line 255, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/root/Tools/Intelligence/spiderfoot/sflib.py", line 1399, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/root/Tools/Intelligence/spiderfoot/modules/sfp_bingsearch.py", line 82, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/root/Tools/Intelligence/spiderfoot/sflib.py", line 1399, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/root/Tools/Intelligence/spiderfoot/modules/sfp_dns.py", line 164, in handleEvent\n    self.processHost(match[1], parentEvent, affiliate=False)\n', '  File "/root/Tools/Intelligence/spiderfoot/modules/sfp_dns.py", line 387, in processHost\n    self.notifyListeners(evt)\n', '  File "/root/Tools/Intelligence/spiderfoot/sflib.py", line 1399, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/root/Tools/Intelligence/spiderfoot/modules/sfp_bingsearch.py", line 82, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/root/Tools/Intelligence/spiderfoot/sflib.py", line 1399, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/root/Tools/Intelligence/spiderfoot/modules/sfp_dns.py", line 164, in handleEvent\n    self.processHost(match[1], parentEvent, affiliate=False)\n', '  File "/root/Tools/Intelligence/spiderfoot/modules/sfp_dns.py", line 391, in processHost\n    self.processDomain(dom, evt)\n', '  File "/root/Tools/Intelligence/spiderfoot/modules/sfp_dns.py", line 408, in processDomain\n    self.notifyListeners(domevt)\n', '  File "/root/Tools/Intelligence/spiderfoot/sflib.py", line 1399, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/root/Tools/Intelligence/spiderfoot/modules/sfp_darksearch.py", line 67, in handleEvent\n    timeout=self.opts[\'_fetchtimeout\']))\n', '  File "/root/Tools/Intelligence/spiderfoot/sflib.py", line 1006, in googleIterate\n    self.refreshTorIdent()\n', '  File "/root/Tools/Intelligence/spiderfoot/sflib.py", line 77, in refreshTorIdent\n    self.fatal("Unable to re-circuit TOR: " + str(e))\n', '  File "/root/Tools/Intelligence/spiderfoot/sflib.py", line 302, in fatal\n    sys.exit(-1)\n', 'SystemExit: -1\n']

Thanks
system kali linux 2.0

**Comment by smicallef** [comment]
Have you definitely run TOR as it's explained in the tutorial?

http://www.spiderfoot.net/news/spiderfoot-and-tor/

**Comment by jteslaxxx** [comment]
yes
