### ISSUE TITLE
Unable to decode whois result

### ISSUE THREAD

**Issue by enderax** [smicallef/spiderfoot#94]
I got this error.

> Unable to perform WHOIS on XXX.com.tr: 'utf8' codec can't decode byte 0xfd in position 30: invalid start byte

There are some workarounds for this:
[stackoverflow](https://stackoverflow.com/questions/6180521/unicodedecodeerror-utf8-codec-cant-decode-bytes-in-position-3-6-invalid-dat)

After this error, it says 'Running' but it seems stopped

**Comment by smicallef** [comment]
Should be fixed now on github - could you pull the latest version and give it a go?

**Comment by enderax** [comment]
I got the error on Windows but couldn't install now. So I tried it on Kali and it seems fixed. Thanks!
