### ISSUE TITLE
SpiderFoot Scan Error 

### ISSUE THREAD

**Issue by MiChaelinzo** [smicallef/spiderfoot#949]
<img width="592" alt="spiderfooterror" src="https://user-images.githubusercontent.com/68110223/91639089-bb43fb80-ea1c-11ea-9bcb-55ab16047ddc.PNG">
https://pastebin.com/ybVrBnNS

**Comment by bcoles** [comment]
It looks like DNS resolution is failing. Can you resolve `publicsuffix.org` ?

**Comment by MiChaelinzo** [comment]
also when i navigate to scans tab it just loads endlessly
<img width="170" alt="spiderfooterro2" src="https://user-images.githubusercontent.com/68110223/91641505-89876080-ea2d-11ea-8449-1d959023fa8a.PNG">

**Comment by MiChaelinzo** [comment]
> It looks like DNS resolution is failing. Can you resolve `publicsuffix.org` ?

i can access  the site

**Comment by MiChaelinzo** [comment]
This problem happens only it the v3.2-DEV not in my v3.0

**Comment by MiChaelinzo** [comment]
<img width="555" alt="get post" src="https://user-images.githubusercontent.com/68110223/91642754-965c8200-ea36-11ea-830c-ea8c24445d72.PNG">

**Comment by bcoles** [comment]
> also when i navigate to scans tab it just loads endlessly
> This problem happens only it the v3.2-DEV not in my v3.0

This is a different issue.

* Are you using the latest version of SpiderFoot from the `master` branch?
* On what operating system?
* On what version of Python?
* Do you get an error messages in the browser console?

**Comment by MiChaelinzo** [comment]
> > also when i navigate to scans tab it just loads endlessly
> > This problem happens only it the v3.2-DEV not in my v3.0
> 
> This is a different issue.
> 
> * Are you using the latest version of SpiderFoot from the `master` branch?
> * On what operating system?
> * On what version of Python?
> * Do you get an error messages in the browser console?

Yes I am
5.7.0-kali1-amd64
Python 3.8.5
Mozilla Firefox 68.11.0esr

**Comment by smicallef** [comment]
Could you share the contents of the browser console (if using Firefox, go to the top right hamburger menu -> Web Developer -> Web Console) and check for any errors reported when you aren't seeing the page load.

**Comment by MiChaelinzo** [comment]
<img width="722" alt="spiderfoot1 2" src="https://user-images.githubusercontent.com/68110223/92519241-4ba2ed00-f222-11ea-9660-9c5ff01f20fe.PNG">

> Could you share the contents of the browser console (if using Firefox, go to the top right hamburger menu -> Web Developer -> Web Console) and check for any errors reported when you aren't seeing the page load.

**Comment by bcoles** [comment]
Thanks for providing the web console output. The JavScript issue should now be resolved.
