### ISSUE TITLE
ModuleNotFoundError: No module named 'exifread'

### ISSUE THREAD

**Issue by hledger** [smicallef/spiderfoot#958]
While installing the requirements, not the exifread python module is not found. Please assist.

~/spiderfoot $ pip install "ExifRead==2.1.2"
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting ExifRead==2.1.2
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://www.piwheels.org/simple/exifread/

**Comment by bcoles** [comment]
Is `pip` on your system pointing to `pip3` (for Python3) ?

```
$ pip --version
pip 20.2.2 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)
```

You could try:

```
pip3 install -r requirements.txt
```

**Comment by leotrubach** [comment]
Wondering where "ExifRead==2.1.2" is coming from?
In requirements i see exifread>=2.1.2.
