### ISSUE TITLE
Yahoo pages with no useful information

### ISSUE THREAD

**Issue by thesoulkiller** [smicallef/spiderfoot#97]
Hi,
I've been trying the application to create a whole OSINT report. I encountered an issue that tbl_scan_results.data for Yahoo search returns a html page where it has 
`We did not find results for: intitle:"some data about target" site:plus.google.com.`
I attached that html file.
I don't know yet, if another module has the same issue. Could you please add a filter for these types of results, because it is hard to analyze.
[bu-ne.txt](https://github.com/smicallef/spiderfoot/files/140888/bu-ne.txt)

Thank you.
-Barış

**Comment by thesoulkiller** [comment]
This one is more beautiful :) 
[bu-ne.txt](https://github.com/smicallef/spiderfoot/files/141497/bu-ne.txt)

**Comment by smicallef** [comment]
Should be solved now.
