### ISSUE TITLE
Unhandled exception (UnicodeDecodeError) encountered during scan.

### ISSUE THREAD

**Issue by febrefebril** [smicallef/spiderfoot#98]
SpiderFoot  ERROR   

Unhandled exception (UnicodeDecodeError) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "/root/Downloads/spiderfoot-2.6.1/sfscan.py", line 255, in startScan\n    psMod.notifyListeners(firstEvent)\n', '  File "/root/Downloads/spiderfoot-2.6.1/sflib.py", line 1399, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/root/Downloads/spiderfoot-2.6.1/modules/sfp_dns.py", line 220, in handleEvent\n    self.processHost(addr, parentEvent, False)\n', '  File "/root/Downloads/spiderfoot-2.6.1/modules/sfp_dns.py", line 387, in processHost\n    self.notifyListeners(evt)\n', '  File "/root/Downloads/spiderfoot-2.6.1/sflib.py", line 1399, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/root/Downloads/spiderfoot-2.6.1/modules/sfp_googlesearch.py", line 104, in handleEvent\n    self.notifyListeners(evt)\n', '  File "/root/Downloads/spiderfoot-2.6.1/sflib.py", line 1399, in notifyListeners\n    listener.handleEvent(sfEvent)\n', '  File "/root/Downloads/spiderfoot-2.6.1/modules/sfp_spider.py", line 254, in handleEvent\n    return self.spiderFrom(spiderTarget)\n', '  File "/root/Downloads/spiderfoot-2.6.1/modules/sfp_spider.py", line 307, in spiderFrom\n    freshLinks = self.processUrl(link)\n', '  File "/root/Downloads/spiderfoot-2.6.1/modules/sfp_spider.py", line 101, in processUrl\n    self.sf.debug("Redirect of " + url + " to " + fetched[\'realurl\'])\n', "UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 75: ordinal not in range(128)\n"]

This happens every time i try to scan a specific domain

**Comment by smicallef** [comment]
If possible could you privately e-mail me (support@spiderfoot.net) the target so I can re-produce this error?

**Comment by smicallef** [comment]
This should be fixed with the latest changes I've made - could you pull the latest version and try again?
