### ISSUE TITLE
[win]Unhandled exception (SystemExit) encountered

### ISSUE THREAD

**Issue by Xyntax** [smicallef/spiderfoot#99]
Unhandled exception (SystemExit) encountered during scan. Please report this as a bug: ['Traceback (most recent call last):\n', '  File "sfscan.pyc", line 255, in startScan\n', '  File "sflib.pyc", line 1399, in notifyListeners\n', '  File "modules\sfp_dns.pyc", line 244, in handleEvent\n', '  File "modules\sfp_dns.pyc", line 301, in resolveIP\n', '  File "sflib.pyc", line 322, in info\n', '  File "sflib.pyc", line 286, in _dblog\n', '  File "sfdb.pyc", line 319, in scanLogEvent\n', '  File "sflib.pyc", line 302, in fatal\n', 'SystemExit: -1\n']

**Comment by Xyntax** [comment]
this happens everytime i start full scan with **ip**
eg
211.142.198.190
120.25.1.207
112.74.202.175

**Comment by smicallef** [comment]
I cannot re-produce this. Are you sure there are no issues at your end? Maybe disk is full?
