### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by ojaschauhan44** [smicallef/spiderfoot#995]
python3 sf.py -l 0.0.0.0:5001
  File "sf.py", line 168
    raise ValueError(f"Module {modName} has multiple categories defined but only one is supported.")

**Comment by ojaschauhan44** [comment]
python3 ./sf.py -l 0.0.0.0:5001
  File "sf.py", line 168
    raise ValueError(f"Module {modName} has multiple categories defined but only one is supported.")
                                                                                                                                                               ^
SyntaxError: invalid syntax

**Comment by bcoles** [comment]
Can you show the full stack trace please?

Also, which version of SpiderFoot are you using?

**Comment by bcoles** [comment]
SpiderFoot requires Python 3.6.

There's a check to ensure that Python 3.6+ is in use, but obviously this is never executed if the Python interpreter bails out due to being unable to parse syntax elsewhere in the file.
