### ISSUE TITLE
Syntax error line 154

### ISSUE THREAD

**Issue by ojaschauhan44** [smicallef/spiderfoot#996]
python3 ./sf.py -l 0.0.0.0:5001
  File "./sf.py", line 154
    log.critical(f"Modules directory does not exist: {mod_dir}")
                                                                                             ^
SyntaxError: invalid syntax

**Comment by bcoles** [comment]
Can you show the full stack trace please?

Also, which version of SpiderFoot are you using?

**Comment by leotrubach** [comment]
Probably Python 3.5, where f-strings are not yet supported.

**Comment by bcoles** [comment]
SpiderFoot requires Python 3.6.

There's a check to ensure that Python 3.6+ is in use, but obviously this is never executed if the Python interpreter bails out due to being unable to parse syntax elsewhere in the file.
